//
// Generated by JavaToPas v1.5 20160713 - 141449
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.FormElement;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tag,
  org.jsoup.nodes.Attributes,
  org.jsoup.nodes.Element,
  org.jsoup.Connection;

type
  JFormElement = interface;

  JFormElementClass = interface(JObjectClass)
    ['{741B6F93-495F-4E5E-996B-D6211B9F4BC5}']
    function addElement(element : JElement) : JFormElement; cdecl;              // (Lorg/jsoup/nodes/Element;)Lorg/jsoup/nodes/FormElement; A: $1
    function elements : JElements; cdecl;                                       // ()Lorg/jsoup/select/Elements; A: $1
    function formData : JList; cdecl;                                           // ()Ljava/util/List; A: $1
    function init(tag : JTag; baseUri : JString; attributes : JAttributes) : JFormElement; cdecl;// (Lorg/jsoup/parser/Tag;Ljava/lang/String;Lorg/jsoup/nodes/Attributes;)V A: $1
    function submit : JConnection; cdecl;                                       // ()Lorg/jsoup/Connection; A: $1
  end;

  [JavaSignature('org/jsoup/nodes/FormElement')]
  JFormElement = interface(JObject)
    ['{2BAA13DB-33D7-495D-BB99-38C14A9DA15C}']
    function addElement(element : JElement) : JFormElement; cdecl;              // (Lorg/jsoup/nodes/Element;)Lorg/jsoup/nodes/FormElement; A: $1
    function elements : JElements; cdecl;                                       // ()Lorg/jsoup/select/Elements; A: $1
    function formData : JList; cdecl;                                           // ()Ljava/util/List; A: $1
    function submit : JConnection; cdecl;                                       // ()Lorg/jsoup/Connection; A: $1
  end;

  TJFormElement = class(TJavaGenericImport<JFormElementClass, JFormElement>)
  end;

implementation

end.
