//
// Generated by JavaToPas v1.5 20160713 - 141510
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator = interface;

  JEvaluatorClass = interface(JObjectClass)
    ['{EBAABEC4-A428-49E7-9D6D-CBEE69AEBABE}']
    function matches(JElementparam0 : JElement; JElementparam1 : JElement) : boolean; cdecl;// (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $401
  end;

  [JavaSignature('org/jsoup/select/Evaluator$MatchesOwn')]
  JEvaluator = interface(JObject)
    ['{97315163-F833-4E2E-A1D4-19399965EA74}']
    function matches(JElementparam0 : JElement; JElementparam1 : JElement) : boolean; cdecl;// (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $401
  end;

  TJEvaluator = class(TJavaGenericImport<JEvaluatorClass, JEvaluator>)
  end;

implementation

end.
