//
// Generated by JavaToPas v1.5 20160713 - 141455
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_4;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder,
  org.jsoup.parser.TreeBuilder;

type
  JHtmlTreeBuilderState_4 = interface;

  JHtmlTreeBuilderState_4Class = interface(JObjectClass)
    ['{3E8D74E9-C389-4C1A-8D22-4C6DC06C7F2F}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_4')]
  JHtmlTreeBuilderState_4 = interface(JObject)
    ['{F585CB19-EC2C-416F-8F5F-A6F7C2536516}']
  end;

  TJHtmlTreeBuilderState_4 = class(TJavaGenericImport<JHtmlTreeBuilderState_4Class, JHtmlTreeBuilderState_4>)
  end;

implementation

end.
