//
// Generated by JavaToPas v1.5 20160713 - 141455
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_7;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_7 = interface;

  JHtmlTreeBuilderState_7Class = interface(JObjectClass)
    ['{C160F311-FFF8-4485-B627-EA741225F633}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_7')]
  JHtmlTreeBuilderState_7 = interface(JObject)
    ['{D04EC88F-E2B4-47CE-B852-4E977F4177BC}']
  end;

  TJHtmlTreeBuilderState_7 = class(TJavaGenericImport<JHtmlTreeBuilderState_7Class, JHtmlTreeBuilderState_7>)
  end;

implementation

end.
