//
// Generated by JavaToPas v1.5 20160713 - 141454
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_17;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_17 = interface;

  JHtmlTreeBuilderState_17Class = interface(JObjectClass)
    ['{2D5DFE57-CA4F-45A3-9CCD-AF11AE1FFFD4}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_17')]
  JHtmlTreeBuilderState_17 = interface(JObject)
    ['{7AEFB62C-75D7-4414-9AE3-BE8AA3734F65}']
  end;

  TJHtmlTreeBuilderState_17 = class(TJavaGenericImport<JHtmlTreeBuilderState_17Class, JHtmlTreeBuilderState_17>)
  end;

implementation

end.
