//
// Generated by JavaToPas v1.5 20160713 - 141454
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_22;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_22 = interface;

  JHtmlTreeBuilderState_22Class = interface(JObjectClass)
    ['{D97F22EE-3D25-4F6E-B817-8653844E77DE}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_22')]
  JHtmlTreeBuilderState_22 = interface(JObject)
    ['{90725922-3AAF-40B0-80D5-CDFF104CB40D}']
  end;

  TJHtmlTreeBuilderState_22 = class(TJavaGenericImport<JHtmlTreeBuilderState_22Class, JHtmlTreeBuilderState_22>)
  end;

implementation

end.
