//
// Generated by JavaToPas v1.5 20160713 - 141447
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Element_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element,
  org.jsoup.nodes.Document;

type
  JElement_1 = interface;

  JElement_1Class = interface(JObjectClass)
    ['{4F0C4EC5-5056-4965-A330-555461B3DC54}']
    procedure head(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  [JavaSignature('org/jsoup/nodes/Element_1')]
  JElement_1 = interface(JObject)
    ['{0A3B2212-3460-4E5C-88E9-55AF9A247ED0}']
    procedure head(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  TJElement_1 = class(TJavaGenericImport<JElement_1Class, JElement_1>)
  end;

implementation

end.
