//
// Generated by JavaToPas v1.5 20160713 - 141505
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.XmlTreeBuilder;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.ParseErrorList,
  org.jsoup.parser.Token,
  org.jsoup.nodes.Document,
  org.jsoup.nodes.Element,
  org.jsoup.parser.Token_StartTag,
  org.jsoup.parser.Token_EndTag;

type
  JXmlTreeBuilder = interface;

  JXmlTreeBuilderClass = interface(JObjectClass)
    ['{916658C2-5978-4BDF-95EF-239740F0D1E6}']
    function init : JXmlTreeBuilder; cdecl;                                     // ()V A: $1
  end;

  [JavaSignature('org/jsoup/parser/XmlTreeBuilder')]
  JXmlTreeBuilder = interface(JObject)
    ['{B1D13F55-F224-41A5-82C5-856F0B12D991}']
  end;

  TJXmlTreeBuilder = class(TJavaGenericImport<JXmlTreeBuilderClass, JXmlTreeBuilder>)
  end;

implementation

end.
