//
// Generated by JavaToPas v1.5 20160713 - 141504
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_8;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_8 = interface;

  JTokeniserState_8Class = interface(JObjectClass)
    ['{F3B33A5A-E884-4C41-AA59-6A33FA3B6DA3}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_8')]
  JTokeniserState_8 = interface(JObject)
    ['{F7F517F6-C63B-4361-8641-E0331EB0B850}']
  end;

  TJTokeniserState_8 = class(TJavaGenericImport<JTokeniserState_8Class, JTokeniserState_8>)
  end;

implementation

end.
