//
// Generated by JavaToPas v1.5 20160713 - 141441
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.examples.ListLinks;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JListLinks = interface;

  JListLinksClass = interface(JObjectClass)
    ['{1D8555D3-D29B-4ABE-9918-C97239557AB6}']
    function init : JListLinks; cdecl;                                          // ()V A: $1
    procedure main(args : TJavaArray<JString>) ; cdecl;                         // ([Ljava/lang/String;)V A: $9
  end;

  [JavaSignature('org/jsoup/examples/ListLinks')]
  JListLinks = interface(JObject)
    ['{C23866D8-1C4E-4EFD-BC13-6DD1A9BD926A}']
  end;

  TJListLinks = class(TJavaGenericImport<JListLinksClass, JListLinks>)
  end;

implementation

end.
