//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_34;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_34 = interface;

  JTokeniserState_34Class = interface(JObjectClass)
    ['{29C04E9B-AD7A-47DC-9ECA-78DA6F845428}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_34')]
  JTokeniserState_34 = interface(JObject)
    ['{20EC88EA-2468-4D8F-9503-DA16FF02AD58}']
  end;

  TJTokeniserState_34 = class(TJavaGenericImport<JTokeniserState_34Class, JTokeniserState_34>)
  end;

implementation

end.
