//
// Generated by JavaToPas v1.5 20160713 - 141440
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.examples.HtmlToPlainText_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JHtmlToPlainText_1 = interface;

  JHtmlToPlainText_1Class = interface(JObjectClass)
    ['{9C90403B-B176-449B-9DAA-06C3A010C4F0}']
  end;

  [JavaSignature('org/jsoup/examples/HtmlToPlainText_1')]
  JHtmlToPlainText_1 = interface(JObject)
    ['{C0D059B4-AF01-4151-BBE0-C634575E89FB}']
  end;

  TJHtmlToPlainText_1 = class(TJavaGenericImport<JHtmlToPlainText_1Class, JHtmlToPlainText_1>)
  end;

implementation

end.
