//
// Generated by JavaToPas v1.5 20160713 - 141506
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.safety.Whitelist_Protocol;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JWhitelist_Protocol = interface;

  JWhitelist_ProtocolClass = interface(JObjectClass)
    ['{7650263B-FA37-4BD1-B56C-12D3FA62F86A}']
  end;

  [JavaSignature('org/jsoup/safety/Whitelist_Protocol')]
  JWhitelist_Protocol = interface(JObject)
    ['{97EA6B26-3DB7-459D-9289-92E69363831D}']
  end;

  TJWhitelist_Protocol = class(TJavaGenericImport<JWhitelist_ProtocolClass, JWhitelist_Protocol>)
  end;

implementation

end.
