//
// Generated by JavaToPas v1.5 20160713 - 141440
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.Connection_Method;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JConnection_Method = interface;

  JConnection_MethodClass = interface(JObjectClass)
    ['{349E652D-D6BD-4451-82C8-2B3A985CBC21}']
    function _GetDELETE : JConnection_Method; cdecl;                            //  A: $4019
    function _GetGET : JConnection_Method; cdecl;                               //  A: $4019
    function _GetHEAD : JConnection_Method; cdecl;                              //  A: $4019
    function _GetOPTIONS : JConnection_Method; cdecl;                           //  A: $4019
    function _GetPATCH : JConnection_Method; cdecl;                             //  A: $4019
    function _GetPOST : JConnection_Method; cdecl;                              //  A: $4019
    function _GetPUT : JConnection_Method; cdecl;                               //  A: $4019
    function _GetTRACE : JConnection_Method; cdecl;                             //  A: $4019
    function hasBody : boolean; cdecl;                                          // ()Z A: $11
    function valueOf(&name : JString) : JConnection_Method; cdecl;              // (Ljava/lang/String;)Lorg/jsoup/Connection$Method; A: $9
    function values : TJavaArray<JConnection_Method>; cdecl;                    // ()[Lorg/jsoup/Connection$Method; A: $9
    property DELETE : JConnection_Method read _GetDELETE;                       // Lorg/jsoup/Connection$Method; A: $4019
    property GET : JConnection_Method read _GetGET;                             // Lorg/jsoup/Connection$Method; A: $4019
    property HEAD : JConnection_Method read _GetHEAD;                           // Lorg/jsoup/Connection$Method; A: $4019
    property OPTIONS : JConnection_Method read _GetOPTIONS;                     // Lorg/jsoup/Connection$Method; A: $4019
    property PATCH : JConnection_Method read _GetPATCH;                         // Lorg/jsoup/Connection$Method; A: $4019
    property POST : JConnection_Method read _GetPOST;                           // Lorg/jsoup/Connection$Method; A: $4019
    property PUT : JConnection_Method read _GetPUT;                             // Lorg/jsoup/Connection$Method; A: $4019
    property TRACE : JConnection_Method read _GetTRACE;                         // Lorg/jsoup/Connection$Method; A: $4019
  end;

  [JavaSignature('org/jsoup/Connection_Method')]
  JConnection_Method = interface(JObject)
    ['{B31EDC49-787B-46E6-90B4-4FE534D292E5}']
  end;

  TJConnection_Method = class(TJavaGenericImport<JConnection_MethodClass, JConnection_Method>)
  end;

implementation

end.
