//
// Generated by JavaToPas v1.5 20160713 - 141508
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_AllElements;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_AllElements = interface;

  JEvaluator_AllElementsClass = interface(JObjectClass)
    ['{F12A2B1F-4568-4B84-80D0-798497B1007F}']
    function init : JEvaluator_AllElements; cdecl;                              // ()V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_AllElements')]
  JEvaluator_AllElements = interface(JObject)
    ['{1B1D9C80-51F6-4AE6-9A34-BE653A4B9BD2}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_AllElements = class(TJavaGenericImport<JEvaluator_AllElementsClass, JEvaluator_AllElements>)
  end;

implementation

end.
