//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_66;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_66 = interface;

  JTokeniserState_66Class = interface(JObjectClass)
    ['{AF83F24D-226D-4D31-B4DD-4F0F15D46997}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_66')]
  JTokeniserState_66 = interface(JObject)
    ['{B8BD3FEF-1A5B-42C0-BFD2-ADA3BA490ED7}']
  end;

  TJTokeniserState_66 = class(TJavaGenericImport<JTokeniserState_66Class, JTokeniserState_66>)
  end;

implementation

end.
