//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_43;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_43 = interface;

  JTokeniserState_43Class = interface(JObjectClass)
    ['{50FB72E0-29F6-4F7F-BFFC-5A40829B2495}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_43')]
  JTokeniserState_43 = interface(JObject)
    ['{7E761A17-B1C8-445E-9E24-D29121D2EA21}']
  end;

  TJTokeniserState_43 = class(TJavaGenericImport<JTokeniserState_43Class, JTokeniserState_43>)
  end;

implementation

end.
