//
// Generated by JavaToPas v1.5 20160713 - 141458
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.Token_EOF;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token;

type
  JToken_EOF = interface;

  JToken_EOFClass = interface(JObjectClass)
    ['{EC28AE63-E91D-41C8-9A04-1CA22BAB4EB8}']
  end;

  [JavaSignature('org/jsoup/parser/Token_EOF')]
  JToken_EOF = interface(JObject)
    ['{4C3046D1-5370-4101-8D03-4CB8E20824A7}']
  end;

  TJToken_EOF = class(TJavaGenericImport<JToken_EOFClass, JToken_EOF>)
  end;

implementation

end.
