//
// Generated by JavaToPas v1.5 20160713 - 141456
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_9;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_9 = interface;

  JHtmlTreeBuilderState_9Class = interface(JObjectClass)
    ['{A6C5D7A8-4FBE-4856-9A5D-8BDC533CB5D5}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_9')]
  JHtmlTreeBuilderState_9 = interface(JObject)
    ['{EA5012D4-37AF-4C88-8697-89431522AE65}']
  end;

  TJHtmlTreeBuilderState_9 = class(TJavaGenericImport<JHtmlTreeBuilderState_9Class, JHtmlTreeBuilderState_9>)
  end;

implementation

end.
