//
// Generated by JavaToPas v1.5 20160713 - 141449
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Entities_EscapeMode;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JEntities_EscapeMode = interface;

  JEntities_EscapeModeClass = interface(JObjectClass)
    ['{6C7C408B-26C6-40F4-850B-1D530B0FE020}']
    function _Getbase : JEntities_EscapeMode; cdecl;                            //  A: $4019
    function _Getextended : JEntities_EscapeMode; cdecl;                        //  A: $4019
    function _Getxhtml : JEntities_EscapeMode; cdecl;                           //  A: $4019
    function getMap : JMap; cdecl;                                              // ()Ljava/util/Map; A: $1
    function valueOf(&name : JString) : JEntities_EscapeMode; cdecl;            // (Ljava/lang/String;)Lorg/jsoup/nodes/Entities$EscapeMode; A: $9
    function values : TJavaArray<JEntities_EscapeMode>; cdecl;                  // ()[Lorg/jsoup/nodes/Entities$EscapeMode; A: $9
    property base : JEntities_EscapeMode read _Getbase;                         // Lorg/jsoup/nodes/Entities$EscapeMode; A: $4019
    property extended : JEntities_EscapeMode read _Getextended;                 // Lorg/jsoup/nodes/Entities$EscapeMode; A: $4019
    property xhtml : JEntities_EscapeMode read _Getxhtml;                       // Lorg/jsoup/nodes/Entities$EscapeMode; A: $4019
  end;

  [JavaSignature('org/jsoup/nodes/Entities_EscapeMode')]
  JEntities_EscapeMode = interface(JObject)
    ['{AFC3D4D3-DB6D-4A92-BC79-8113BC31FB2A}']
    function getMap : JMap; cdecl;                                              // ()Ljava/util/Map; A: $1
  end;

  TJEntities_EscapeMode = class(TJavaGenericImport<JEntities_EscapeModeClass, JEntities_EscapeMode>)
  end;

implementation

end.
