//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_21;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_21 = interface;

  JTokeniserState_21Class = interface(JObjectClass)
    ['{DD1ACCC9-F463-4427-B3FB-2153DEEE1BEE}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_21')]
  JTokeniserState_21 = interface(JObject)
    ['{32CB0FC7-EE05-4C20-BA6C-E5AB7620A291}']
  end;

  TJTokeniserState_21 = class(TJavaGenericImport<JTokeniserState_21Class, JTokeniserState_21>)
  end;

implementation

end.
