//
// Generated by JavaToPas v1.5 20160713 - 141446
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Document_OutputSettings_Syntax;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JDocument_OutputSettings_Syntax = interface;

  JDocument_OutputSettings_SyntaxClass = interface(JObjectClass)
    ['{A9896D99-4B2A-40FF-AA75-ABE0DEDDB707}']
    function _Gethtml : JDocument_OutputSettings_Syntax; cdecl;                 //  A: $4019
    function _Getxml : JDocument_OutputSettings_Syntax; cdecl;                  //  A: $4019
    function valueOf(&name : JString) : JDocument_OutputSettings_Syntax; cdecl; // (Ljava/lang/String;)Lorg/jsoup/nodes/Document$OutputSettings$Syntax; A: $9
    function values : TJavaArray<JDocument_OutputSettings_Syntax>; cdecl;       // ()[Lorg/jsoup/nodes/Document$OutputSettings$Syntax; A: $9
    property html : JDocument_OutputSettings_Syntax read _Gethtml;              // Lorg/jsoup/nodes/Document$OutputSettings$Syntax; A: $4019
    property xml : JDocument_OutputSettings_Syntax read _Getxml;                // Lorg/jsoup/nodes/Document$OutputSettings$Syntax; A: $4019
  end;

  [JavaSignature('org/jsoup/nodes/Document_OutputSettings_Syntax')]
  JDocument_OutputSettings_Syntax = interface(JObject)
    ['{89AC050C-BCA8-45E9-801A-39180CC36B11}']
  end;

  TJDocument_OutputSettings_Syntax = class(TJavaGenericImport<JDocument_OutputSettings_SyntaxClass, JDocument_OutputSettings_Syntax>)
  end;

implementation

end.
