//
// Generated by JavaToPas v1.5 20160713 - 141454
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_23;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_23 = interface;

  JHtmlTreeBuilderState_23Class = interface(JObjectClass)
    ['{EE022C52-9398-43F9-ADB2-D02D19A3549F}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_23')]
  JHtmlTreeBuilderState_23 = interface(JObject)
    ['{E125EB9F-8CEF-4006-869A-41CC5BCF4A65}']
  end;

  TJHtmlTreeBuilderState_23 = class(TJavaGenericImport<JHtmlTreeBuilderState_23Class, JHtmlTreeBuilderState_23>)
  end;

implementation

end.
