//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_14;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_14 = interface;

  JTokeniserState_14Class = interface(JObjectClass)
    ['{9DCB0138-639B-4169-8269-38E487D30817}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_14')]
  JTokeniserState_14 = interface(JObject)
    ['{3EE994CF-B344-40DF-8116-3CD3E5AD8308}']
  end;

  TJTokeniserState_14 = class(TJavaGenericImport<JTokeniserState_14Class, JTokeniserState_14>)
  end;

implementation

end.
