//
// Generated by JavaToPas v1.5 20160713 - 141446
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Attributes;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.LinkedHashMap,
  org.jsoup.nodes.Attribute,
  java.lang.Appendable,
  org.jsoup.nodes.Document_OutputSettings;

type
  JAttributes = interface;

  JAttributesClass = interface(JObjectClass)
    ['{E0DF97A0-7D1C-4E45-90DA-D441ED321F16}']
    function asList : JList; cdecl;                                             // ()Ljava/util/List; A: $1
    function clone : JAttributes; cdecl;                                        // ()Lorg/jsoup/nodes/Attributes; A: $1
    function dataset : JMap; cdecl;                                             // ()Ljava/util/Map; A: $1
    function equals(o : JObject) : boolean; cdecl;                              // (Ljava/lang/Object;)Z A: $1
    function get(key : JString) : JString; cdecl;                               // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function hasKey(key : JString) : boolean; cdecl;                            // (Ljava/lang/String;)Z A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    function html : JString; cdecl; overload;                                   // ()Ljava/lang/String; A: $1
    function init : JAttributes; cdecl;                                         // ()V A: $1
    function iterator : JIterator; cdecl;                                       // ()Ljava/util/Iterator; A: $1
    function size : Integer; cdecl;                                             // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure addAll(incoming : JAttributes) ; cdecl;                           // (Lorg/jsoup/nodes/Attributes;)V A: $1
    procedure put(attribute : JAttribute) ; cdecl; overload;                    // (Lorg/jsoup/nodes/Attribute;)V A: $1
    procedure put(key : JString; value : JString) ; cdecl; overload;            // (Ljava/lang/String;Ljava/lang/String;)V A: $1
    procedure put(key : JString; value : boolean) ; cdecl; overload;            // (Ljava/lang/String;Z)V A: $1
    procedure remove(key : JString) ; cdecl;                                    // (Ljava/lang/String;)V A: $1
  end;

  [JavaSignature('org/jsoup/nodes/Attributes$Dataset')]
  JAttributes = interface(JObject)
    ['{5AD400AD-4627-4259-8A13-D737DDB90082}']
    function asList : JList; cdecl;                                             // ()Ljava/util/List; A: $1
    function clone : JAttributes; cdecl;                                        // ()Lorg/jsoup/nodes/Attributes; A: $1
    function dataset : JMap; cdecl;                                             // ()Ljava/util/Map; A: $1
    function equals(o : JObject) : boolean; cdecl;                              // (Ljava/lang/Object;)Z A: $1
    function get(key : JString) : JString; cdecl;                               // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function hasKey(key : JString) : boolean; cdecl;                            // (Ljava/lang/String;)Z A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    function html : JString; cdecl; overload;                                   // ()Ljava/lang/String; A: $1
    function iterator : JIterator; cdecl;                                       // ()Ljava/util/Iterator; A: $1
    function size : Integer; cdecl;                                             // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure addAll(incoming : JAttributes) ; cdecl;                           // (Lorg/jsoup/nodes/Attributes;)V A: $1
    procedure put(attribute : JAttribute) ; cdecl; overload;                    // (Lorg/jsoup/nodes/Attribute;)V A: $1
    procedure put(key : JString; value : JString) ; cdecl; overload;            // (Ljava/lang/String;Ljava/lang/String;)V A: $1
    procedure put(key : JString; value : boolean) ; cdecl; overload;            // (Ljava/lang/String;Z)V A: $1
    procedure remove(key : JString) ; cdecl;                                    // (Ljava/lang/String;)V A: $1
  end;

  TJAttributes = class(TJavaGenericImport<JAttributesClass, JAttributes>)
  end;

const
  TJAttributesdataPrefix = 'data-';

implementation

end.
