//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_22;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_22 = interface;

  JTokeniserState_22Class = interface(JObjectClass)
    ['{8F20A13E-EF84-4DB7-B062-32AF16BE0473}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_22')]
  JTokeniserState_22 = interface(JObject)
    ['{AB73B88F-AA76-4C17-B26E-475B43D952D9}']
  end;

  TJTokeniserState_22 = class(TJavaGenericImport<JTokeniserState_22Class, JTokeniserState_22>)
  end;

implementation

end.
