//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_65;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_65 = interface;

  JTokeniserState_65Class = interface(JObjectClass)
    ['{F1E76C55-56BA-4949-8429-02126C4C6449}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_65')]
  JTokeniserState_65 = interface(JObject)
    ['{52905914-4B98-431F-8E8D-07CDD96F9C0D}']
  end;

  TJTokeniserState_65 = class(TJavaGenericImport<JTokeniserState_65Class, JTokeniserState_65>)
  end;

implementation

end.
