//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_17;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_17 = interface;

  JTokeniserState_17Class = interface(JObjectClass)
    ['{0FDBA9B2-F541-4A35-A3F7-26000801C49F}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_17')]
  JTokeniserState_17 = interface(JObject)
    ['{876572F2-346A-4675-A58B-46FFEA867B14}']
  end;

  TJTokeniserState_17 = class(TJavaGenericImport<JTokeniserState_17Class, JTokeniserState_17>)
  end;

implementation

end.
