//
// Generated by JavaToPas v1.5 20160713 - 141454
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_24;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JHtmlTreeBuilderState_24 = interface;

  JHtmlTreeBuilderState_24Class = interface(JObjectClass)
    ['{8B265207-250D-48D0-B523-98F76CF039E1}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_24')]
  JHtmlTreeBuilderState_24 = interface(JObject)
    ['{A62EF392-FB6D-4449-8282-9560AA82F328}']
  end;

  TJHtmlTreeBuilderState_24 = class(TJavaGenericImport<JHtmlTreeBuilderState_24Class, JHtmlTreeBuilderState_24>)
  end;

implementation

end.
