//
// Generated by JavaToPas v1.5 20160713 - 141507
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.CombiningEvaluator_Or;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.select.Evaluator,
  org.jsoup.nodes.Element;

type
  JCombiningEvaluator_Or = interface;

  JCombiningEvaluator_OrClass = interface(JObjectClass)
    ['{67DF89D8-AB3D-484D-A1CF-F0991B1A9160}']
    function matches(root : JElement; node : JElement) : boolean; cdecl;        // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure add(e : JEvaluator) ; cdecl;                                      // (Lorg/jsoup/select/Evaluator;)V A: $1
  end;

  [JavaSignature('org/jsoup/select/CombiningEvaluator_Or')]
  JCombiningEvaluator_Or = interface(JObject)
    ['{7C511F7D-BF03-4852-BA60-6498903F5676}']
    function matches(root : JElement; node : JElement) : boolean; cdecl;        // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure add(e : JEvaluator) ; cdecl;                                      // (Lorg/jsoup/select/Evaluator;)V A: $1
  end;

  TJCombiningEvaluator_Or = class(TJavaGenericImport<JCombiningEvaluator_OrClass, JCombiningEvaluator_Or>)
  end;

implementation

end.
