//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_19;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_19 = interface;

  JTokeniserState_19Class = interface(JObjectClass)
    ['{65CB2E91-4E7D-49FC-A94C-32F63E675B19}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_19')]
  JTokeniserState_19 = interface(JObject)
    ['{F607F9F0-C792-4144-8141-661D752C4417}']
  end;

  TJTokeniserState_19 = class(TJavaGenericImport<JTokeniserState_19Class, JTokeniserState_19>)
  end;

implementation

end.
