//
// Generated by JavaToPas v1.5 20160713 - 141451
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.CharacterReader;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JCharacterReader = interface;

  JCharacterReaderClass = interface(JObjectClass)
    ['{5C6776BB-F5F3-4D1F-9E20-0A073C7F6E13}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/parser/CharacterReader')]
  JCharacterReader = interface(JObject)
    ['{847765C8-9798-413F-A773-1D84FDB61BFC}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJCharacterReader = class(TJavaGenericImport<JCharacterReaderClass, JCharacterReader>)
  end;

const
  TJCharacterReaderEOF = 65535;
  TJCharacterReadermaxCacheLen = 12;

implementation

end.
