//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_29;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_29 = interface;

  JTokeniserState_29Class = interface(JObjectClass)
    ['{227602E8-4D1D-4E6A-9FD6-49F7EE61D56E}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_29')]
  JTokeniserState_29 = interface(JObject)
    ['{C3F47651-ED18-4BD1-9EA9-DA46CB5521A4}']
  end;

  TJTokeniserState_29 = class(TJavaGenericImport<JTokeniserState_29Class, JTokeniserState_29>)
  end;

implementation

end.
