//
// Generated by JavaToPas v1.5 20160713 - 141457
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.ParseErrorList;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JParseErrorList = interface;

  JParseErrorListClass = interface(JObjectClass)
    ['{F3B6A26F-C982-4EA6-977B-0B0881C2A936}']
  end;

  [JavaSignature('org/jsoup/parser/ParseErrorList')]
  JParseErrorList = interface(JObject)
    ['{ECF046A8-F2E7-4D7B-8C19-20FF0756E346}']
  end;

  TJParseErrorList = class(TJavaGenericImport<JParseErrorListClass, JParseErrorList>)
  end;

const
  TJParseErrorListINITIAL_CAPACITY = 16;

implementation

end.
