//
// Generated by JavaToPas v1.5 20160713 - 141510
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_IsOnlyOfType;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_IsOnlyOfType = interface;

  JEvaluator_IsOnlyOfTypeClass = interface(JObjectClass)
    ['{A6EA0337-C91F-4602-A9AA-CB6355C9DE8A}']
    function init : JEvaluator_IsOnlyOfType; cdecl;                             // ()V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_IsOnlyOfType')]
  JEvaluator_IsOnlyOfType = interface(JObject)
    ['{7C674629-3E22-4F83-B3AD-973A4FC6ADA5}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_IsOnlyOfType = class(TJavaGenericImport<JEvaluator_IsOnlyOfTypeClass, JEvaluator_IsOnlyOfType>)
  end;

implementation

end.
