//
// Generated by JavaToPas v1.5 20160713 - 141508
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_AttributeStarting;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_AttributeStarting = interface;

  JEvaluator_AttributeStartingClass = interface(JObjectClass)
    ['{73645225-7EEB-4F5C-9199-A7C5796AD7E5}']
    function init(keyPrefix : JString) : JEvaluator_AttributeStarting; cdecl;   // (Ljava/lang/String;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_AttributeStarting')]
  JEvaluator_AttributeStarting = interface(JObject)
    ['{EE168331-8BA8-4DE8-87F5-D9173F3004F3}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_AttributeStarting = class(TJavaGenericImport<JEvaluator_AttributeStartingClass, JEvaluator_AttributeStarting>)
  end;

implementation

end.
