//
// Generated by JavaToPas v1.5 20160713 - 141510
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_IsRoot;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_IsRoot = interface;

  JEvaluator_IsRootClass = interface(JObjectClass)
    ['{0ADE32C9-DE99-4A9B-81BD-4A4827C6BD1D}']
    function init : JEvaluator_IsRoot; cdecl;                                   // ()V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_IsRoot')]
  JEvaluator_IsRoot = interface(JObject)
    ['{D141EB57-C3F5-4839-83C7-4162B3922711}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_IsRoot = class(TJavaGenericImport<JEvaluator_IsRootClass, JEvaluator_IsRoot>)
  end;

implementation

end.
