//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_32;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_32 = interface;

  JTokeniserState_32Class = interface(JObjectClass)
    ['{FC3EA216-EF55-4EEB-9EFE-21806CBE7A10}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_32')]
  JTokeniserState_32 = interface(JObject)
    ['{93045E44-087E-4E59-8F37-71E9420267AC}']
  end;

  TJTokeniserState_32 = class(TJavaGenericImport<JTokeniserState_32Class, JTokeniserState_32>)
  end;

implementation

end.
