//
// Generated by JavaToPas v1.5 20160713 - 141454
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_20;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_20 = interface;

  JHtmlTreeBuilderState_20Class = interface(JObjectClass)
    ['{1C9510BA-A257-4185-B43B-51D752ABD865}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_20')]
  JHtmlTreeBuilderState_20 = interface(JObject)
    ['{3A06993C-4A0D-4973-B7CF-F87F80E9CDBA}']
  end;

  TJHtmlTreeBuilderState_20 = class(TJavaGenericImport<JHtmlTreeBuilderState_20Class, JHtmlTreeBuilderState_20>)
  end;

implementation

end.
