//
// Generated by JavaToPas v1.5 20160713 - 141509
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_CssNthEvaluator;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_CssNthEvaluator = interface;

  JEvaluator_CssNthEvaluatorClass = interface(JObjectClass)
    ['{EA223167-FA06-4A0E-9AA5-C75C514BE088}']
    function init(a : Integer; b : Integer) : JEvaluator_CssNthEvaluator; cdecl; overload;// (II)V A: $1
    function init(b : Integer) : JEvaluator_CssNthEvaluator; cdecl; overload;   // (I)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_CssNthEvaluator')]
  JEvaluator_CssNthEvaluator = interface(JObject)
    ['{8B5B7995-5ECA-45CB-AF0D-A42A31B74A8F}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_CssNthEvaluator = class(TJavaGenericImport<JEvaluator_CssNthEvaluatorClass, JEvaluator_CssNthEvaluator>)
  end;

implementation

end.
