//
// Generated by JavaToPas v1.5 20160713 - 141510
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_MatchesOwn;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.regex.Pattern,
  org.jsoup.nodes.Element;

type
  JEvaluator_MatchesOwn = interface;

  JEvaluator_MatchesOwnClass = interface(JObjectClass)
    ['{BD3299F5-1CB6-4D60-B825-7C821410A3B0}']
    function init(pattern : JPattern) : JEvaluator_MatchesOwn; cdecl;           // (Ljava/util/regex/Pattern;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_MatchesOwn')]
  JEvaluator_MatchesOwn = interface(JObject)
    ['{438BDD5E-3094-4A6C-9C6A-07C33C2459C1}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_MatchesOwn = class(TJavaGenericImport<JEvaluator_MatchesOwnClass, JEvaluator_MatchesOwn>)
  end;

implementation

end.
