//
// Generated by JavaToPas v1.5 20160713 - 141458
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.Token;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token_TokenType,
  org.jsoup.parser.Token_StartTag,
  org.jsoup.parser.Token_EndTag;

type
  JToken_Character = interface; // merged
  JToken_Comment = interface; // merged
  JToken_Doctype = interface; // merged
  JToken = interface;

  JTokenClass = interface(JObjectClass)
    ['{DFF08691-E73A-4D81-B359-432C83A02D8D}']
  end;

  [JavaSignature('org/jsoup/parser/Token$TokenType')]
  JToken = interface(JObject)
    ['{BA28BCE5-5ABB-407B-BDF5-647A2A9433B6}']
  end;

  TJToken = class(TJavaGenericImport<JTokenClass, JToken>)
  end;

  // Merged from: .\org.jsoup.parser.Token_Doctype.pas
  JToken_DoctypeClass = interface(JObjectClass)
    ['{6A03A2F9-C907-4407-96B3-DBBA993DBC3F}']
    function getSystemIdentifier : JString; cdecl;                              // ()Ljava/lang/String; A: $1
    function isForceQuirks : boolean; cdecl;                                    // ()Z A: $1
  end;

  [JavaSignature('org/jsoup/parser/Token_Doctype')]
  JToken_Doctype = interface(JObject)
    ['{8839562F-35C2-4EBA-BDEA-D2C8DD2194E5}']
    function getSystemIdentifier : JString; cdecl;                              // ()Ljava/lang/String; A: $1
    function isForceQuirks : boolean; cdecl;                                    // ()Z A: $1
  end;

  TJToken_Doctype = class(TJavaGenericImport<JToken_DoctypeClass, JToken_Doctype>)
  end;


  // Merged from: .\org.jsoup.parser.Token_Comment.pas
  JToken_CommentClass = interface(JObjectClass)
    ['{8C41F7E7-F9B4-4F5A-8472-8C29B92CC266}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/parser/Token_Comment')]
  JToken_Comment = interface(JObject)
    ['{2E7B3866-88E1-46D6-B8B2-DB1F0B6F96CC}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJToken_Comment = class(TJavaGenericImport<JToken_CommentClass, JToken_Comment>)
  end;


  // Merged from: .\org.jsoup.parser.Token_Character.pas
  JToken_CharacterClass = interface(JObjectClass)
    ['{30DB8002-30E6-401C-8543-7A9980A46091}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/parser/Token_Character')]
  JToken_Character = interface(JObject)
    ['{9DAA81E3-333A-4B95-9D41-6FCDD34FEA01}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJToken_Character = class(TJavaGenericImport<JToken_CharacterClass, JToken_Character>)
  end;


implementation

end.
