//
// Generated by JavaToPas v1.5 20160713 - 141445
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.helper.W3CDom_W3CBuilder;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.w3c.dom.Document,
  org.w3c.dom.Element,
  org.jsoup.nodes.Document,
  org.jsoup.nodes.Element;

type
  JW3CDom_W3CBuilder = interface;

  JW3CDom_W3CBuilderClass = interface(JObjectClass)
    ['{A916C3C8-93BD-4656-B2B8-D591DF86AD3A}']
    function init(doc : JDocument) : JW3CDom_W3CBuilder; cdecl;                 // (Lorg/w3c/dom/Document;)V A: $1
    procedure head(source : JNode; depth : Integer) ; cdecl;                    // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(source : JNode; depth : Integer) ; cdecl;                    // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  [JavaSignature('org/jsoup/helper/W3CDom_W3CBuilder')]
  JW3CDom_W3CBuilder = interface(JObject)
    ['{A7DB8084-B42E-469B-9A78-765D4A7C1479}']
    procedure head(source : JNode; depth : Integer) ; cdecl;                    // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(source : JNode; depth : Integer) ; cdecl;                    // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  TJW3CDom_W3CBuilder = class(TJavaGenericImport<JW3CDom_W3CBuilderClass, JW3CDom_W3CBuilder>)
  end;

const
  TJW3CDom_W3CBuilderxmlnsKey = 'xmlns';
  TJW3CDom_W3CBuilderxmlnsPrefix = 'xmlns:';

implementation

end.
