//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_53;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_53 = interface;

  JTokeniserState_53Class = interface(JObjectClass)
    ['{3E43BC12-4789-4BF8-8F93-330A26A5CCDF}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_53')]
  JTokeniserState_53 = interface(JObject)
    ['{54DA343E-FD75-4E3E-9ABD-34C4B8F4403B}']
  end;

  TJTokeniserState_53 = class(TJavaGenericImport<JTokeniserState_53Class, JTokeniserState_53>)
  end;

implementation

end.
