//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_61;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_61 = interface;

  JTokeniserState_61Class = interface(JObjectClass)
    ['{925FA068-91CB-48DC-A21C-23FF991894CB}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_61')]
  JTokeniserState_61 = interface(JObject)
    ['{8C34D3AA-C512-41AC-99D5-2AE4281F1C29}']
  end;

  TJTokeniserState_61 = class(TJavaGenericImport<JTokeniserState_61Class, JTokeniserState_61>)
  end;

implementation

end.
