//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_24;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_24 = interface;

  JTokeniserState_24Class = interface(JObjectClass)
    ['{1C46F6C4-7DB5-4B1B-9F18-E666574CCE73}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_24')]
  JTokeniserState_24 = interface(JObject)
    ['{43F97DA0-40B4-4E4D-A18F-1BB5FCA82029}']
  end;

  TJTokeniserState_24 = class(TJavaGenericImport<JTokeniserState_24Class, JTokeniserState_24>)
  end;

implementation

end.
