//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_23;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_23 = interface;

  JTokeniserState_23Class = interface(JObjectClass)
    ['{0DC58D1E-E713-48E4-9C25-6136430CDD5D}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_23')]
  JTokeniserState_23 = interface(JObject)
    ['{8122A83B-D3EE-47F8-8F1B-FC1757F167B7}']
  end;

  TJTokeniserState_23 = class(TJavaGenericImport<JTokeniserState_23Class, JTokeniserState_23>)
  end;

implementation

end.
