//
// Generated by JavaToPas v1.5 20160713 - 141508
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_Attribute;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_Attribute = interface;

  JEvaluator_AttributeClass = interface(JObjectClass)
    ['{2416456A-31BB-4535-8F3E-10030E9DB88B}']
    function init(key : JString) : JEvaluator_Attribute; cdecl;                 // (Ljava/lang/String;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_Attribute')]
  JEvaluator_Attribute = interface(JObject)
    ['{CF287824-BBBA-4084-8CAE-D86CD8162B13}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_Attribute = class(TJavaGenericImport<JEvaluator_AttributeClass, JEvaluator_Attribute>)
  end;

implementation

end.
