//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_50;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_50 = interface;

  JTokeniserState_50Class = interface(JObjectClass)
    ['{FEA94773-9DDC-46BC-8FD3-3A1BD2C6B7D6}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_50')]
  JTokeniserState_50 = interface(JObject)
    ['{49596941-9596-4B47-92F8-35F0AC2DE2A3}']
  end;

  TJTokeniserState_50 = class(TJavaGenericImport<JTokeniserState_50Class, JTokeniserState_50>)
  end;

implementation

end.
