//
// Generated by JavaToPas v1.5 20160713 - 141454
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_21;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_21 = interface;

  JHtmlTreeBuilderState_21Class = interface(JObjectClass)
    ['{7C6AAC39-2725-4EDC-AA5E-B13202432F12}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_21')]
  JHtmlTreeBuilderState_21 = interface(JObject)
    ['{63742427-ADEC-436D-805B-2DFC7E0AAD83}']
  end;

  TJHtmlTreeBuilderState_21 = class(TJavaGenericImport<JHtmlTreeBuilderState_21Class, JHtmlTreeBuilderState_21>)
  end;

implementation

end.
