//
// Generated by JavaToPas v1.5 20160713 - 141511
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.StructuralEvaluator_Root;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JStructuralEvaluator_Root = interface;

  JStructuralEvaluator_RootClass = interface(JObjectClass)
    ['{C18746B0-553A-493C-AB91-2D476BE0FCC4}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
  end;

  [JavaSignature('org/jsoup/select/StructuralEvaluator_Root')]
  JStructuralEvaluator_Root = interface(JObject)
    ['{48F6CB7E-E648-4C02-B806-CA2C79903D0B}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
  end;

  TJStructuralEvaluator_Root = class(TJavaGenericImport<JStructuralEvaluator_RootClass, JStructuralEvaluator_Root>)
  end;

implementation

end.
