//
// Generated by JavaToPas v1.5 20160713 - 141457
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.Parser;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.TreeBuilder,
  org.jsoup.parser.ParseErrorList,
  org.jsoup.nodes.Document,
  org.jsoup.nodes.Element;

type
  JParser = interface;

  JParserClass = interface(JObjectClass)
    ['{4FA86D50-02B4-48D7-AC15-827983FCBD67}']
    function getErrors : JList; cdecl;                                          // ()Ljava/util/List; A: $1
    function getTreeBuilder : JTreeBuilder; cdecl;                              // ()Lorg/jsoup/parser/TreeBuilder; A: $1
    function htmlParser : JParser; cdecl;                                       // ()Lorg/jsoup/parser/Parser; A: $9
    function init(treeBuilder : JTreeBuilder) : JParser; cdecl;                 // (Lorg/jsoup/parser/TreeBuilder;)V A: $1
    function isTrackErrors : boolean; cdecl;                                    // ()Z A: $1
    function parse(html : JString; baseUri : JString) : JDocument; cdecl;       // (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function parseBodyFragment(bodyHtml : JString; baseUri : JString) : JDocument; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function parseBodyFragmentRelaxed(bodyHtml : JString; baseUri : JString) : JDocument; deprecated; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function parseFragment(fragmentHtml : JString; context : JElement; baseUri : JString) : JList; cdecl;// (Ljava/lang/String;Lorg/jsoup/nodes/Element;Ljava/lang/String;)Ljava/util/List; A: $9
    function parseInput(html : JString; baseUri : JString) : JDocument; cdecl;  // (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $1
    function parseXmlFragment(fragmentXml : JString; baseUri : JString) : JList; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Ljava/util/List; A: $9
    function setTrackErrors(maxErrors : Integer) : JParser; cdecl;              // (I)Lorg/jsoup/parser/Parser; A: $1
    function setTreeBuilder(treeBuilder : JTreeBuilder) : JParser; cdecl;       // (Lorg/jsoup/parser/TreeBuilder;)Lorg/jsoup/parser/Parser; A: $1
    function unescapeEntities(&string : JString; inAttribute : boolean) : JString; cdecl;// (Ljava/lang/String;Z)Ljava/lang/String; A: $9
    function xmlParser : JParser; cdecl;                                        // ()Lorg/jsoup/parser/Parser; A: $9
  end;

  [JavaSignature('org/jsoup/parser/Parser')]
  JParser = interface(JObject)
    ['{834E2CFD-4FF1-4FCD-BCAD-19FE13945B02}']
    function getErrors : JList; cdecl;                                          // ()Ljava/util/List; A: $1
    function getTreeBuilder : JTreeBuilder; cdecl;                              // ()Lorg/jsoup/parser/TreeBuilder; A: $1
    function isTrackErrors : boolean; cdecl;                                    // ()Z A: $1
    function parseInput(html : JString; baseUri : JString) : JDocument; cdecl;  // (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $1
    function setTrackErrors(maxErrors : Integer) : JParser; cdecl;              // (I)Lorg/jsoup/parser/Parser; A: $1
    function setTreeBuilder(treeBuilder : JTreeBuilder) : JParser; cdecl;       // (Lorg/jsoup/parser/TreeBuilder;)Lorg/jsoup/parser/Parser; A: $1
  end;

  TJParser = class(TJavaGenericImport<JParserClass, JParser>)
  end;

const
  TJParserDEFAULT_MAX_ERRORS = 0;

implementation

end.
