//
// Generated by JavaToPas v1.5 20160713 - 141445
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.HttpStatusException;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JHttpStatusException = interface;

  JHttpStatusExceptionClass = interface(JObjectClass)
    ['{8B42CAF6-A6F6-4416-9C24-34F30D7180DF}']
    function getStatusCode : Integer; cdecl;                                    // ()I A: $1
    function getUrl : JString; cdecl;                                           // ()Ljava/lang/String; A: $1
    function init(&message : JString; statusCode : Integer; url : JString) : JHttpStatusException; cdecl;// (Ljava/lang/String;ILjava/lang/String;)V A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/HttpStatusException')]
  JHttpStatusException = interface(JObject)
    ['{2D376769-4867-46AC-B133-914FE4360695}']
    function getStatusCode : Integer; cdecl;                                    // ()I A: $1
    function getUrl : JString; cdecl;                                           // ()Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJHttpStatusException = class(TJavaGenericImport<JHttpStatusExceptionClass, JHttpStatusException>)
  end;

implementation

end.
