//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_58;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_58 = interface;

  JTokeniserState_58Class = interface(JObjectClass)
    ['{18D61290-BE15-4050-AC71-6B95183A3A4A}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_58')]
  JTokeniserState_58 = interface(JObject)
    ['{6D5F6514-0447-4FC4-8CF6-EB3319A858B9}']
  end;

  TJTokeniserState_58 = class(TJavaGenericImport<JTokeniserState_58Class, JTokeniserState_58>)
  end;

implementation

end.
