//
// Generated by JavaToPas v1.5 20160713 - 141453
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_10;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_10 = interface;

  JHtmlTreeBuilderState_10Class = interface(JObjectClass)
    ['{09AE1C09-EA2A-4B91-B4CE-F25B1D639467}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_10')]
  JHtmlTreeBuilderState_10 = interface(JObject)
    ['{135A6E21-7EF8-41B8-8EE7-0E77F168F951}']
  end;

  TJHtmlTreeBuilderState_10 = class(TJavaGenericImport<JHtmlTreeBuilderState_10Class, JHtmlTreeBuilderState_10>)
  end;

implementation

end.
