//
// Generated by JavaToPas v1.5 20160713 - 141446
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.BooleanAttribute;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JBooleanAttribute = interface;

  JBooleanAttributeClass = interface(JObjectClass)
    ['{76C46AE0-2D22-4029-AE2E-FBFC75A00F15}']
    function init(key : JString) : JBooleanAttribute; cdecl;                    // (Ljava/lang/String;)V A: $1
  end;

  [JavaSignature('org/jsoup/nodes/BooleanAttribute')]
  JBooleanAttribute = interface(JObject)
    ['{D3A3D4F5-1267-4047-86C8-027FC24CBE5E}']
  end;

  TJBooleanAttribute = class(TJavaGenericImport<JBooleanAttributeClass, JBooleanAttribute>)
  end;

implementation

end.
