//
// Generated by JavaToPas v1.5 20160713 - 141506
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.safety.Cleaner_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JCleaner_1 = interface;

  JCleaner_1Class = interface(JObjectClass)
    ['{82D2DC2F-634F-4B11-A5D4-74EBC639C764}']
  end;

  [JavaSignature('org/jsoup/safety/Cleaner_1')]
  JCleaner_1 = interface(JObject)
    ['{791B5FFE-47DB-4B48-8AC7-57EF8C502AD6}']
  end;

  TJCleaner_1 = class(TJavaGenericImport<JCleaner_1Class, JCleaner_1>)
  end;

implementation

end.
