//
// Generated by JavaToPas v1.5 20160713 - 141507
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Collector;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.select.Evaluator,
  org.jsoup.nodes.Element;

type
  JCollector = interface;

  JCollectorClass = interface(JObjectClass)
    ['{EA102692-930D-4383-A276-74985FFFCAFB}']
    function collect(eval : JEvaluator; root : JElement) : JElements; cdecl;    // (Lorg/jsoup/select/Evaluator;Lorg/jsoup/nodes/Element;)Lorg/jsoup/select/Elements; A: $9
  end;

  [JavaSignature('org/jsoup/select/Collector$Accumulator')]
  JCollector = interface(JObject)
    ['{63E661EA-4038-40AB-8D4E-BDC79F1FA0E0}']
  end;

  TJCollector = class(TJavaGenericImport<JCollectorClass, JCollector>)
  end;

implementation

end.
