//
// Generated by JavaToPas v1.5 20160713 - 141453
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_14;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder,
  org.jsoup.parser.TreeBuilder;

type
  JHtmlTreeBuilderState_14 = interface;

  JHtmlTreeBuilderState_14Class = interface(JObjectClass)
    ['{4C14C04D-526A-4C89-86EF-DE4A97AE7122}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_14')]
  JHtmlTreeBuilderState_14 = interface(JObject)
    ['{8FE1ADAB-452F-4478-B2B6-D474A7FC1D24}']
  end;

  TJHtmlTreeBuilderState_14 = class(TJavaGenericImport<JHtmlTreeBuilderState_14Class, JHtmlTreeBuilderState_14>)
  end;

implementation

end.
