//
// Generated by JavaToPas v1.5 20160713 - 141506
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.safety.Whitelist_AttributeKey;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JWhitelist_AttributeKey = interface;

  JWhitelist_AttributeKeyClass = interface(JObjectClass)
    ['{C10F50E5-3E22-4657-BDF5-386DCEBBC96D}']
  end;

  [JavaSignature('org/jsoup/safety/Whitelist_AttributeKey')]
  JWhitelist_AttributeKey = interface(JObject)
    ['{FEF128F7-CB95-44CD-A82B-53D102EAD9B5}']
  end;

  TJWhitelist_AttributeKey = class(TJavaGenericImport<JWhitelist_AttributeKeyClass, JWhitelist_AttributeKey>)
  end;

implementation

end.
