//
// Generated by JavaToPas v1.5 20160713 - 141509
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_IndexEvaluator;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JEvaluator_IndexEvaluator = interface;

  JEvaluator_IndexEvaluatorClass = interface(JObjectClass)
    ['{962B24BF-6ED2-4C7A-8E46-08E8A2A3D06C}']
    function init(&index : Integer) : JEvaluator_IndexEvaluator; cdecl;         // (I)V A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_IndexEvaluator')]
  JEvaluator_IndexEvaluator = interface(JObject)
    ['{151FD986-FFAB-4B66-B21D-B6FE2831E2CC}']
  end;

  TJEvaluator_IndexEvaluator = class(TJavaGenericImport<JEvaluator_IndexEvaluatorClass, JEvaluator_IndexEvaluator>)
  end;

implementation

end.
