//
// Generated by JavaToPas v1.5 20160713 - 141507
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.safety.Whitelist;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element,
  org.jsoup.nodes.Attribute,
  org.jsoup.nodes.Attributes;

type
  JWhitelist = interface;

  JWhitelistClass = interface(JObjectClass)
    ['{9D5E1D49-36FF-4083-82DE-EA13BEDAA5F9}']
    function addAttributes(tag : JString; keys : TJavaArray<JString>) : JWhitelist; cdecl;// (Ljava/lang/String;[Ljava/lang/String;)Lorg/jsoup/safety/Whitelist; A: $81
    function addEnforcedAttribute(tag : JString; key : JString; value : JString) : JWhitelist; cdecl;// (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/safety/Whitelist; A: $1
    function addProtocols(tag : JString; key : JString; protocols : TJavaArray<JString>) : JWhitelist; cdecl;// (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Lorg/jsoup/safety/Whitelist; A: $81
    function addTags(tags : TJavaArray<JString>) : JWhitelist; cdecl;           // ([Ljava/lang/String;)Lorg/jsoup/safety/Whitelist; A: $81
    function basic : JWhitelist; cdecl;                                         // ()Lorg/jsoup/safety/Whitelist; A: $9
    function basicWithImages : JWhitelist; cdecl;                               // ()Lorg/jsoup/safety/Whitelist; A: $9
    function init : JWhitelist; cdecl;                                          // ()V A: $1
    function none : JWhitelist; cdecl;                                          // ()Lorg/jsoup/safety/Whitelist; A: $9
    function preserveRelativeLinks(preserve : boolean) : JWhitelist; cdecl;     // (Z)Lorg/jsoup/safety/Whitelist; A: $1
    function relaxed : JWhitelist; cdecl;                                       // ()Lorg/jsoup/safety/Whitelist; A: $9
    function removeAttributes(tag : JString; keys : TJavaArray<JString>) : JWhitelist; cdecl;// (Ljava/lang/String;[Ljava/lang/String;)Lorg/jsoup/safety/Whitelist; A: $81
    function removeEnforcedAttribute(tag : JString; key : JString) : JWhitelist; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/safety/Whitelist; A: $1
    function removeProtocols(tag : JString; key : JString; protocols : TJavaArray<JString>) : JWhitelist; cdecl;// (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)Lorg/jsoup/safety/Whitelist; A: $81
    function removeTags(tags : TJavaArray<JString>) : JWhitelist; cdecl;        // ([Ljava/lang/String;)Lorg/jsoup/safety/Whitelist; A: $81
    function simpleText : JWhitelist; cdecl;                                    // ()Lorg/jsoup/safety/Whitelist; A: $9
  end;

  [JavaSignature('org/jsoup/safety/Whitelist$TypedValue')]
  JWhitelist = interface(JObject)
    ['{6F2A9490-1253-482C-A09A-00021D338A60}']
    function addEnforcedAttribute(tag : JString; key : JString; value : JString) : JWhitelist; cdecl;// (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/safety/Whitelist; A: $1
    function preserveRelativeLinks(preserve : boolean) : JWhitelist; cdecl;     // (Z)Lorg/jsoup/safety/Whitelist; A: $1
    function removeEnforcedAttribute(tag : JString; key : JString) : JWhitelist; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/safety/Whitelist; A: $1
  end;

  TJWhitelist = class(TJavaGenericImport<JWhitelistClass, JWhitelist>)
  end;

implementation

end.
