//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_18;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_18 = interface;

  JTokeniserState_18Class = interface(JObjectClass)
    ['{EA7BFE45-7255-4D48-BD7E-F09CB5FD663E}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_18')]
  JTokeniserState_18 = interface(JObject)
    ['{E55840F0-E9D8-40D4-BFB0-C3924ECFCF42}']
  end;

  TJTokeniserState_18 = class(TJavaGenericImport<JTokeniserState_18Class, JTokeniserState_18>)
  end;

implementation

end.
