//
// Generated by JavaToPas v1.5 20160713 - 141511
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.QueryParser;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.TokenQueue,
  java.util.regex.Pattern,
  org.jsoup.select.Evaluator;

type
  JQueryParser = interface;

  JQueryParserClass = interface(JObjectClass)
    ['{9C567330-83B9-43E9-BB47-E94112A79F12}']
    function parse(query : JString) : JEvaluator; cdecl; overload;              // (Ljava/lang/String;)Lorg/jsoup/select/Evaluator; A: $9
  end;

  [JavaSignature('org/jsoup/select/QueryParser')]
  JQueryParser = interface(JObject)
    ['{D48F490E-FDF3-4EA1-A12A-959CA8358C7B}']
  end;

  TJQueryParser = class(TJavaGenericImport<JQueryParserClass, JQueryParser>)
  end;

implementation

end.
