//
// Generated by JavaToPas v1.5 20160713 - 141455
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_5;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_5 = interface;

  JHtmlTreeBuilderState_5Class = interface(JObjectClass)
    ['{48F0955B-2D0B-4CBC-9F86-D1CE80469B38}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_5')]
  JHtmlTreeBuilderState_5 = interface(JObject)
    ['{7A375B0A-489F-41DA-9A88-0306F886E4C0}']
  end;

  TJHtmlTreeBuilderState_5 = class(TJavaGenericImport<JHtmlTreeBuilderState_5Class, JHtmlTreeBuilderState_5>)
  end;

implementation

end.
