//
// Generated by JavaToPas v1.5 20160713 - 141441
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.examples.HtmlToPlainText;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JHtmlToPlainText = interface;

  JHtmlToPlainTextClass = interface(JObjectClass)
    ['{7E7C9286-767A-4EB8-A9A2-225D6CC23600}']
    function getPlainText(element : JElement) : JString; cdecl;                 // (Lorg/jsoup/nodes/Element;)Ljava/lang/String; A: $1
    function init : JHtmlToPlainText; cdecl;                                    // ()V A: $1
    procedure main(args : TJavaArray<JString>) ; cdecl;                         // ([Ljava/lang/String;)V A: $89
  end;

  [JavaSignature('org/jsoup/examples/HtmlToPlainText$FormattingVisitor')]
  JHtmlToPlainText = interface(JObject)
    ['{868D5BCE-0CAB-4B62-BB5C-1B4532E210FB}']
    function getPlainText(element : JElement) : JString; cdecl;                 // (Lorg/jsoup/nodes/Element;)Ljava/lang/String; A: $1
  end;

  TJHtmlToPlainText = class(TJavaGenericImport<JHtmlToPlainTextClass, JHtmlToPlainText>)
  end;

const
  TJHtmlToPlainTextuserAgent = 'Mozilla/5.0 (jsoup)';
  TJHtmlToPlainTexttimeout = 5000;

implementation

end.
