//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_45;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_45 = interface;

  JTokeniserState_45Class = interface(JObjectClass)
    ['{091B1854-2C57-4E48-ADE5-EAFC7BA1DA4F}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_45')]
  JTokeniserState_45 = interface(JObject)
    ['{DD4059E8-67C6-4055-B61C-51BFF4F0AAC3}']
  end;

  TJTokeniserState_45 = class(TJavaGenericImport<JTokeniserState_45Class, JTokeniserState_45>)
  end;

implementation

end.
