//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_30;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_30 = interface;

  JTokeniserState_30Class = interface(JObjectClass)
    ['{71D1BD3C-1901-4B0D-B6EE-7820FA2B13F9}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_30')]
  JTokeniserState_30 = interface(JObject)
    ['{C77B0A30-869D-4746-91F8-297B0CEBA8DC}']
  end;

  TJTokeniserState_30 = class(TJavaGenericImport<JTokeniserState_30Class, JTokeniserState_30>)
  end;

implementation

end.
