//
// Generated by JavaToPas v1.5 20160713 - 141511
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.SerializationException;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JSerializationException = interface;

  JSerializationExceptionClass = interface(JObjectClass)
    ['{864E3D01-CD30-43FA-9DDF-D04AD474C062}']
    function init : JSerializationException; cdecl; overload;                   // ()V A: $1
    function init(&message : JString) : JSerializationException; cdecl; overload;// (Ljava/lang/String;)V A: $1
    function init(&message : JString; cause : JThrowable) : JSerializationException; cdecl; overload;// (Ljava/lang/String;Ljava/lang/Throwable;)V A: $1
    function init(cause : JThrowable) : JSerializationException; cdecl; overload;// (Ljava/lang/Throwable;)V A: $1
  end;

  [JavaSignature('org/jsoup/SerializationException')]
  JSerializationException = interface(JObject)
    ['{F5FAA725-B667-4B39-87CA-3329B524AAD5}']
  end;

  TJSerializationException = class(TJavaGenericImport<JSerializationExceptionClass, JSerializationException>)
  end;

implementation

end.
