//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_6;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_6 = interface;

  JTokeniserState_6Class = interface(JObjectClass)
    ['{37388037-6FAC-4BF1-969D-5E43D950813E}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_6')]
  JTokeniserState_6 = interface(JObject)
    ['{477A89E1-9A72-4BF2-9B6D-A80FC16BE88F}']
  end;

  TJTokeniserState_6 = class(TJavaGenericImport<JTokeniserState_6Class, JTokeniserState_6>)
  end;

implementation

end.
