//
// Generated by JavaToPas v1.5 20160713 - 141507
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.CombiningEvaluator_And;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.select.Evaluator,
  org.jsoup.nodes.Element;

type
  JCombiningEvaluator_And = interface;

  JCombiningEvaluator_AndClass = interface(JObjectClass)
    ['{3BB2CF25-BBCB-4CF6-8DA4-B42A6FEBDE04}']
    function matches(root : JElement; node : JElement) : boolean; cdecl;        // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/CombiningEvaluator_And')]
  JCombiningEvaluator_And = interface(JObject)
    ['{164A0A96-15BD-4B0C-8772-2485BC30B23C}']
    function matches(root : JElement; node : JElement) : boolean; cdecl;        // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJCombiningEvaluator_And = class(TJavaGenericImport<JCombiningEvaluator_AndClass, JCombiningEvaluator_And>)
  end;

implementation

end.
