//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_54;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_54 = interface;

  JTokeniserState_54Class = interface(JObjectClass)
    ['{26608693-9F51-4284-9C38-2C19CCC01FC0}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_54')]
  JTokeniserState_54 = interface(JObject)
    ['{92E41CE1-1A45-487F-8439-C49B1215BCE2}']
  end;

  TJTokeniserState_54 = class(TJavaGenericImport<JTokeniserState_54Class, JTokeniserState_54>)
  end;

implementation

end.
