//
// Generated by JavaToPas v1.5 20160713 - 141505
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokenQueue;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.lang.Character;

type
  JTokenQueue = interface;

  JTokenQueueClass = interface(JObjectClass)
    ['{5128377B-C429-4F8D-AD62-8B561D96EB3D}']
    function chompBalanced(open : Char; close : Char) : JString; cdecl;         // (CC)Ljava/lang/String; A: $1
    function chompTo(seq : JString) : JString; cdecl;                           // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function chompToIgnoreCase(seq : JString) : JString; cdecl;                 // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function consume : Char; cdecl; overload;                                   // ()C A: $1
    function consumeAttributeKey : JString; cdecl;                              // ()Ljava/lang/String; A: $1
    function consumeCssIdentifier : JString; cdecl;                             // ()Ljava/lang/String; A: $1
    function consumeElementSelector : JString; cdecl;                           // ()Ljava/lang/String; A: $1
    function consumeTagName : JString; cdecl;                                   // ()Ljava/lang/String; A: $1
    function consumeTo(seq : JString) : JString; cdecl;                         // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function consumeToAny(seq : TJavaArray<JString>) : JString; cdecl;          // ([Ljava/lang/String;)Ljava/lang/String; A: $81
    function consumeToIgnoreCase(seq : JString) : JString; cdecl;               // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function consumeWhitespace : boolean; cdecl;                                // ()Z A: $1
    function consumeWord : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function init(data : JString) : JTokenQueue; cdecl;                         // (Ljava/lang/String;)V A: $1
    function isEmpty : boolean; cdecl;                                          // ()Z A: $1
    function matchChomp(seq : JString) : boolean; cdecl;                        // (Ljava/lang/String;)Z A: $1
    function matches(seq : JString) : boolean; cdecl;                           // (Ljava/lang/String;)Z A: $1
    function matchesAny(seq : TJavaArray<Char>) : boolean; cdecl; overload;     // ([C)Z A: $81
    function matchesAny(seq : TJavaArray<JString>) : boolean; cdecl; overload;  // ([Ljava/lang/String;)Z A: $81
    function matchesCS(seq : JString) : boolean; cdecl;                         // (Ljava/lang/String;)Z A: $1
    function matchesStartTag : boolean; cdecl;                                  // ()Z A: $1
    function matchesWhitespace : boolean; cdecl;                                // ()Z A: $1
    function matchesWord : boolean; cdecl;                                      // ()Z A: $1
    function peek : Char; cdecl;                                                // ()C A: $1
    function remainder : JString; cdecl;                                        // ()Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function unescape(&in : JString) : JString; cdecl;                          // (Ljava/lang/String;)Ljava/lang/String; A: $9
    procedure addFirst(c : JCharacter) ; cdecl; overload;                       // (Ljava/lang/Character;)V A: $1
    procedure addFirst(seq : JString) ; cdecl; overload;                        // (Ljava/lang/String;)V A: $1
    procedure advance ; cdecl;                                                  // ()V A: $1
    procedure consume(seq : JString) ; cdecl; overload;                         // (Ljava/lang/String;)V A: $1
  end;

  [JavaSignature('org/jsoup/parser/TokenQueue')]
  JTokenQueue = interface(JObject)
    ['{AED8C8BC-222B-4472-9DF8-BA6CB37DBC79}']
    function chompBalanced(open : Char; close : Char) : JString; cdecl;         // (CC)Ljava/lang/String; A: $1
    function chompTo(seq : JString) : JString; cdecl;                           // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function chompToIgnoreCase(seq : JString) : JString; cdecl;                 // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function consume : Char; cdecl; overload;                                   // ()C A: $1
    function consumeAttributeKey : JString; cdecl;                              // ()Ljava/lang/String; A: $1
    function consumeCssIdentifier : JString; cdecl;                             // ()Ljava/lang/String; A: $1
    function consumeElementSelector : JString; cdecl;                           // ()Ljava/lang/String; A: $1
    function consumeTagName : JString; cdecl;                                   // ()Ljava/lang/String; A: $1
    function consumeTo(seq : JString) : JString; cdecl;                         // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function consumeToIgnoreCase(seq : JString) : JString; cdecl;               // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function consumeWhitespace : boolean; cdecl;                                // ()Z A: $1
    function consumeWord : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function isEmpty : boolean; cdecl;                                          // ()Z A: $1
    function matchChomp(seq : JString) : boolean; cdecl;                        // (Ljava/lang/String;)Z A: $1
    function matches(seq : JString) : boolean; cdecl;                           // (Ljava/lang/String;)Z A: $1
    function matchesCS(seq : JString) : boolean; cdecl;                         // (Ljava/lang/String;)Z A: $1
    function matchesStartTag : boolean; cdecl;                                  // ()Z A: $1
    function matchesWhitespace : boolean; cdecl;                                // ()Z A: $1
    function matchesWord : boolean; cdecl;                                      // ()Z A: $1
    function peek : Char; cdecl;                                                // ()C A: $1
    function remainder : JString; cdecl;                                        // ()Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure addFirst(c : JCharacter) ; cdecl; overload;                       // (Ljava/lang/Character;)V A: $1
    procedure addFirst(seq : JString) ; cdecl; overload;                        // (Ljava/lang/String;)V A: $1
    procedure advance ; cdecl;                                                  // ()V A: $1
    procedure consume(seq : JString) ; cdecl; overload;                         // (Ljava/lang/String;)V A: $1
  end;

  TJTokenQueue = class(TJavaGenericImport<JTokenQueueClass, JTokenQueue>)
  end;

const
  TJTokenQueueESC = 92;

implementation

end.
