//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_49;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_49 = interface;

  JTokeniserState_49Class = interface(JObjectClass)
    ['{AD547242-92C1-4F0B-9EEC-B96B0BF2FC18}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_49')]
  JTokeniserState_49 = interface(JObject)
    ['{E8E2C810-8A1D-4213-809D-AC4CE616BD4D}']
  end;

  TJTokeniserState_49 = class(TJavaGenericImport<JTokeniserState_49Class, JTokeniserState_49>)
  end;

implementation

end.
