//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_41;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_41 = interface;

  JTokeniserState_41Class = interface(JObjectClass)
    ['{CA866B6E-3C75-4B02-A6FF-FD2D7F77518E}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_41')]
  JTokeniserState_41 = interface(JObject)
    ['{9050970B-7969-4DBB-8D08-B75A4B06F9F9}']
  end;

  TJTokeniserState_41 = class(TJavaGenericImport<JTokeniserState_41Class, JTokeniserState_41>)
  end;

implementation

end.
