//
// Generated by JavaToPas v1.5 20160713 - 141504
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_9;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_9 = interface;

  JTokeniserState_9Class = interface(JObjectClass)
    ['{18C732B8-708D-432D-AF65-A0A5D836A4C2}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_9')]
  JTokeniserState_9 = interface(JObject)
    ['{EF3CC3AA-B1F7-40DE-9CF5-2558BC327CFC}']
  end;

  TJTokeniserState_9 = class(TJavaGenericImport<JTokeniserState_9Class, JTokeniserState_9>)
  end;

implementation

end.
