//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_2;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_2 = interface;

  JTokeniserState_2Class = interface(JObjectClass)
    ['{02F6178A-0D2B-4CE5-A13F-F0B96EDF6D25}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_2')]
  JTokeniserState_2 = interface(JObject)
    ['{E3EF4AB7-EF48-4E6A-9BD6-5D816665D395}']
  end;

  TJTokeniserState_2 = class(TJavaGenericImport<JTokeniserState_2Class, JTokeniserState_2>)
  end;

implementation

end.
