//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_25;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_25 = interface;

  JTokeniserState_25Class = interface(JObjectClass)
    ['{D6D06A53-FF4B-45A1-B907-3729995DDA34}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_25')]
  JTokeniserState_25 = interface(JObject)
    ['{421BDE4A-31A3-47F6-9864-C37759AA33E7}']
  end;

  TJTokeniserState_25 = class(TJavaGenericImport<JTokeniserState_25Class, JTokeniserState_25>)
  end;

implementation

end.
