//
// Generated by JavaToPas v1.5 20160713 - 141447
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Document;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Document_OutputSettings,
  org.jsoup.nodes.Document_QuirksMode,
  org.jsoup.nodes.Element,
  java.nio.charset.Charset,
  org.jsoup.nodes.Attributes,
  org.jsoup.select.NodeVisitor,
  java.lang.Appendable;

type
  JNode = interface; // merged
  JDocument = interface;

  JDocumentClass = interface(JObjectClass)
    ['{BA757945-364A-4BBC-AAAB-5C90440723E2}']
    function body : JElement; cdecl;                                            // ()Lorg/jsoup/nodes/Element; A: $1
    function charset : JCharset; cdecl; overload;                               // ()Ljava/nio/charset/Charset; A: $1
    function clone : JDocument; cdecl;                                          // ()Lorg/jsoup/nodes/Document; A: $1
    function createElement(tagName : JString) : JElement; cdecl;                // (Ljava/lang/String;)Lorg/jsoup/nodes/Element; A: $1
    function createShell(baseUri : JString) : JDocument; cdecl;                 // (Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function head : JElement; cdecl;                                            // ()Lorg/jsoup/nodes/Element; A: $1
    function init(baseUri : JString) : JDocument; cdecl;                        // (Ljava/lang/String;)V A: $1
    function location : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function nodeName : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function normalise : JDocument; cdecl;                                      // ()Lorg/jsoup/nodes/Document; A: $1
    function outerHtml : JString; cdecl;                                        // ()Ljava/lang/String; A: $1
    function outputSettings : JDocument_OutputSettings; cdecl; overload;        // ()Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function outputSettings(outputSettings : JDocument_OutputSettings) : JDocument; cdecl; overload;// (Lorg/jsoup/nodes/Document$OutputSettings;)Lorg/jsoup/nodes/Document; A: $1
    function quirksMode : JDocument_QuirksMode; cdecl; overload;                // ()Lorg/jsoup/nodes/Document$QuirksMode; A: $1
    function quirksMode(quirksMode : JDocument_QuirksMode) : JDocument; cdecl; overload;// (Lorg/jsoup/nodes/Document$QuirksMode;)Lorg/jsoup/nodes/Document; A: $1
    function text(text : JString) : JElement; cdecl;                            // (Ljava/lang/String;)Lorg/jsoup/nodes/Element; A: $1
    function title : JString; cdecl; overload;                                  // ()Ljava/lang/String; A: $1
    function updateMetaCharsetElement : boolean; cdecl; overload;               // ()Z A: $1
    procedure charset(charset : JCharset) ; cdecl; overload;                    // (Ljava/nio/charset/Charset;)V A: $1
    procedure title(title : JString) ; cdecl; overload;                         // (Ljava/lang/String;)V A: $1
    procedure updateMetaCharsetElement(update : boolean) ; cdecl; overload;     // (Z)V A: $1
  end;

  [JavaSignature('org/jsoup/nodes/Document$QuirksMode')]
  JDocument = interface(JObject)
    ['{278621C0-5980-42CD-980F-C094AEAC6C41}']
    function body : JElement; cdecl;                                            // ()Lorg/jsoup/nodes/Element; A: $1
    function charset : JCharset; cdecl; overload;                               // ()Ljava/nio/charset/Charset; A: $1
    function clone : JDocument; cdecl;                                          // ()Lorg/jsoup/nodes/Document; A: $1
    function createElement(tagName : JString) : JElement; cdecl;                // (Ljava/lang/String;)Lorg/jsoup/nodes/Element; A: $1
    function head : JElement; cdecl;                                            // ()Lorg/jsoup/nodes/Element; A: $1
    function location : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function nodeName : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function normalise : JDocument; cdecl;                                      // ()Lorg/jsoup/nodes/Document; A: $1
    function outerHtml : JString; cdecl;                                        // ()Ljava/lang/String; A: $1
    function outputSettings : JDocument_OutputSettings; cdecl; overload;        // ()Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function outputSettings(outputSettings : JDocument_OutputSettings) : JDocument; cdecl; overload;// (Lorg/jsoup/nodes/Document$OutputSettings;)Lorg/jsoup/nodes/Document; A: $1
    function quirksMode : JDocument_QuirksMode; cdecl; overload;                // ()Lorg/jsoup/nodes/Document$QuirksMode; A: $1
    function quirksMode(quirksMode : JDocument_QuirksMode) : JDocument; cdecl; overload;// (Lorg/jsoup/nodes/Document$QuirksMode;)Lorg/jsoup/nodes/Document; A: $1
    function text(text : JString) : JElement; cdecl;                            // (Ljava/lang/String;)Lorg/jsoup/nodes/Element; A: $1
    function title : JString; cdecl; overload;                                  // ()Ljava/lang/String; A: $1
    function updateMetaCharsetElement : boolean; cdecl; overload;               // ()Z A: $1
    procedure charset(charset : JCharset) ; cdecl; overload;                    // (Ljava/nio/charset/Charset;)V A: $1
    procedure title(title : JString) ; cdecl; overload;                         // (Ljava/lang/String;)V A: $1
    procedure updateMetaCharsetElement(update : boolean) ; cdecl; overload;     // (Z)V A: $1
  end;

  TJDocument = class(TJavaGenericImport<JDocumentClass, JDocument>)
  end;

  // Merged from: .\org.jsoup.nodes.Node.pas
  JNodeClass = interface(JObjectClass)
    ['{455FCE2A-FA4F-4053-AFD6-C5BF8F0B088F}']
    function absUrl(attributeKey : JString) : JString; cdecl;                   // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function after(html : JString) : JNode; cdecl; overload;                    // (Ljava/lang/String;)Lorg/jsoup/nodes/Node; A: $1
    function after(node : JNode) : JNode; cdecl; overload;                      // (Lorg/jsoup/nodes/Node;)Lorg/jsoup/nodes/Node; A: $1
    function attr(attributeKey : JString) : JString; cdecl; overload;           // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function attr(attributeKey : JString; attributeValue : JString) : JNode; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Node; A: $1
    function attributes : JAttributes; cdecl;                                   // ()Lorg/jsoup/nodes/Attributes; A: $1
    function baseUri : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function before(html : JString) : JNode; cdecl; overload;                   // (Ljava/lang/String;)Lorg/jsoup/nodes/Node; A: $1
    function before(node : JNode) : JNode; cdecl; overload;                     // (Lorg/jsoup/nodes/Node;)Lorg/jsoup/nodes/Node; A: $1
    function childNode(&index : Integer) : JNode; cdecl;                        // (I)Lorg/jsoup/nodes/Node; A: $1
    function childNodeSize : Integer; cdecl;                                    // ()I A: $11
    function childNodes : JList; cdecl;                                         // ()Ljava/util/List; A: $1
    function childNodesCopy : JList; cdecl;                                     // ()Ljava/util/List; A: $1
    function clone : JNode; cdecl;                                              // ()Lorg/jsoup/nodes/Node; A: $1
    function equals(o : JObject) : boolean; cdecl;                              // (Ljava/lang/Object;)Z A: $1
    function hasAttr(attributeKey : JString) : boolean; cdecl;                  // (Ljava/lang/String;)Z A: $1
    function hasSameValue(o : JObject) : boolean; cdecl;                        // (Ljava/lang/Object;)Z A: $1
    function html(appendable : JAppendable) : JAppendable; cdecl;               // (Ljava/lang/Appendable;)Ljava/lang/Appendable; A: $1
    function nextSibling : JNode; cdecl;                                        // ()Lorg/jsoup/nodes/Node; A: $1
    function nodeName : JString; cdecl;                                         // ()Ljava/lang/String; A: $401
    function outerHtml : JString; cdecl; overload;                              // ()Ljava/lang/String; A: $1
    function ownerDocument : JDocument; cdecl;                                  // ()Lorg/jsoup/nodes/Document; A: $1
    function parent : JNode; cdecl;                                             // ()Lorg/jsoup/nodes/Node; A: $1
    function parentNode : JNode; cdecl;                                         // ()Lorg/jsoup/nodes/Node; A: $11
    function previousSibling : JNode; cdecl;                                    // ()Lorg/jsoup/nodes/Node; A: $1
    function removeAttr(attributeKey : JString) : JNode; cdecl;                 // (Ljava/lang/String;)Lorg/jsoup/nodes/Node; A: $1
    function siblingIndex : Integer; cdecl;                                     // ()I A: $1
    function siblingNodes : JList; cdecl;                                       // ()Ljava/util/List; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function traverse(nodeVisitor : JNodeVisitor) : JNode; cdecl;               // (Lorg/jsoup/select/NodeVisitor;)Lorg/jsoup/nodes/Node; A: $1
    function unwrap : JNode; cdecl;                                             // ()Lorg/jsoup/nodes/Node; A: $1
    function wrap(html : JString) : JNode; cdecl;                               // (Ljava/lang/String;)Lorg/jsoup/nodes/Node; A: $1
    procedure remove ; cdecl;                                                   // ()V A: $1
    procedure replaceWith(&in : JNode) ; cdecl;                                 // (Lorg/jsoup/nodes/Node;)V A: $1
    procedure setBaseUri(baseUri : JString) ; cdecl;                            // (Ljava/lang/String;)V A: $1
  end;

  [JavaSignature('org/jsoup/nodes/Node$OuterHtmlVisitor')]
  JNode = interface(JObject)
    ['{84A3FE91-CA2D-42F3-AE79-9E674BEC2886}']
    function absUrl(attributeKey : JString) : JString; cdecl;                   // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function after(html : JString) : JNode; cdecl; overload;                    // (Ljava/lang/String;)Lorg/jsoup/nodes/Node; A: $1
    function after(node : JNode) : JNode; cdecl; overload;                      // (Lorg/jsoup/nodes/Node;)Lorg/jsoup/nodes/Node; A: $1
    function attr(attributeKey : JString) : JString; cdecl; overload;           // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function attr(attributeKey : JString; attributeValue : JString) : JNode; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Node; A: $1
    function attributes : JAttributes; cdecl;                                   // ()Lorg/jsoup/nodes/Attributes; A: $1
    function baseUri : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function before(html : JString) : JNode; cdecl; overload;                   // (Ljava/lang/String;)Lorg/jsoup/nodes/Node; A: $1
    function before(node : JNode) : JNode; cdecl; overload;                     // (Lorg/jsoup/nodes/Node;)Lorg/jsoup/nodes/Node; A: $1
    function childNode(&index : Integer) : JNode; cdecl;                        // (I)Lorg/jsoup/nodes/Node; A: $1
    function childNodes : JList; cdecl;                                         // ()Ljava/util/List; A: $1
    function childNodesCopy : JList; cdecl;                                     // ()Ljava/util/List; A: $1
    function clone : JNode; cdecl;                                              // ()Lorg/jsoup/nodes/Node; A: $1
    function equals(o : JObject) : boolean; cdecl;                              // (Ljava/lang/Object;)Z A: $1
    function hasAttr(attributeKey : JString) : boolean; cdecl;                  // (Ljava/lang/String;)Z A: $1
    function hasSameValue(o : JObject) : boolean; cdecl;                        // (Ljava/lang/Object;)Z A: $1
    function html(appendable : JAppendable) : JAppendable; cdecl;               // (Ljava/lang/Appendable;)Ljava/lang/Appendable; A: $1
    function nextSibling : JNode; cdecl;                                        // ()Lorg/jsoup/nodes/Node; A: $1
    function nodeName : JString; cdecl;                                         // ()Ljava/lang/String; A: $401
    function outerHtml : JString; cdecl; overload;                              // ()Ljava/lang/String; A: $1
    function ownerDocument : JDocument; cdecl;                                  // ()Lorg/jsoup/nodes/Document; A: $1
    function parent : JNode; cdecl;                                             // ()Lorg/jsoup/nodes/Node; A: $1
    function previousSibling : JNode; cdecl;                                    // ()Lorg/jsoup/nodes/Node; A: $1
    function removeAttr(attributeKey : JString) : JNode; cdecl;                 // (Ljava/lang/String;)Lorg/jsoup/nodes/Node; A: $1
    function siblingIndex : Integer; cdecl;                                     // ()I A: $1
    function siblingNodes : JList; cdecl;                                       // ()Ljava/util/List; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function traverse(nodeVisitor : JNodeVisitor) : JNode; cdecl;               // (Lorg/jsoup/select/NodeVisitor;)Lorg/jsoup/nodes/Node; A: $1
    function unwrap : JNode; cdecl;                                             // ()Lorg/jsoup/nodes/Node; A: $1
    function wrap(html : JString) : JNode; cdecl;                               // (Ljava/lang/String;)Lorg/jsoup/nodes/Node; A: $1
    procedure remove ; cdecl;                                                   // ()V A: $1
    procedure replaceWith(&in : JNode) ; cdecl;                                 // (Lorg/jsoup/nodes/Node;)V A: $1
    procedure setBaseUri(baseUri : JString) ; cdecl;                            // (Ljava/lang/String;)V A: $1
  end;

  TJNode = class(TJavaGenericImport<JNodeClass, JNode>)
  end;


implementation

end.
