//
// Generated by JavaToPas v1.5 20160713 - 141454
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_19;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_19 = interface;

  JHtmlTreeBuilderState_19Class = interface(JObjectClass)
    ['{4F0B9C4C-4221-4048-B639-48C4412944B2}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_19')]
  JHtmlTreeBuilderState_19 = interface(JObject)
    ['{670B0CDC-30BE-4EBC-A34E-1BA7951A5990}']
  end;

  TJHtmlTreeBuilderState_19 = class(TJavaGenericImport<JHtmlTreeBuilderState_19Class, JHtmlTreeBuilderState_19>)
  end;

implementation

end.
