//
// Generated by JavaToPas v1.5 20160713 - 141453
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_11;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_11 = interface;

  JHtmlTreeBuilderState_11Class = interface(JObjectClass)
    ['{3546EC70-5519-496E-B6CC-6FFEE16C9C67}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_11')]
  JHtmlTreeBuilderState_11 = interface(JObject)
    ['{3E8967CE-BC86-409A-A1FF-524780627ED4}']
  end;

  TJHtmlTreeBuilderState_11 = class(TJavaGenericImport<JHtmlTreeBuilderState_11Class, JHtmlTreeBuilderState_11>)
  end;

implementation

end.
