//
// Generated by JavaToPas v1.5 20160713 - 141444
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.helper.StringUtil;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.net.URL;

type
  JStringUtil = interface;

  JStringUtilClass = interface(JObjectClass)
    ['{7DEB3D41-5B41-445C-A6A6-1A4B05A731C6}']
    function &in(needle : JString; haystack : TJavaArray<JString>) : boolean; cdecl;// (Ljava/lang/String;[Ljava/lang/String;)Z A: $89
    function inSorted(needle : JString; haystack : TJavaArray<JString>) : boolean; cdecl;// (Ljava/lang/String;[Ljava/lang/String;)Z A: $9
    function init : JStringUtil; cdecl;                                         // ()V A: $1
    function isBlank(&string : JString) : boolean; cdecl;                       // (Ljava/lang/String;)Z A: $9
    function isNumeric(&string : JString) : boolean; cdecl;                     // (Ljava/lang/String;)Z A: $9
    function isWhitespace(c : Integer) : boolean; cdecl;                        // (I)Z A: $9
    function join(strings : JCollection; sep : JString) : JString; cdecl; overload;// (Ljava/util/Collection;Ljava/lang/String;)Ljava/lang/String; A: $9
    function join(strings : JIterator; sep : JString) : JString; cdecl; overload;// (Ljava/util/Iterator;Ljava/lang/String;)Ljava/lang/String; A: $9
    function normaliseWhitespace(&string : JString) : JString; cdecl;           // (Ljava/lang/String;)Ljava/lang/String; A: $9
    function padding(width : Integer) : JString; cdecl;                         // (I)Ljava/lang/String; A: $9
    function resolve(base : JURL; relUrl : JString) : JURL; cdecl; overload;    // (Ljava/net/URL;Ljava/lang/String;)Ljava/net/URL; A: $9
    function resolve(baseUrl : JString; relUrl : JString) : JString; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String; A: $9
    procedure appendNormalisedWhitespace(accum : JStringBuilder; &string : JString; stripLeading : boolean) ; cdecl;// (Ljava/lang/StringBuilder;Ljava/lang/String;Z)V A: $9
  end;

  [JavaSignature('org/jsoup/helper/StringUtil')]
  JStringUtil = interface(JObject)
    ['{76889800-58C1-4D32-B15C-F30DCEBEE689}']
  end;

  TJStringUtil = class(TJavaGenericImport<JStringUtilClass, JStringUtil>)
  end;

implementation

end.
