//
// Generated by JavaToPas v1.5 20160713 - 141512
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.UnsupportedMimeTypeException;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JUnsupportedMimeTypeException = interface;

  JUnsupportedMimeTypeExceptionClass = interface(JObjectClass)
    ['{D219673D-AB2F-4253-9EA6-963A7B1478A3}']
    function getMimeType : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function getUrl : JString; cdecl;                                           // ()Ljava/lang/String; A: $1
    function init(&message : JString; mimeType : JString; url : JString) : JUnsupportedMimeTypeException; cdecl;// (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/UnsupportedMimeTypeException')]
  JUnsupportedMimeTypeException = interface(JObject)
    ['{27EBF3E7-9258-4655-AF9A-4E8A663E0693}']
    function getMimeType : JString; cdecl;                                      // ()Ljava/lang/String; A: $1
    function getUrl : JString; cdecl;                                           // ()Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJUnsupportedMimeTypeException = class(TJavaGenericImport<JUnsupportedMimeTypeExceptionClass, JUnsupportedMimeTypeException>)
  end;

implementation

end.
