//
// Generated by JavaToPas v1.5 20160713 - 141508
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_AttributeWithValueEnding;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_AttributeWithValueEnding = interface;

  JEvaluator_AttributeWithValueEndingClass = interface(JObjectClass)
    ['{1B8EBDF9-E287-428A-84A2-224AE94CD0A4}']
    function init(key : JString; value : JString) : JEvaluator_AttributeWithValueEnding; cdecl;// (Ljava/lang/String;Ljava/lang/String;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_AttributeWithValueEnding')]
  JEvaluator_AttributeWithValueEnding = interface(JObject)
    ['{789FBF45-C617-4B7A-B058-074FC14D5936}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_AttributeWithValueEnding = class(TJavaGenericImport<JEvaluator_AttributeWithValueEndingClass, JEvaluator_AttributeWithValueEnding>)
  end;

implementation

end.
