//
// Generated by JavaToPas v1.5 20160713 - 141454
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_18;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_18 = interface;

  JHtmlTreeBuilderState_18Class = interface(JObjectClass)
    ['{ED4DFE76-9AB2-46C7-9D25-2D63B9560BED}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_18')]
  JHtmlTreeBuilderState_18 = interface(JObject)
    ['{095C9202-B809-45F8-9184-31867BAC4C83}']
  end;

  TJHtmlTreeBuilderState_18 = class(TJavaGenericImport<JHtmlTreeBuilderState_18Class, JHtmlTreeBuilderState_18>)
  end;

implementation

end.
