//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_11;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_11 = interface;

  JTokeniserState_11Class = interface(JObjectClass)
    ['{72A7219F-657B-4543-BFED-DFE126F0E870}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_11')]
  JTokeniserState_11 = interface(JObject)
    ['{3F10745E-319C-4540-8A8E-2E3354832DE1}']
  end;

  TJTokeniserState_11 = class(TJavaGenericImport<JTokeniserState_11Class, JTokeniserState_11>)
  end;

implementation

end.
