//
// Generated by JavaToPas v1.5 20160713 - 141509
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_IsLastOfType;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JEvaluator_IsLastOfType = interface;

  JEvaluator_IsLastOfTypeClass = interface(JObjectClass)
    ['{812345CB-663F-46A5-A754-5FC7AA858A3A}']
    function init : JEvaluator_IsLastOfType; cdecl;                             // ()V A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_IsLastOfType')]
  JEvaluator_IsLastOfType = interface(JObject)
    ['{A593317B-343B-459C-BD32-259B29E5C6B8}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_IsLastOfType = class(TJavaGenericImport<JEvaluator_IsLastOfTypeClass, JEvaluator_IsLastOfType>)
  end;

implementation

end.
