//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_5;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_5 = interface;

  JTokeniserState_5Class = interface(JObjectClass)
    ['{17F256DE-74FE-4C09-908A-3C0B3621D0C4}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_5')]
  JTokeniserState_5 = interface(JObject)
    ['{5A171635-54F0-4354-A307-77518960096C}']
  end;

  TJTokeniserState_5 = class(TJavaGenericImport<JTokeniserState_5Class, JTokeniserState_5>)
  end;

implementation

end.
