//
// Generated by JavaToPas v1.5 20160713 - 141511
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.StructuralEvaluator_Parent;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.select.Evaluator,
  org.jsoup.nodes.Element;

type
  JStructuralEvaluator_Parent = interface;

  JStructuralEvaluator_ParentClass = interface(JObjectClass)
    ['{A607B27C-3174-42FB-8A94-2972EDE0272E}']
    function init(evaluator : JEvaluator) : JStructuralEvaluator_Parent; cdecl; // (Lorg/jsoup/select/Evaluator;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/StructuralEvaluator_Parent')]
  JStructuralEvaluator_Parent = interface(JObject)
    ['{8ED26A92-1232-4DF6-979C-EE0A6514C07C}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJStructuralEvaluator_Parent = class(TJavaGenericImport<JStructuralEvaluator_ParentClass, JStructuralEvaluator_Parent>)
  end;

implementation

end.
