//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_46;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_46 = interface;

  JTokeniserState_46Class = interface(JObjectClass)
    ['{BBA5D302-D67C-4A66-8701-E8F76C3A76F4}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_46')]
  JTokeniserState_46 = interface(JObject)
    ['{1972A337-EBCB-45AA-A9D4-4189B467831E}']
  end;

  TJTokeniserState_46 = class(TJavaGenericImport<JTokeniserState_46Class, JTokeniserState_46>)
  end;

implementation

end.
