//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_3;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_3 = interface;

  JTokeniserState_3Class = interface(JObjectClass)
    ['{06057ED4-131F-4AEB-B707-F86F3D1B5B88}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_3')]
  JTokeniserState_3 = interface(JObject)
    ['{D84CB02C-CFB6-4A47-90F3-B3E4916C153E}']
  end;

  TJTokeniserState_3 = class(TJavaGenericImport<JTokeniserState_3Class, JTokeniserState_3>)
  end;

implementation

end.
