//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_16;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_16 = interface;

  JTokeniserState_16Class = interface(JObjectClass)
    ['{2F843FE2-C282-45AE-AEA0-477252CB6ECF}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_16')]
  JTokeniserState_16 = interface(JObject)
    ['{1654C3FF-2F02-45BB-BE50-2BC9D7B9FDC5}']
  end;

  TJTokeniserState_16 = class(TJavaGenericImport<JTokeniserState_16Class, JTokeniserState_16>)
  end;

implementation

end.
