//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_37;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_37 = interface;

  JTokeniserState_37Class = interface(JObjectClass)
    ['{27961E87-216E-4C65-9A73-43364142C3CF}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_37')]
  JTokeniserState_37 = interface(JObject)
    ['{FBA3CD79-312E-49C2-A4B9-13E569EFFB46}']
  end;

  TJTokeniserState_37 = class(TJavaGenericImport<JTokeniserState_37Class, JTokeniserState_37>)
  end;

implementation

end.
