//
// Generated by JavaToPas v1.5 20160713 - 141506
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.safety.Cleaner_CleaningVisitor;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element,
  org.jsoup.nodes.Document;

type
  JCleaner_CleaningVisitor = interface;

  JCleaner_CleaningVisitorClass = interface(JObjectClass)
    ['{A9A8BB6C-9C95-4F4D-A5A4-22ED50B53001}']
    procedure head(source : JNode; depth : Integer) ; cdecl;                    // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(source : JNode; depth : Integer) ; cdecl;                    // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  [JavaSignature('org/jsoup/safety/Cleaner_CleaningVisitor')]
  JCleaner_CleaningVisitor = interface(JObject)
    ['{277CC57F-3C1E-4240-9CEE-96AC99881EDB}']
    procedure head(source : JNode; depth : Integer) ; cdecl;                    // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(source : JNode; depth : Integer) ; cdecl;                    // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  TJCleaner_CleaningVisitor = class(TJavaGenericImport<JCleaner_CleaningVisitorClass, JCleaner_CleaningVisitor>)
  end;

implementation

end.
