//
// Generated by JavaToPas v1.5 20160713 - 141445
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Attributes_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JAttributes_1 = interface;

  JAttributes_1Class = interface(JObjectClass)
    ['{A0ED9E79-1E9B-499E-93A8-B68D9D464F6B}']
  end;

  [JavaSignature('org/jsoup/nodes/Attributes_1')]
  JAttributes_1 = interface(JObject)
    ['{BAE4009D-50F1-43DA-A508-C37942DAA75E}']
  end;

  TJAttributes_1 = class(TJavaGenericImport<JAttributes_1Class, JAttributes_1>)
  end;

implementation

end.
