//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_38;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_38 = interface;

  JTokeniserState_38Class = interface(JObjectClass)
    ['{789F6013-57A5-42CB-B8C9-C687455D08E9}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_38')]
  JTokeniserState_38 = interface(JObject)
    ['{0BBFDC4D-8AB1-47A3-8353-C47276FAC2ED}']
  end;

  TJTokeniserState_38 = class(TJavaGenericImport<JTokeniserState_38Class, JTokeniserState_38>)
  end;

implementation

end.
