//
// Generated by JavaToPas v1.5 20160713 - 141455
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_3;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_3 = interface;

  JHtmlTreeBuilderState_3Class = interface(JObjectClass)
    ['{30BF7237-90B9-4D15-9138-9324742C9816}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_3')]
  JHtmlTreeBuilderState_3 = interface(JObject)
    ['{F81344DF-F8C2-4BA7-9C73-5B0AAF8A01BC}']
  end;

  TJHtmlTreeBuilderState_3 = class(TJavaGenericImport<JHtmlTreeBuilderState_3Class, JHtmlTreeBuilderState_3>)
  end;

implementation

end.
