//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_52;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_52 = interface;

  JTokeniserState_52Class = interface(JObjectClass)
    ['{D82DC32B-4A27-4DE3-BA5C-9EB93D33DDD1}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_52')]
  JTokeniserState_52 = interface(JObject)
    ['{853E33DC-0F30-4D17-958F-F47062CE8DA7}']
  end;

  TJTokeniserState_52 = class(TJavaGenericImport<JTokeniserState_52Class, JTokeniserState_52>)
  end;

implementation

end.
