//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_63;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_63 = interface;

  JTokeniserState_63Class = interface(JObjectClass)
    ['{6A4D78BE-C23E-47CC-9E5A-AA51F588AA59}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_63')]
  JTokeniserState_63 = interface(JObject)
    ['{F4FE2ECB-77FB-4CBC-A55A-58AB1268AAA2}']
  end;

  TJTokeniserState_63 = class(TJavaGenericImport<JTokeniserState_63Class, JTokeniserState_63>)
  end;

implementation

end.
