//
// Generated by JavaToPas v1.5 20160713 - 141509
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_IsEmpty;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_IsEmpty = interface;

  JEvaluator_IsEmptyClass = interface(JObjectClass)
    ['{3FEAD3F9-3692-4415-A0FD-17BEF9B077AB}']
    function init : JEvaluator_IsEmpty; cdecl;                                  // ()V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_IsEmpty')]
  JEvaluator_IsEmpty = interface(JObject)
    ['{85F67395-DE0F-4BA4-8273-5013636A77F1}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_IsEmpty = class(TJavaGenericImport<JEvaluator_IsEmptyClass, JEvaluator_IsEmpty>)
  end;

implementation

end.
