//
// Generated by JavaToPas v1.5 20160713 - 141450
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Node_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Document;

type
  JNode_1 = interface;

  JNode_1Class = interface(JObjectClass)
    ['{44CCC7AC-F015-4DAF-98A8-F8803BB56105}']
    procedure head(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  [JavaSignature('org/jsoup/nodes/Node_1')]
  JNode_1 = interface(JObject)
    ['{3C56ED0E-58BA-43A5-BD36-CABF071935C1}']
    procedure head(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  TJNode_1 = class(TJavaGenericImport<JNode_1Class, JNode_1>)
  end;

implementation

end.
