//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_36;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_36 = interface;

  JTokeniserState_36Class = interface(JObjectClass)
    ['{F6A258BE-DEE0-4D67-9515-E02F0083621D}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_36')]
  JTokeniserState_36 = interface(JObject)
    ['{03FD29D9-3969-412E-938F-243B1867D46F}']
  end;

  TJTokeniserState_36 = class(TJavaGenericImport<JTokeniserState_36Class, JTokeniserState_36>)
  end;

implementation

end.
