//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_33;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_33 = interface;

  JTokeniserState_33Class = interface(JObjectClass)
    ['{CE7EF2AD-B797-4E85-A22F-F2DA21B103BD}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_33')]
  JTokeniserState_33 = interface(JObject)
    ['{9FDE17A7-5DA3-4986-8C6D-E3EFB847EDBA}']
  end;

  TJTokeniserState_33 = class(TJavaGenericImport<JTokeniserState_33Class, JTokeniserState_33>)
  end;

implementation

end.
