//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_10;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_10 = interface;

  JTokeniserState_10Class = interface(JObjectClass)
    ['{341BEA6F-7457-4AFA-B6EB-50E21B513BCA}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_10')]
  JTokeniserState_10 = interface(JObject)
    ['{2AFF5D1C-C204-4E25-9299-5E98318B1800}']
  end;

  TJTokeniserState_10 = class(TJavaGenericImport<JTokeniserState_10Class, JTokeniserState_10>)
  end;

implementation

end.
