//
// Generated by JavaToPas v1.5 20160713 - 141511
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.StructuralEvaluator_ImmediatePreviousSibling;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.select.Evaluator,
  org.jsoup.nodes.Element;

type
  JStructuralEvaluator_ImmediatePreviousSibling = interface;

  JStructuralEvaluator_ImmediatePreviousSiblingClass = interface(JObjectClass)
    ['{8A5DFC6E-237C-437E-B20F-A98D319565B0}']
    function init(evaluator : JEvaluator) : JStructuralEvaluator_ImmediatePreviousSibling; cdecl;// (Lorg/jsoup/select/Evaluator;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/StructuralEvaluator_ImmediatePreviousSibling')]
  JStructuralEvaluator_ImmediatePreviousSibling = interface(JObject)
    ['{34A14880-E16B-4995-A84B-E2768FB6DCDF}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJStructuralEvaluator_ImmediatePreviousSibling = class(TJavaGenericImport<JStructuralEvaluator_ImmediatePreviousSiblingClass, JStructuralEvaluator_ImmediatePreviousSibling>)
  end;

implementation

end.
