//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_60;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_60 = interface;

  JTokeniserState_60Class = interface(JObjectClass)
    ['{37ECFD2C-B2F6-473C-9623-A5251E9B5E86}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_60')]
  JTokeniserState_60 = interface(JObject)
    ['{00A2DA1C-596C-4786-8883-F5E3238C7E83}']
  end;

  TJTokeniserState_60 = class(TJavaGenericImport<JTokeniserState_60Class, JTokeniserState_60>)
  end;

implementation

end.
