//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_28;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_28 = interface;

  JTokeniserState_28Class = interface(JObjectClass)
    ['{4BF91CB4-F466-4B1F-BDDB-A84D25100E4F}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_28')]
  JTokeniserState_28 = interface(JObject)
    ['{B4CB27B0-3C20-4D48-9F00-D67161A74E2D}']
  end;

  TJTokeniserState_28 = class(TJavaGenericImport<JTokeniserState_28Class, JTokeniserState_28>)
  end;

implementation

end.
