//
// Generated by JavaToPas v1.5 20160713 - 141506
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.safety.Whitelist_AttributeValue;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JWhitelist_AttributeValue = interface;

  JWhitelist_AttributeValueClass = interface(JObjectClass)
    ['{47C43C38-F1AB-44DE-8B76-D76EF16F67C7}']
  end;

  [JavaSignature('org/jsoup/safety/Whitelist_AttributeValue')]
  JWhitelist_AttributeValue = interface(JObject)
    ['{D5C3E6E3-07A3-404B-B3AF-36995B61F6F0}']
  end;

  TJWhitelist_AttributeValue = class(TJavaGenericImport<JWhitelist_AttributeValueClass, JWhitelist_AttributeValue>)
  end;

implementation

end.
