//
// Generated by JavaToPas v1.5 20160713 - 141507
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Collector_Accumulator;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element,
  org.jsoup.select.Evaluator,
  org.jsoup.nodes.Document;

type
  JCollector_Accumulator = interface;

  JCollector_AccumulatorClass = interface(JObjectClass)
    ['{9B9D86C5-0559-42C8-BECA-E031541154DD}']
    procedure head(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  [JavaSignature('org/jsoup/select/Collector_Accumulator')]
  JCollector_Accumulator = interface(JObject)
    ['{9EA308FB-A31B-46B1-80C4-C6930AB22D16}']
    procedure head(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  TJCollector_Accumulator = class(TJavaGenericImport<JCollector_AccumulatorClass, JCollector_Accumulator>)
  end;

implementation

end.
