//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_20;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_20 = interface;

  JTokeniserState_20Class = interface(JObjectClass)
    ['{9AF550E1-E4B8-47EB-8BAE-164AB7E31AC2}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_20')]
  JTokeniserState_20 = interface(JObject)
    ['{54078DCD-8C33-486E-8343-21DC39F2D8E0}']
  end;

  TJTokeniserState_20 = class(TJavaGenericImport<JTokeniserState_20Class, JTokeniserState_20>)
  end;

implementation

end.
