//
// Generated by JavaToPas v1.5 20160713 - 141457
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.ParseError;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JParseError = interface;

  JParseErrorClass = interface(JObjectClass)
    ['{96A4BA2B-19ED-431D-9D43-C2ED40373ADE}']
    function getErrorMessage : JString; cdecl;                                  // ()Ljava/lang/String; A: $1
    function getPosition : Integer; cdecl;                                      // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/parser/ParseError')]
  JParseError = interface(JObject)
    ['{05EC6C2E-4410-4D31-B2C4-B8DE95F04C4B}']
    function getErrorMessage : JString; cdecl;                                  // ()Ljava/lang/String; A: $1
    function getPosition : Integer; cdecl;                                      // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJParseError = class(TJavaGenericImport<JParseErrorClass, JParseError>)
  end;

implementation

end.
