//
// Generated by JavaToPas v1.5 20160713 - 141511
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.StructuralEvaluator_Has;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.select.Evaluator,
  org.jsoup.nodes.Element;

type
  JStructuralEvaluator_Has = interface;

  JStructuralEvaluator_HasClass = interface(JObjectClass)
    ['{3A65329E-3A2A-47D7-8F70-5EC02B04497D}']
    function init(evaluator : JEvaluator) : JStructuralEvaluator_Has; cdecl;    // (Lorg/jsoup/select/Evaluator;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/StructuralEvaluator_Has')]
  JStructuralEvaluator_Has = interface(JObject)
    ['{792624A6-0887-434B-9057-EC32093A87B8}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJStructuralEvaluator_Has = class(TJavaGenericImport<JStructuralEvaluator_HasClass, JStructuralEvaluator_Has>)
  end;

implementation

end.
