//
// Generated by JavaToPas v1.5 20160713 - 141508
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_AttributeWithValueContaining;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_AttributeWithValueContaining = interface;

  JEvaluator_AttributeWithValueContainingClass = interface(JObjectClass)
    ['{12E647EA-E37D-4A21-AF32-1FE34CCF9077}']
    function init(key : JString; value : JString) : JEvaluator_AttributeWithValueContaining; cdecl;// (Ljava/lang/String;Ljava/lang/String;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_AttributeWithValueContaining')]
  JEvaluator_AttributeWithValueContaining = interface(JObject)
    ['{BB34D1A9-B566-45EA-B777-1CD8834D44CE}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_AttributeWithValueContaining = class(TJavaGenericImport<JEvaluator_AttributeWithValueContainingClass, JEvaluator_AttributeWithValueContaining>)
  end;

implementation

end.
