//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_35;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_35 = interface;

  JTokeniserState_35Class = interface(JObjectClass)
    ['{BD08161C-55E8-4DA7-B0E7-F99376B514E3}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_35')]
  JTokeniserState_35 = interface(JObject)
    ['{A4A8CB5A-2FC9-44EE-892F-48468BE666D2}']
  end;

  TJTokeniserState_35 = class(TJavaGenericImport<JTokeniserState_35Class, JTokeniserState_35>)
  end;

implementation

end.
