//
// Generated by JavaToPas v1.5 20160713 - 141509
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_IsNthOfType;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_IsNthOfType = interface;

  JEvaluator_IsNthOfTypeClass = interface(JObjectClass)
    ['{AEDB153C-841B-451F-9910-D82E528CAF4C}']
    function init(a : Integer; b : Integer) : JEvaluator_IsNthOfType; cdecl;    // (II)V A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_IsNthOfType')]
  JEvaluator_IsNthOfType = interface(JObject)
    ['{0EFD4261-A161-4168-9A81-784FAD77BBDA}']
  end;

  TJEvaluator_IsNthOfType = class(TJavaGenericImport<JEvaluator_IsNthOfTypeClass, JEvaluator_IsNthOfType>)
  end;

implementation

end.
