//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_55;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_55 = interface;

  JTokeniserState_55Class = interface(JObjectClass)
    ['{E4D7461F-901B-4480-B641-D67B23DB8F79}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_55')]
  JTokeniserState_55 = interface(JObject)
    ['{F666AC5E-D1D5-4E82-B67D-7EE9AB4F065D}']
  end;

  TJTokeniserState_55 = class(TJavaGenericImport<JTokeniserState_55Class, JTokeniserState_55>)
  end;

implementation

end.
