//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_51;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_51 = interface;

  JTokeniserState_51Class = interface(JObjectClass)
    ['{3A070A14-BC41-4F09-8014-70EF6D1A97F9}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_51')]
  JTokeniserState_51 = interface(JObject)
    ['{20357545-8CA1-46D0-AC99-50834DE1B66A}']
  end;

  TJTokeniserState_51 = class(TJavaGenericImport<JTokeniserState_51Class, JTokeniserState_51>)
  end;

implementation

end.
