//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_15;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_15 = interface;

  JTokeniserState_15Class = interface(JObjectClass)
    ['{4C05394A-E0D8-44C6-96A1-C771FBA503C9}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_15')]
  JTokeniserState_15 = interface(JObject)
    ['{2A6FA60C-14B4-47FE-A325-41885C09ED78}']
  end;

  TJTokeniserState_15 = class(TJavaGenericImport<JTokeniserState_15Class, JTokeniserState_15>)
  end;

implementation

end.
