//
// Generated by JavaToPas v1.5 20160713 - 141442
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.helper.HttpConnection_Request;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.net.Proxy,
  org.jsoup.parser.Parser,
  org.jsoup.Connection_Request,
  org.jsoup.Connection_KeyVal;

type
  JHttpConnection_Request = interface;

  JHttpConnection_RequestClass = interface(JObjectClass)
    ['{33ACA855-0E07-4CFF-87F2-6DCBB1BFD321}']
    function data : JCollection; cdecl; overload;                               // ()Ljava/util/Collection; A: $1
    function data(keyval : JConnection_KeyVal) : JHttpConnection_Request; cdecl; overload;// (Lorg/jsoup/Connection$KeyVal;)Lorg/jsoup/helper/HttpConnection$Request; A: $1
    function followRedirects : boolean; cdecl; overload;                        // ()Z A: $1
    function followRedirects(followRedirects : boolean) : JConnection_Request; cdecl; overload;// (Z)Lorg/jsoup/Connection$Request; A: $1
    function ignoreContentType : boolean; cdecl; overload;                      // ()Z A: $1
    function ignoreContentType(ignoreContentType : boolean) : JConnection_Request; cdecl; overload;// (Z)Lorg/jsoup/Connection$Request; A: $1
    function ignoreHttpErrors : boolean; cdecl; overload;                       // ()Z A: $1
    function ignoreHttpErrors(ignoreHttpErrors : boolean) : JConnection_Request; cdecl; overload;// (Z)Lorg/jsoup/Connection$Request; A: $1
    function maxBodySize : Integer; cdecl; overload;                            // ()I A: $1
    function maxBodySize(bytes : Integer) : JConnection_Request; cdecl; overload;// (I)Lorg/jsoup/Connection$Request; A: $1
    function parser : JParser; cdecl; overload;                                 // ()Lorg/jsoup/parser/Parser; A: $1
    function parser(parser : JParser) : JHttpConnection_Request; cdecl; overload;// (Lorg/jsoup/parser/Parser;)Lorg/jsoup/helper/HttpConnection$Request; A: $1
    function postDataCharset : JString; cdecl; overload;                        // ()Ljava/lang/String; A: $1
    function postDataCharset(charset : JString) : JConnection_Request; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/Connection$Request; A: $1
    function proxy : JProxy; cdecl; overload;                                   // ()Ljava/net/Proxy; A: $1
    function proxy(host : JString; port : Integer) : JHttpConnection_Request; cdecl; overload;// (Ljava/lang/String;I)Lorg/jsoup/helper/HttpConnection$Request; A: $1
    function proxy(proxy : JProxy) : JHttpConnection_Request; cdecl; overload;  // (Ljava/net/Proxy;)Lorg/jsoup/helper/HttpConnection$Request; A: $1
    function requestBody : JString; cdecl; overload;                            // ()Ljava/lang/String; A: $1
    function requestBody(body : JString) : JConnection_Request; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/Connection$Request; A: $1
    function timeout : Integer; cdecl; overload;                                // ()I A: $1
    function timeout(millis : Integer) : JHttpConnection_Request; cdecl; overload;// (I)Lorg/jsoup/helper/HttpConnection$Request; A: $1
    function validateTLSCertificates : boolean; cdecl; overload;                // ()Z A: $1
    procedure validateTLSCertificates(value : boolean) ; cdecl; overload;       // (Z)V A: $1
  end;

  [JavaSignature('org/jsoup/helper/HttpConnection_Request')]
  JHttpConnection_Request = interface(JObject)
    ['{0B0D7E3A-F03D-48CC-A5C3-095E9A2D1C53}']
    function data : JCollection; cdecl; overload;                               // ()Ljava/util/Collection; A: $1
    function data(keyval : JConnection_KeyVal) : JHttpConnection_Request; cdecl; overload;// (Lorg/jsoup/Connection$KeyVal;)Lorg/jsoup/helper/HttpConnection$Request; A: $1
    function followRedirects : boolean; cdecl; overload;                        // ()Z A: $1
    function followRedirects(followRedirects : boolean) : JConnection_Request; cdecl; overload;// (Z)Lorg/jsoup/Connection$Request; A: $1
    function ignoreContentType : boolean; cdecl; overload;                      // ()Z A: $1
    function ignoreContentType(ignoreContentType : boolean) : JConnection_Request; cdecl; overload;// (Z)Lorg/jsoup/Connection$Request; A: $1
    function ignoreHttpErrors : boolean; cdecl; overload;                       // ()Z A: $1
    function ignoreHttpErrors(ignoreHttpErrors : boolean) : JConnection_Request; cdecl; overload;// (Z)Lorg/jsoup/Connection$Request; A: $1
    function maxBodySize : Integer; cdecl; overload;                            // ()I A: $1
    function maxBodySize(bytes : Integer) : JConnection_Request; cdecl; overload;// (I)Lorg/jsoup/Connection$Request; A: $1
    function parser : JParser; cdecl; overload;                                 // ()Lorg/jsoup/parser/Parser; A: $1
    function parser(parser : JParser) : JHttpConnection_Request; cdecl; overload;// (Lorg/jsoup/parser/Parser;)Lorg/jsoup/helper/HttpConnection$Request; A: $1
    function postDataCharset : JString; cdecl; overload;                        // ()Ljava/lang/String; A: $1
    function postDataCharset(charset : JString) : JConnection_Request; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/Connection$Request; A: $1
    function proxy : JProxy; cdecl; overload;                                   // ()Ljava/net/Proxy; A: $1
    function proxy(host : JString; port : Integer) : JHttpConnection_Request; cdecl; overload;// (Ljava/lang/String;I)Lorg/jsoup/helper/HttpConnection$Request; A: $1
    function proxy(proxy : JProxy) : JHttpConnection_Request; cdecl; overload;  // (Ljava/net/Proxy;)Lorg/jsoup/helper/HttpConnection$Request; A: $1
    function requestBody : JString; cdecl; overload;                            // ()Ljava/lang/String; A: $1
    function requestBody(body : JString) : JConnection_Request; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/Connection$Request; A: $1
    function timeout : Integer; cdecl; overload;                                // ()I A: $1
    function timeout(millis : Integer) : JHttpConnection_Request; cdecl; overload;// (I)Lorg/jsoup/helper/HttpConnection$Request; A: $1
    function validateTLSCertificates : boolean; cdecl; overload;                // ()Z A: $1
    procedure validateTLSCertificates(value : boolean) ; cdecl; overload;       // (Z)V A: $1
  end;

  TJHttpConnection_Request = class(TJavaGenericImport<JHttpConnection_RequestClass, JHttpConnection_Request>)
  end;

implementation

end.
