//
// Generated by JavaToPas v1.5 20160713 - 141457
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.Tag;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JTag = interface;

  JTagClass = interface(JObjectClass)
    ['{B95B2F3C-6109-4B4A-AC56-7D71CA0CEE6E}']
    function canContainBlock : boolean; cdecl;                                  // ()Z A: $1
    function equals(o : JObject) : boolean; cdecl;                              // (Ljava/lang/Object;)Z A: $1
    function formatAsBlock : boolean; cdecl;                                    // ()Z A: $1
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    function isBlock : boolean; cdecl;                                          // ()Z A: $1
    function isData : boolean; cdecl;                                           // ()Z A: $1
    function isEmpty : boolean; cdecl;                                          // ()Z A: $1
    function isFormListed : boolean; cdecl;                                     // ()Z A: $1
    function isFormSubmittable : boolean; cdecl;                                // ()Z A: $1
    function isInline : boolean; cdecl;                                         // ()Z A: $1
    function isKnownTag : boolean; cdecl; overload;                             // ()Z A: $1
    function isKnownTag(tagName : JString) : boolean; cdecl; overload;          // (Ljava/lang/String;)Z A: $9
    function isSelfClosing : boolean; cdecl;                                    // ()Z A: $1
    function preserveWhitespace : boolean; cdecl;                               // ()Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function valueOf(tagName : JString) : JTag; cdecl;                          // (Ljava/lang/String;)Lorg/jsoup/parser/Tag; A: $9
  end;

  [JavaSignature('org/jsoup/parser/Tag')]
  JTag = interface(JObject)
    ['{D4E4A69D-C099-42C3-93CE-D9CCC7F8A803}']
    function canContainBlock : boolean; cdecl;                                  // ()Z A: $1
    function equals(o : JObject) : boolean; cdecl;                              // (Ljava/lang/Object;)Z A: $1
    function formatAsBlock : boolean; cdecl;                                    // ()Z A: $1
    function getName : JString; cdecl;                                          // ()Ljava/lang/String; A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    function isBlock : boolean; cdecl;                                          // ()Z A: $1
    function isData : boolean; cdecl;                                           // ()Z A: $1
    function isEmpty : boolean; cdecl;                                          // ()Z A: $1
    function isFormListed : boolean; cdecl;                                     // ()Z A: $1
    function isFormSubmittable : boolean; cdecl;                                // ()Z A: $1
    function isInline : boolean; cdecl;                                         // ()Z A: $1
    function isKnownTag : boolean; cdecl; overload;                             // ()Z A: $1
    function isSelfClosing : boolean; cdecl;                                    // ()Z A: $1
    function preserveWhitespace : boolean; cdecl;                               // ()Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJTag = class(TJavaGenericImport<JTagClass, JTag>)
  end;

implementation

end.
