//
// Generated by JavaToPas v1.5 20160713 - 141511
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Selector_SelectorParseException;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JSelector_SelectorParseException = interface;

  JSelector_SelectorParseExceptionClass = interface(JObjectClass)
    ['{5A3C66C4-F1A3-4ABF-B674-B9AAC7DD1E62}']
    function init(msg : JString; params : TJavaArray<JObject>) : JSelector_SelectorParseException; cdecl;// (Ljava/lang/String;[Ljava/lang/Object;)V A: $81
  end;

  [JavaSignature('org/jsoup/select/Selector_SelectorParseException')]
  JSelector_SelectorParseException = interface(JObject)
    ['{511CEBCD-F56A-47F1-BFAB-A8AA599CAAC8}']
  end;

  TJSelector_SelectorParseException = class(TJavaGenericImport<JSelector_SelectorParseExceptionClass, JSelector_SelectorParseException>)
  end;

implementation

end.
