//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_64;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_64 = interface;

  JTokeniserState_64Class = interface(JObjectClass)
    ['{7B9DC76E-F9F4-420E-95A4-1FFFC902D992}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_64')]
  JTokeniserState_64 = interface(JObject)
    ['{6D5B48FA-E21E-448F-AC46-19A403CFE1FF}']
  end;

  TJTokeniserState_64 = class(TJavaGenericImport<JTokeniserState_64Class, JTokeniserState_64>)
  end;

implementation

end.
