//
// Generated by JavaToPas v1.5 20160713 - 141511
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Selector;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.select.Evaluator,
  org.jsoup.nodes.Element;

type
  JSelector = interface;

  JSelectorClass = interface(JObjectClass)
    ['{08A930DA-20E4-42BB-8EA9-2AC18D44F4B3}']
    function select(evaluator : JEvaluator; root : JElement) : JElements; cdecl; overload;// (Lorg/jsoup/select/Evaluator;Lorg/jsoup/nodes/Element;)Lorg/jsoup/select/Elements; A: $9
    function select(query : JString; root : JElement) : JElements; cdecl; overload;// (Ljava/lang/String;Lorg/jsoup/nodes/Element;)Lorg/jsoup/select/Elements; A: $9
    function select(query : JString; roots : JIterable) : JElements; cdecl; overload;// (Ljava/lang/String;Ljava/lang/Iterable;)Lorg/jsoup/select/Elements; A: $9
  end;

  [JavaSignature('org/jsoup/select/Selector$SelectorParseException')]
  JSelector = interface(JObject)
    ['{A0736FEC-A7B6-419C-849F-996CE4FC8FC3}']
  end;

  TJSelector = class(TJavaGenericImport<JSelectorClass, JSelector>)
  end;

implementation

end.
