//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_47;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_47 = interface;

  JTokeniserState_47Class = interface(JObjectClass)
    ['{84113630-4877-4F1A-812A-5F15F644FD4A}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_47')]
  JTokeniserState_47 = interface(JObject)
    ['{E9C78EE7-9273-4CAB-B067-D80C3E763866}']
  end;

  TJTokeniserState_47 = class(TJavaGenericImport<JTokeniserState_47Class, JTokeniserState_47>)
  end;

implementation

end.
