//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_59;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_59 = interface;

  JTokeniserState_59Class = interface(JObjectClass)
    ['{008646A0-CD6B-41C8-BC06-D9C8B88DF8C0}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_59')]
  JTokeniserState_59 = interface(JObject)
    ['{0483EF2B-4D13-491D-B5AB-06B0539684AF}']
  end;

  TJTokeniserState_59 = class(TJavaGenericImport<JTokeniserState_59Class, JTokeniserState_59>)
  end;

implementation

end.
