//
// Generated by JavaToPas v1.5 20160713 - 141445
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.Jsoup;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Document,
  org.jsoup.parser.Parser,
  org.jsoup.Connection,
  java.net.URL,
  org.jsoup.safety.Whitelist,
  org.jsoup.nodes.Document_OutputSettings;

type
  JJsoup = interface;

  JJsoupClass = interface(JObjectClass)
    ['{58557D6E-2506-44CE-B5DF-447C619E349B}']
    function clean(bodyHtml : JString; baseUri : JString; whitelist : JWhitelist) : JString; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;Lorg/jsoup/safety/Whitelist;)Ljava/lang/String; A: $9
    function clean(bodyHtml : JString; baseUri : JString; whitelist : JWhitelist; outputSettings : JDocument_OutputSettings) : JString; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;Lorg/jsoup/safety/Whitelist;Lorg/jsoup/nodes/Document$OutputSettings;)Ljava/lang/String; A: $9
    function clean(bodyHtml : JString; whitelist : JWhitelist) : JString; cdecl; overload;// (Ljava/lang/String;Lorg/jsoup/safety/Whitelist;)Ljava/lang/String; A: $9
    function connect(url : JString) : JConnection; cdecl;                       // (Ljava/lang/String;)Lorg/jsoup/Connection; A: $9
    function isValid(bodyHtml : JString; whitelist : JWhitelist) : boolean; cdecl;// (Ljava/lang/String;Lorg/jsoup/safety/Whitelist;)Z A: $9
    function parse(&in : JFile; charsetName : JString) : JDocument; cdecl; overload;// (Ljava/io/File;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function parse(&in : JFile; charsetName : JString; baseUri : JString) : JDocument; cdecl; overload;// (Ljava/io/File;Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function parse(&in : JInputStream; charsetName : JString; baseUri : JString) : JDocument; cdecl; overload;// (Ljava/io/InputStream;Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function parse(&in : JInputStream; charsetName : JString; baseUri : JString; parser : JParser) : JDocument; cdecl; overload;// (Ljava/io/InputStream;Ljava/lang/String;Ljava/lang/String;Lorg/jsoup/parser/Parser;)Lorg/jsoup/nodes/Document; A: $9
    function parse(html : JString) : JDocument; cdecl; overload;                // (Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function parse(html : JString; baseUri : JString) : JDocument; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function parse(html : JString; baseUri : JString; parser : JParser) : JDocument; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;Lorg/jsoup/parser/Parser;)Lorg/jsoup/nodes/Document; A: $9
    function parse(url : JURL; timeoutMillis : Integer) : JDocument; cdecl; overload;// (Ljava/net/URL;I)Lorg/jsoup/nodes/Document; A: $9
    function parseBodyFragment(bodyHtml : JString) : JDocument; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function parseBodyFragment(bodyHtml : JString; baseUri : JString) : JDocument; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
  end;

  [JavaSignature('org/jsoup/Jsoup')]
  JJsoup = interface(JObject)
    ['{4CC98621-723B-4DC9-AFEC-C70C1C5D68C9}']
  end;

  TJJsoup = class(TJavaGenericImport<JJsoupClass, JJsoup>)
  end;

implementation

end.
