//
// Generated by JavaToPas v1.5 20160713 - 141509
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_IsNthLastChild;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_IsNthLastChild = interface;

  JEvaluator_IsNthLastChildClass = interface(JObjectClass)
    ['{F559833B-F4FB-4454-BC91-AEE9D12B8C61}']
    function init(a : Integer; b : Integer) : JEvaluator_IsNthLastChild; cdecl; // (II)V A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_IsNthLastChild')]
  JEvaluator_IsNthLastChild = interface(JObject)
    ['{B5856A33-353A-41F1-AD90-C0C78E64C760}']
  end;

  TJEvaluator_IsNthLastChild = class(TJavaGenericImport<JEvaluator_IsNthLastChildClass, JEvaluator_IsNthLastChild>)
  end;

implementation

end.
