//
// Generated by JavaToPas v1.5 20160713 - 141445
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.helper.W3CDom;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  javax.xml.parsers.DocumentBuilderFactory,
  org.w3c.dom.Document,
  org.jsoup.nodes.Document;

type
  JW3CDom = interface;

  JW3CDomClass = interface(JObjectClass)
    ['{E18F9C32-9C72-43B2-B3AD-4C355A371AAC}']
    function asString(doc : JDocument) : JString; cdecl;                        // (Lorg/w3c/dom/Document;)Ljava/lang/String; A: $1
    function fromJsoup(&in : JDocument) : JDocument; cdecl;                     // (Lorg/jsoup/nodes/Document;)Lorg/w3c/dom/Document; A: $1
    function init : JW3CDom; cdecl;                                             // ()V A: $1
    procedure convert(&in : JDocument; &out : JDocument) ; cdecl;               // (Lorg/jsoup/nodes/Document;Lorg/w3c/dom/Document;)V A: $1
  end;

  [JavaSignature('org/jsoup/helper/W3CDom$W3CBuilder')]
  JW3CDom = interface(JObject)
    ['{9FDCC5ED-2933-4666-A3E1-AD6FD673EA73}']
    function asString(doc : JDocument) : JString; cdecl;                        // (Lorg/w3c/dom/Document;)Ljava/lang/String; A: $1
    function fromJsoup(&in : JDocument) : JDocument; cdecl;                     // (Lorg/jsoup/nodes/Document;)Lorg/w3c/dom/Document; A: $1
    procedure convert(&in : JDocument; &out : JDocument) ; cdecl;               // (Lorg/jsoup/nodes/Document;Lorg/w3c/dom/Document;)V A: $1
  end;

  TJW3CDom = class(TJavaGenericImport<JW3CDomClass, JW3CDom>)
  end;

implementation

end.
