//
// Generated by JavaToPas v1.5 20160713 - 141457
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.Token_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JToken_1 = interface;

  JToken_1Class = interface(JObjectClass)
    ['{23148E16-71DA-4051-AE08-7AE6EE1A9453}']
  end;

  [JavaSignature('org/jsoup/parser/Token_1')]
  JToken_1 = interface(JObject)
    ['{8A3DF667-1B39-4ADE-9804-16935E485C3C}']
  end;

  TJToken_1 = class(TJavaGenericImport<JToken_1Class, JToken_1>)
  end;

implementation

end.
