//
// Generated by JavaToPas v1.5 20160713 - 141455
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_6;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_6 = interface;

  JHtmlTreeBuilderState_6Class = interface(JObjectClass)
    ['{F955C140-3B18-4BC7-85CC-60E0CF6636CA}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_6')]
  JHtmlTreeBuilderState_6 = interface(JObject)
    ['{7B1273C6-59CA-4AAF-A2E1-68F49AA1C9B3}']
  end;

  TJHtmlTreeBuilderState_6 = class(TJavaGenericImport<JHtmlTreeBuilderState_6Class, JHtmlTreeBuilderState_6>)
  end;

implementation

end.
