//
// Generated by JavaToPas v1.5 20160713 - 141447
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Document_OutputSettings;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Entities_EscapeMode,
  java.nio.charset.Charset,
  java.nio.charset.CharsetEncoder,
  org.jsoup.nodes.Document_OutputSettings_Syntax;

type
  JDocument_OutputSettings = interface;

  JDocument_OutputSettingsClass = interface(JObjectClass)
    ['{FA45719C-4461-4CD2-A6BE-53518FAF5B3F}']
    function charset : JCharset; cdecl; overload;                               // ()Ljava/nio/charset/Charset; A: $1
    function charset(charset : JCharset) : JDocument_OutputSettings; cdecl; overload;// (Ljava/nio/charset/Charset;)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function charset(charset : JString) : JDocument_OutputSettings; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function clone : JDocument_OutputSettings; cdecl;                           // ()Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function escapeMode : JEntities_EscapeMode; cdecl; overload;                // ()Lorg/jsoup/nodes/Entities$EscapeMode; A: $1
    function escapeMode(escapeMode : JEntities_EscapeMode) : JDocument_OutputSettings; cdecl; overload;// (Lorg/jsoup/nodes/Entities$EscapeMode;)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function indentAmount : Integer; cdecl; overload;                           // ()I A: $1
    function indentAmount(indentAmount : Integer) : JDocument_OutputSettings; cdecl; overload;// (I)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function init : JDocument_OutputSettings; cdecl;                            // ()V A: $1
    function outline : boolean; cdecl; overload;                                // ()Z A: $1
    function outline(outlineMode : boolean) : JDocument_OutputSettings; cdecl; overload;// (Z)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function prettyPrint : boolean; cdecl; overload;                            // ()Z A: $1
    function prettyPrint(pretty : boolean) : JDocument_OutputSettings; cdecl; overload;// (Z)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function syntax : JDocument_OutputSettings_Syntax; cdecl; overload;         // ()Lorg/jsoup/nodes/Document$OutputSettings$Syntax; A: $1
    function syntax(syntax : JDocument_OutputSettings_Syntax) : JDocument_OutputSettings; cdecl; overload;// (Lorg/jsoup/nodes/Document$OutputSettings$Syntax;)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
  end;

  [JavaSignature('org/jsoup/nodes/Document$OutputSettings$Syntax')]
  JDocument_OutputSettings = interface(JObject)
    ['{A399F443-FC54-4E8C-937B-2C284359E048}']
    function charset : JCharset; cdecl; overload;                               // ()Ljava/nio/charset/Charset; A: $1
    function charset(charset : JCharset) : JDocument_OutputSettings; cdecl; overload;// (Ljava/nio/charset/Charset;)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function charset(charset : JString) : JDocument_OutputSettings; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function clone : JDocument_OutputSettings; cdecl;                           // ()Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function escapeMode : JEntities_EscapeMode; cdecl; overload;                // ()Lorg/jsoup/nodes/Entities$EscapeMode; A: $1
    function escapeMode(escapeMode : JEntities_EscapeMode) : JDocument_OutputSettings; cdecl; overload;// (Lorg/jsoup/nodes/Entities$EscapeMode;)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function indentAmount : Integer; cdecl; overload;                           // ()I A: $1
    function indentAmount(indentAmount : Integer) : JDocument_OutputSettings; cdecl; overload;// (I)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function outline : boolean; cdecl; overload;                                // ()Z A: $1
    function outline(outlineMode : boolean) : JDocument_OutputSettings; cdecl; overload;// (Z)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function prettyPrint : boolean; cdecl; overload;                            // ()Z A: $1
    function prettyPrint(pretty : boolean) : JDocument_OutputSettings; cdecl; overload;// (Z)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
    function syntax : JDocument_OutputSettings_Syntax; cdecl; overload;         // ()Lorg/jsoup/nodes/Document$OutputSettings$Syntax; A: $1
    function syntax(syntax : JDocument_OutputSettings_Syntax) : JDocument_OutputSettings; cdecl; overload;// (Lorg/jsoup/nodes/Document$OutputSettings$Syntax;)Lorg/jsoup/nodes/Document$OutputSettings; A: $1
  end;

  TJDocument_OutputSettings = class(TJavaGenericImport<JDocument_OutputSettingsClass, JDocument_OutputSettings>)
  end;

implementation

end.
