//
// Generated by JavaToPas v1.5 20160713 - 141508
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_AttributeWithValue;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_AttributeWithValue = interface;

  JEvaluator_AttributeWithValueClass = interface(JObjectClass)
    ['{BED508B4-9F4A-43FC-8EF8-1AAF5FCDC228}']
    function init(key : JString; value : JString) : JEvaluator_AttributeWithValue; cdecl;// (Ljava/lang/String;Ljava/lang/String;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_AttributeWithValue')]
  JEvaluator_AttributeWithValue = interface(JObject)
    ['{63EE6B28-EB95-48B7-B889-CF9C13573385}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_AttributeWithValue = class(TJavaGenericImport<JEvaluator_AttributeWithValueClass, JEvaluator_AttributeWithValue>)
  end;

implementation

end.
