//
// Generated by JavaToPas v1.5 20160713 - 141441
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.helper.DescendableLinkedList_DescendingIterator;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JDescendableLinkedList_DescendingIterator = interface;

  JDescendableLinkedList_DescendingIteratorClass = interface(JObjectClass)
    ['{EC5BC6AE-6439-4CDA-BB19-41968D057C1A}']
    function hasNext : boolean; cdecl;                                          // ()Z A: $1
    function next : JObject; cdecl;                                             // ()Ljava/lang/Object; A: $1
    procedure remove ; cdecl;                                                   // ()V A: $1
  end;

  [JavaSignature('org/jsoup/helper/DescendableLinkedList_DescendingIterator')]
  JDescendableLinkedList_DescendingIterator = interface(JObject)
    ['{B1A16E9C-DA65-4A84-B1A9-5DDB21BD4E8C}']
    function hasNext : boolean; cdecl;                                          // ()Z A: $1
    function next : JObject; cdecl;                                             // ()Ljava/lang/Object; A: $1
    procedure remove ; cdecl;                                                   // ()V A: $1
  end;

  TJDescendableLinkedList_DescendingIterator = class(TJavaGenericImport<JDescendableLinkedList_DescendingIteratorClass, JDescendableLinkedList_DescendingIterator>)
  end;

implementation

end.
