//
// Generated by JavaToPas v1.5 20160713 - 141505
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TreeBuilder;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.CharacterReader,
  org.jsoup.parser.Tokeniser,
  org.jsoup.nodes.Document,
  org.jsoup.parser.Token,
  org.jsoup.parser.ParseErrorList,
  org.jsoup.parser.Token_StartTag,
  org.jsoup.parser.Token_EndTag,
  org.jsoup.nodes.Attributes,
  org.jsoup.nodes.Element;

type
  JTreeBuilder = interface;

  JTreeBuilderClass = interface(JObjectClass)
    ['{D9D17822-C968-4730-A594-B3F421D47B72}']
    function processStartTag(&name : JString; attrs : JAttributes) : boolean; cdecl; overload;// (Ljava/lang/String;Lorg/jsoup/nodes/Attributes;)Z A: $1
  end;

  [JavaSignature('org/jsoup/parser/TreeBuilder')]
  JTreeBuilder = interface(JObject)
    ['{6A31C277-929F-4763-8A6B-4DAB25236FED}']
    function processStartTag(&name : JString; attrs : JAttributes) : boolean; cdecl; overload;// (Ljava/lang/String;Lorg/jsoup/nodes/Attributes;)Z A: $1
  end;

  TJTreeBuilder = class(TJavaGenericImport<JTreeBuilderClass, JTreeBuilder>)
  end;

implementation

end.
