//
// Generated by JavaToPas v1.5 20160713 - 141511
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.StructuralEvaluator;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.select.Evaluator;

type
  JStructuralEvaluator = interface;

  JStructuralEvaluatorClass = interface(JObjectClass)
    ['{ECBECCE3-4BCD-457D-87B4-C9835B9E8F6D}']
  end;

  [JavaSignature('org/jsoup/select/StructuralEvaluator$ImmediatePreviousSibling')]
  JStructuralEvaluator = interface(JObject)
    ['{A83D1AE3-858E-4BED-8C5B-FFF936379417}']
  end;

  TJStructuralEvaluator = class(TJavaGenericImport<JStructuralEvaluatorClass, JStructuralEvaluator>)
  end;

implementation

end.
