//
// Generated by JavaToPas v1.5 20160713 - 141508
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_Class;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_Class = interface;

  JEvaluator_ClassClass = interface(JObjectClass)
    ['{BDBF3131-C58C-4E84-810B-7411373B6405}']
    function init(className : JString) : JEvaluator_Class; cdecl;               // (Ljava/lang/String;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_Class')]
  JEvaluator_Class = interface(JObject)
    ['{E7616577-1142-4253-9147-65B11F917B64}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_Class = class(TJavaGenericImport<JEvaluator_ClassClass, JEvaluator_Class>)
  end;

implementation

end.
