//
// Generated by JavaToPas v1.5 20160713 - 141509
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_IndexGreaterThan;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_IndexGreaterThan = interface;

  JEvaluator_IndexGreaterThanClass = interface(JObjectClass)
    ['{3B879D6B-C166-46A0-9DF0-B9FEC4DEB891}']
    function init(&index : Integer) : JEvaluator_IndexGreaterThan; cdecl;       // (I)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_IndexGreaterThan')]
  JEvaluator_IndexGreaterThan = interface(JObject)
    ['{891AD869-550D-49D1-9381-F147F53E0CCA}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_IndexGreaterThan = class(TJavaGenericImport<JEvaluator_IndexGreaterThanClass, JEvaluator_IndexGreaterThan>)
  end;

implementation

end.
