//
// Generated by JavaToPas v1.5 20160713 - 141453
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_1 = interface;

  JHtmlTreeBuilderState_1Class = interface(JObjectClass)
    ['{9BE4A72B-B93F-4447-9021-76CE38CAC158}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_1')]
  JHtmlTreeBuilderState_1 = interface(JObject)
    ['{6CC8D5C6-4DE2-4513-ACFE-783AD01733B9}']
  end;

  TJHtmlTreeBuilderState_1 = class(TJavaGenericImport<JHtmlTreeBuilderState_1Class, JHtmlTreeBuilderState_1>)
  end;

implementation

end.
