//
// Generated by JavaToPas v1.5 20160713 - 141453
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_15;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_15 = interface;

  JHtmlTreeBuilderState_15Class = interface(JObjectClass)
    ['{83178601-0199-4508-8621-DEB62AE83304}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_15')]
  JHtmlTreeBuilderState_15 = interface(JObject)
    ['{194DEE2A-7319-422D-8B8C-204435AFF122}']
  end;

  TJHtmlTreeBuilderState_15 = class(TJavaGenericImport<JHtmlTreeBuilderState_15Class, JHtmlTreeBuilderState_15>)
  end;

implementation

end.
