//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_12;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_12 = interface;

  JTokeniserState_12Class = interface(JObjectClass)
    ['{CEBFD89D-1D9B-4B0D-818C-5A4A30151762}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_12')]
  JTokeniserState_12 = interface(JObject)
    ['{5C6C606C-2A64-46C0-948E-33533C05EADB}']
  end;

  TJTokeniserState_12 = class(TJavaGenericImport<JTokeniserState_12Class, JTokeniserState_12>)
  end;

implementation

end.
