//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_4;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_4 = interface;

  JTokeniserState_4Class = interface(JObjectClass)
    ['{07D518D6-5D60-4A09-B2B0-795862BEFCA9}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_4')]
  JTokeniserState_4 = interface(JObject)
    ['{C04F5482-A7E2-49C6-9AB5-E962A3EBEA35}']
  end;

  TJTokeniserState_4 = class(TJavaGenericImport<JTokeniserState_4Class, JTokeniserState_4>)
  end;

implementation

end.
