//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_7;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_7 = interface;

  JTokeniserState_7Class = interface(JObjectClass)
    ['{DCDCF5C2-89ED-4AC9-9900-A6DD6718DF20}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_7')]
  JTokeniserState_7 = interface(JObject)
    ['{CD7AC612-3F99-462D-8BE2-8E682C292301}']
  end;

  TJTokeniserState_7 = class(TJavaGenericImport<JTokeniserState_7Class, JTokeniserState_7>)
  end;

implementation

end.
