//
// Generated by JavaToPas v1.5 20160713 - 141446
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.DataNode;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.lang.Appendable,
  org.jsoup.nodes.Document_OutputSettings;

type
  JDataNode = interface;

  JDataNodeClass = interface(JObjectClass)
    ['{261A2367-F662-45B8-86E9-DBB33DE4D63F}']
    function createFromEncoded(encodedData : JString; baseUri : JString) : JDataNode; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/DataNode; A: $9
    function getWholeData : JString; cdecl;                                     // ()Ljava/lang/String; A: $1
    function init(data : JString; baseUri : JString) : JDataNode; cdecl;        // (Ljava/lang/String;Ljava/lang/String;)V A: $1
    function nodeName : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function setWholeData(data : JString) : JDataNode; cdecl;                   // (Ljava/lang/String;)Lorg/jsoup/nodes/DataNode; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/nodes/DataNode')]
  JDataNode = interface(JObject)
    ['{6AE5A016-5F8E-41CC-AB10-FC69E9309E7F}']
    function getWholeData : JString; cdecl;                                     // ()Ljava/lang/String; A: $1
    function nodeName : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function setWholeData(data : JString) : JDataNode; cdecl;                   // (Ljava/lang/String;)Lorg/jsoup/nodes/DataNode; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJDataNode = class(TJavaGenericImport<JDataNodeClass, JDataNode>)
  end;

const
  TJDataNodeDATA_KEY = 'data';

implementation

end.
