//
// Generated by JavaToPas v1.5 20160713 - 141449
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Entities_CoreCharset;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JEntities_CoreCharset = interface;

  JEntities_CoreCharsetClass = interface(JObjectClass)
    ['{A8207283-4937-4D6B-B279-0D24E0BB747C}']
    function _Getascii : JEntities_CoreCharset; cdecl;                          //  A: $4019
    function _Getfallback : JEntities_CoreCharset; cdecl;                       //  A: $4019
    function _Getutf : JEntities_CoreCharset; cdecl;                            //  A: $4019
    function valueOf(&name : JString) : JEntities_CoreCharset; cdecl;           // (Ljava/lang/String;)Lorg/jsoup/nodes/Entities$CoreCharset; A: $9
    function values : TJavaArray<JEntities_CoreCharset>; cdecl;                 // ()[Lorg/jsoup/nodes/Entities$CoreCharset; A: $9
    property ascii : JEntities_CoreCharset read _Getascii;                      // Lorg/jsoup/nodes/Entities$CoreCharset; A: $4019
    property fallback : JEntities_CoreCharset read _Getfallback;                // Lorg/jsoup/nodes/Entities$CoreCharset; A: $4019
    property utf : JEntities_CoreCharset read _Getutf;                          // Lorg/jsoup/nodes/Entities$CoreCharset; A: $4019
  end;

  [JavaSignature('org/jsoup/nodes/Entities_CoreCharset')]
  JEntities_CoreCharset = interface(JObject)
    ['{30A2AD5E-AB69-4031-9F27-4728A2748710}']
  end;

  TJEntities_CoreCharset = class(TJavaGenericImport<JEntities_CoreCharsetClass, JEntities_CoreCharset>)
  end;

implementation

end.
