//
// Generated by JavaToPas v1.5 20160713 - 141440
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.Connection_KeyVal;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JConnection_KeyVal = interface;

  JConnection_KeyValClass = interface(JObjectClass)
    ['{A8E2F637-B3A7-49BE-A911-AD1AD04C49D2}']
    function hasInputStream : boolean; cdecl;                                   // ()Z A: $401
    function inputStream : JInputStream; cdecl; overload;                       // ()Ljava/io/InputStream; A: $401
    function inputStream(JInputStreamparam0 : JInputStream) : JConnection_KeyVal; cdecl; overload;// (Ljava/io/InputStream;)Lorg/jsoup/Connection$KeyVal; A: $401
    function key : JString; cdecl; overload;                                    // ()Ljava/lang/String; A: $401
    function key(JStringparam0 : JString) : JConnection_KeyVal; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/Connection$KeyVal; A: $401
    function value : JString; cdecl; overload;                                  // ()Ljava/lang/String; A: $401
    function value(JStringparam0 : JString) : JConnection_KeyVal; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/Connection$KeyVal; A: $401
  end;

  [JavaSignature('org/jsoup/Connection_KeyVal')]
  JConnection_KeyVal = interface(JObject)
    ['{C8E3E9D9-63FC-4496-88DA-BB658567AE98}']
    function hasInputStream : boolean; cdecl;                                   // ()Z A: $401
    function inputStream : JInputStream; cdecl; overload;                       // ()Ljava/io/InputStream; A: $401
    function inputStream(JInputStreamparam0 : JInputStream) : JConnection_KeyVal; cdecl; overload;// (Ljava/io/InputStream;)Lorg/jsoup/Connection$KeyVal; A: $401
    function key : JString; cdecl; overload;                                    // ()Ljava/lang/String; A: $401
    function key(JStringparam0 : JString) : JConnection_KeyVal; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/Connection$KeyVal; A: $401
    function value : JString; cdecl; overload;                                  // ()Ljava/lang/String; A: $401
    function value(JStringparam0 : JString) : JConnection_KeyVal; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/Connection$KeyVal; A: $401
  end;

  TJConnection_KeyVal = class(TJavaGenericImport<JConnection_KeyValClass, JConnection_KeyVal>)
  end;

implementation

end.
