//
// Generated by JavaToPas v1.5 20160713 - 141450
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Node_OuterHtmlVisitor;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.lang.Appendable,
  org.jsoup.nodes.Document_OutputSettings,
  org.jsoup.nodes.Document;

type
  JNode_OuterHtmlVisitor = interface;

  JNode_OuterHtmlVisitorClass = interface(JObjectClass)
    ['{FE543884-DEF0-4832-AC31-1ED0E8C02265}']
    procedure head(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  [JavaSignature('org/jsoup/nodes/Node_OuterHtmlVisitor')]
  JNode_OuterHtmlVisitor = interface(JObject)
    ['{E16FAB13-3B11-45C7-A4EB-4B8134A73E21}']
    procedure head(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  TJNode_OuterHtmlVisitor = class(TJavaGenericImport<JNode_OuterHtmlVisitorClass, JNode_OuterHtmlVisitor>)
  end;

implementation

end.
