//
// Generated by JavaToPas v1.5 20160713 - 141441
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.helper.DescendableLinkedList_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JDescendableLinkedList_1 = interface;

  JDescendableLinkedList_1Class = interface(JObjectClass)
    ['{1C0C8E7E-F1E7-4C8F-BBCA-1A43E2C35DA1}']
  end;

  [JavaSignature('org/jsoup/helper/DescendableLinkedList_1')]
  JDescendableLinkedList_1 = interface(JObject)
    ['{77A1130E-A350-4E3C-BD39-F9F513BA0676}']
  end;

  TJDescendableLinkedList_1 = class(TJavaGenericImport<JDescendableLinkedList_1Class, JDescendableLinkedList_1>)
  end;

implementation

end.
