//
// Generated by JavaToPas v1.5 20160713 - 141509
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_Id;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_Id = interface;

  JEvaluator_IdClass = interface(JObjectClass)
    ['{5E8516CC-4DF0-44BB-BD34-D1DAFC5AFED1}']
    function init(id : JString) : JEvaluator_Id; cdecl;                         // (Ljava/lang/String;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_Id')]
  JEvaluator_Id = interface(JObject)
    ['{FDB4B098-7632-45A1-9251-49B503F4A563}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_Id = class(TJavaGenericImport<JEvaluator_IdClass, JEvaluator_Id>)
  end;

implementation

end.
