//
// Generated by JavaToPas v1.5 20160713 - 141451
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.XmlDeclaration;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.lang.Appendable,
  org.jsoup.nodes.Document_OutputSettings;

type
  JXmlDeclaration = interface;

  JXmlDeclarationClass = interface(JObjectClass)
    ['{E873022E-53AB-42F5-AE04-CFD90F76DE5A}']
    function &name : JString; cdecl;                                            // ()Ljava/lang/String; A: $1
    function getWholeDeclaration : JString; cdecl;                              // ()Ljava/lang/String; A: $1
    function init(&name : JString; baseUri : JString; isProcessingInstruction : boolean) : JXmlDeclaration; cdecl;// (Ljava/lang/String;Ljava/lang/String;Z)V A: $1
    function nodeName : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/nodes/XmlDeclaration')]
  JXmlDeclaration = interface(JObject)
    ['{8FFD3C80-9C14-4A26-8EBF-362D5690EF3B}']
    function &name : JString; cdecl;                                            // ()Ljava/lang/String; A: $1
    function getWholeDeclaration : JString; cdecl;                              // ()Ljava/lang/String; A: $1
    function nodeName : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJXmlDeclaration = class(TJavaGenericImport<JXmlDeclarationClass, JXmlDeclaration>)
  end;

implementation

end.
