//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_26;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_26 = interface;

  JTokeniserState_26Class = interface(JObjectClass)
    ['{C421261C-96EC-49CE-8B53-197D8F783EA6}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_26')]
  JTokeniserState_26 = interface(JObject)
    ['{8ED01C91-E114-4F41-8B4F-78D093DD09E3}']
  end;

  TJTokeniserState_26 = class(TJavaGenericImport<JTokeniserState_26Class, JTokeniserState_26>)
  end;

implementation

end.
