//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_31;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_31 = interface;

  JTokeniserState_31Class = interface(JObjectClass)
    ['{A31C13B0-578D-4528-BA75-2CDD12C98EB9}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_31')]
  JTokeniserState_31 = interface(JObject)
    ['{9C9FA57B-1456-4E3F-A7BC-CF917A319A96}']
  end;

  TJTokeniserState_31 = class(TJavaGenericImport<JTokeniserState_31Class, JTokeniserState_31>)
  end;

implementation

end.
