//
// Generated by JavaToPas v1.5 20160713 - 141445
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Attribute;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.lang.Appendable,
  org.jsoup.nodes.Document_OutputSettings;

type
  JAttribute = interface;

  JAttributeClass = interface(JObjectClass)
    ['{4B9BFB21-EC17-430A-AD1E-86B55AEAEC79}']
    function clone : JAttribute; cdecl;                                         // ()Lorg/jsoup/nodes/Attribute; A: $1
    function createFromEncoded(unencodedKey : JString; encodedValue : JString) : JAttribute; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Attribute; A: $9
    function equals(o : JObject) : boolean; cdecl;                              // (Ljava/lang/Object;)Z A: $1
    function getKey : JString; cdecl;                                           // ()Ljava/lang/String; A: $1
    function getValue : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    function html : JString; cdecl; overload;                                   // ()Ljava/lang/String; A: $1
    function init(key : JString; value : JString) : JAttribute; cdecl;          // (Ljava/lang/String;Ljava/lang/String;)V A: $1
    function setValue(value : JString) : JString; cdecl;                        // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure setKey(key : JString) ; cdecl;                                    // (Ljava/lang/String;)V A: $1
  end;

  [JavaSignature('org/jsoup/nodes/Attribute')]
  JAttribute = interface(JObject)
    ['{FCD48278-C0C4-4E11-9E6C-2A2555E628A1}']
    function clone : JAttribute; cdecl;                                         // ()Lorg/jsoup/nodes/Attribute; A: $1
    function equals(o : JObject) : boolean; cdecl;                              // (Ljava/lang/Object;)Z A: $1
    function getKey : JString; cdecl;                                           // ()Ljava/lang/String; A: $1
    function getValue : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    function html : JString; cdecl; overload;                                   // ()Ljava/lang/String; A: $1
    function setValue(value : JString) : JString; cdecl;                        // (Ljava/lang/String;)Ljava/lang/String; A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure setKey(key : JString) ; cdecl;                                    // (Ljava/lang/String;)V A: $1
  end;

  TJAttribute = class(TJavaGenericImport<JAttributeClass, JAttribute>)
  end;

implementation

end.
