//
// Generated by JavaToPas v1.5 20160713 - 141511
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.StructuralEvaluator_Not;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.select.Evaluator,
  org.jsoup.nodes.Element;

type
  JStructuralEvaluator_Not = interface;

  JStructuralEvaluator_NotClass = interface(JObjectClass)
    ['{F7A0A575-4A15-4C13-B5D6-D4F36ECA4162}']
    function init(evaluator : JEvaluator) : JStructuralEvaluator_Not; cdecl;    // (Lorg/jsoup/select/Evaluator;)V A: $1
    function matches(root : JElement; node : JElement) : boolean; cdecl;        // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/StructuralEvaluator_Not')]
  JStructuralEvaluator_Not = interface(JObject)
    ['{866675B2-4985-4918-B3FE-D1C8841863BA}']
    function matches(root : JElement; node : JElement) : boolean; cdecl;        // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJStructuralEvaluator_Not = class(TJavaGenericImport<JStructuralEvaluator_NotClass, JStructuralEvaluator_Not>)
  end;

implementation

end.
