//
// Generated by JavaToPas v1.5 20160713 - 141457
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.Token_EndTag;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JToken_EndTag = interface;

  JToken_EndTagClass = interface(JObjectClass)
    ['{32F57E52-D77C-47B2-B0C0-AFD42EC51CFF}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/parser/Token_EndTag')]
  JToken_EndTag = interface(JObject)
    ['{FB7B78FC-EA2E-4E63-81D7-9487E02F25DE}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJToken_EndTag = class(TJavaGenericImport<JToken_EndTagClass, JToken_EndTag>)
  end;

implementation

end.
