//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_67;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_67 = interface;

  JTokeniserState_67Class = interface(JObjectClass)
    ['{BFB8DABF-81BB-40CF-89D0-73C6BF27592F}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_67')]
  JTokeniserState_67 = interface(JObject)
    ['{AA82D5F9-7E25-4CB4-993A-3824D664FBF6}']
  end;

  TJTokeniserState_67 = class(TJavaGenericImport<JTokeniserState_67Class, JTokeniserState_67>)
  end;

implementation

end.
