//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_48;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_48 = interface;

  JTokeniserState_48Class = interface(JObjectClass)
    ['{9E15FAA5-3896-4D09-8D3F-4E1891893F83}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_48')]
  JTokeniserState_48 = interface(JObject)
    ['{DB4B597B-4832-459E-A724-8D64F52DCEA5}']
  end;

  TJTokeniserState_48 = class(TJavaGenericImport<JTokeniserState_48Class, JTokeniserState_48>)
  end;

implementation

end.
