//
// Generated by JavaToPas v1.5 20160713 - 141508
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_ContainsText;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_ContainsText = interface;

  JEvaluator_ContainsTextClass = interface(JObjectClass)
    ['{D0B35BB6-AD1D-408F-B079-0F7FCC73D5E6}']
    function init(searchText : JString) : JEvaluator_ContainsText; cdecl;       // (Ljava/lang/String;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_ContainsText')]
  JEvaluator_ContainsText = interface(JObject)
    ['{D5AFD3C1-BEC8-4C4A-B178-3B362A6E1845}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_ContainsText = class(TJavaGenericImport<JEvaluator_ContainsTextClass, JEvaluator_ContainsText>)
  end;

implementation

end.
