//
// Generated by JavaToPas v1.5 20160713 - 141440
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.examples.HtmlToPlainText_FormattingVisitor;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.examples.HtmlToPlainText,
  org.jsoup.nodes.Document;

type
  JHtmlToPlainText_FormattingVisitor = interface;

  JHtmlToPlainText_FormattingVisitorClass = interface(JObjectClass)
    ['{7E60A2E5-70E2-4629-A0D8-007C872AED3D}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure head(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  [JavaSignature('org/jsoup/examples/HtmlToPlainText_FormattingVisitor')]
  JHtmlToPlainText_FormattingVisitor = interface(JObject)
    ['{AE17D29E-70A5-49C9-BE8B-60A665B17AFE}']
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
    procedure head(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
    procedure tail(node : JNode; depth : Integer) ; cdecl;                      // (Lorg/jsoup/nodes/Node;I)V A: $1
  end;

  TJHtmlToPlainText_FormattingVisitor = class(TJavaGenericImport<JHtmlToPlainText_FormattingVisitorClass, JHtmlToPlainText_FormattingVisitor>)
  end;

const
  TJHtmlToPlainText_FormattingVisitormaxWidth = 80;

implementation

end.
