//
// Generated by JavaToPas v1.5 20160713 - 141507
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.CombiningEvaluator;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.select.Evaluator;

type
  JCombiningEvaluator = interface;

  JCombiningEvaluatorClass = interface(JObjectClass)
    ['{853774B9-EF7F-495F-977C-92C7AF9FC628}']
  end;

  [JavaSignature('org/jsoup/select/CombiningEvaluator$Or')]
  JCombiningEvaluator = interface(JObject)
    ['{1ED72EE1-3F3B-471A-AAF1-BDCF9CFE402F}']
  end;

  TJCombiningEvaluator = class(TJavaGenericImport<JCombiningEvaluatorClass, JCombiningEvaluator>)
  end;

implementation

end.
