//
// Generated by JavaToPas v1.5 20160713 - 141454
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_2;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_2 = interface;

  JHtmlTreeBuilderState_2Class = interface(JObjectClass)
    ['{243BE888-1C1A-409E-949F-74FA4C96B610}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_2')]
  JHtmlTreeBuilderState_2 = interface(JObject)
    ['{C0BECB7B-CB51-4C42-8507-6FF67C1231F0}']
  end;

  TJHtmlTreeBuilderState_2 = class(TJavaGenericImport<JHtmlTreeBuilderState_2Class, JHtmlTreeBuilderState_2>)
  end;

implementation

end.
