//
// Generated by JavaToPas v1.5 20160713 - 141453
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_12;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder,
  org.jsoup.parser.TreeBuilder;

type
  JHtmlTreeBuilderState_12 = interface;

  JHtmlTreeBuilderState_12Class = interface(JObjectClass)
    ['{DD32D075-86E4-4C30-AE6E-A5B6F79C301F}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_12')]
  JHtmlTreeBuilderState_12 = interface(JObject)
    ['{61126472-838A-4559-95BD-6440A218B1D2}']
  end;

  TJHtmlTreeBuilderState_12 = class(TJavaGenericImport<JHtmlTreeBuilderState_12Class, JHtmlTreeBuilderState_12>)
  end;

implementation

end.
