//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_42;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_42 = interface;

  JTokeniserState_42Class = interface(JObjectClass)
    ['{F4D72CA1-76DA-43A6-8416-DAB34BD12D3C}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_42')]
  JTokeniserState_42 = interface(JObject)
    ['{33281FC4-107D-44F5-AE32-8B44D1E01F42}']
  end;

  TJTokeniserState_42 = class(TJavaGenericImport<JTokeniserState_42Class, JTokeniserState_42>)
  end;

implementation

end.
