//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_13;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_13 = interface;

  JTokeniserState_13Class = interface(JObjectClass)
    ['{2BAB6FDC-8BE2-4C73-9EE0-838D90D9979E}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_13')]
  JTokeniserState_13 = interface(JObject)
    ['{BB255739-DAA9-408A-B596-2D8BEBCF196D}']
  end;

  TJTokeniserState_13 = class(TJavaGenericImport<JTokeniserState_13Class, JTokeniserState_13>)
  end;

implementation

end.
