//
// Generated by JavaToPas v1.5 20160713 - 141506
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.safety.Whitelist_TypedValue;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JWhitelist_TypedValue = interface;

  JWhitelist_TypedValueClass = interface(JObjectClass)
    ['{8228BD47-9550-40B6-A8D6-EC1909488FF5}']
    function equals(obj : JObject) : boolean; cdecl;                            // (Ljava/lang/Object;)Z A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/safety/Whitelist_TypedValue')]
  JWhitelist_TypedValue = interface(JObject)
    ['{DFA7C45D-9233-4896-BFBC-169B7C386EC9}']
    function equals(obj : JObject) : boolean; cdecl;                            // (Ljava/lang/Object;)Z A: $1
    function hashCode : Integer; cdecl;                                         // ()I A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJWhitelist_TypedValue = class(TJavaGenericImport<JWhitelist_TypedValueClass, JWhitelist_TypedValue>)
  end;

implementation

end.
