//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_1 = interface;

  JTokeniserState_1Class = interface(JObjectClass)
    ['{27993EE5-561F-4834-80D9-9ED260B7A4BF}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_1')]
  JTokeniserState_1 = interface(JObject)
    ['{6BB61B56-068E-4B83-A6D2-C0304263477F}']
  end;

  TJTokeniserState_1 = class(TJavaGenericImport<JTokeniserState_1Class, JTokeniserState_1>)
  end;

implementation

end.
