//
// Generated by JavaToPas v1.5 20160713 - 141502
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_56;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_56 = interface;

  JTokeniserState_56Class = interface(JObjectClass)
    ['{200C57BC-0062-4275-A87F-951C98487308}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_56')]
  JTokeniserState_56 = interface(JObject)
    ['{F9824141-952D-4F3C-8F3C-C60C27216528}']
  end;

  TJTokeniserState_56 = class(TJavaGenericImport<JTokeniserState_56Class, JTokeniserState_56>)
  end;

implementation

end.
