//
// Generated by JavaToPas v1.5 20160713 - 141453
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_13;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_13 = interface;

  JHtmlTreeBuilderState_13Class = interface(JObjectClass)
    ['{E106F1F8-5D4D-4B16-824D-72CAE7666A97}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_13')]
  JHtmlTreeBuilderState_13 = interface(JObject)
    ['{969A4216-5386-4A23-B8E8-29E69D5A250B}']
  end;

  TJHtmlTreeBuilderState_13 = class(TJavaGenericImport<JHtmlTreeBuilderState_13Class, JHtmlTreeBuilderState_13>)
  end;

implementation

end.
