//
// Generated by JavaToPas v1.5 20160713 - 141511
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.StructuralEvaluator_ImmediateParent;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.select.Evaluator,
  org.jsoup.nodes.Element;

type
  JStructuralEvaluator_ImmediateParent = interface;

  JStructuralEvaluator_ImmediateParentClass = interface(JObjectClass)
    ['{9173665C-D889-4BB5-ADF1-5D9EF3E71D29}']
    function init(evaluator : JEvaluator) : JStructuralEvaluator_ImmediateParent; cdecl;// (Lorg/jsoup/select/Evaluator;)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/StructuralEvaluator_ImmediateParent')]
  JStructuralEvaluator_ImmediateParent = interface(JObject)
    ['{ABFBA6C5-1184-4739-A293-CE63C6C61166}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJStructuralEvaluator_ImmediateParent = class(TJavaGenericImport<JStructuralEvaluator_ImmediateParentClass, JStructuralEvaluator_ImmediateParent>)
  end;

implementation

end.
