//
// Generated by JavaToPas v1.5 20160713 - 141509
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_IndexLessThan;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_IndexLessThan = interface;

  JEvaluator_IndexLessThanClass = interface(JObjectClass)
    ['{4CF1B20E-973F-46D7-80D9-0A8B9DC004DD}']
    function init(&index : Integer) : JEvaluator_IndexLessThan; cdecl;          // (I)V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_IndexLessThan')]
  JEvaluator_IndexLessThan = interface(JObject)
    ['{3813D2D0-B429-4605-AA60-A305802DD454}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_IndexLessThan = class(TJavaGenericImport<JEvaluator_IndexLessThanClass, JEvaluator_IndexLessThan>)
  end;

implementation

end.
