//
// Generated by JavaToPas v1.5 20160713 - 141506
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.safety.Cleaner_ElementMeta;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JCleaner_ElementMeta = interface;

  JCleaner_ElementMetaClass = interface(JObjectClass)
    ['{91E78F11-252D-4296-A6BB-904CACE42B64}']
  end;

  [JavaSignature('org/jsoup/safety/Cleaner_ElementMeta')]
  JCleaner_ElementMeta = interface(JObject)
    ['{9C09E726-EBCB-476E-9A24-0D1AE445EA15}']
  end;

  TJCleaner_ElementMeta = class(TJavaGenericImport<JCleaner_ElementMetaClass, JCleaner_ElementMeta>)
  end;

implementation

end.
