//
// Generated by JavaToPas v1.5 20160713 - 141500
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_27;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_27 = interface;

  JTokeniserState_27Class = interface(JObjectClass)
    ['{33C01FD1-02DA-420F-8783-624BCEDF78D5}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_27')]
  JTokeniserState_27 = interface(JObject)
    ['{FEF3D196-B06D-4916-AE9F-9249F6C8B676}']
  end;

  TJTokeniserState_27 = class(TJavaGenericImport<JTokeniserState_27Class, JTokeniserState_27>)
  end;

implementation

end.
