//
// Generated by JavaToPas v1.5 20160713 - 141444
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.helper.Validate;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JValidate = interface;

  JValidateClass = interface(JObjectClass)
    ['{96AA2DC6-44C5-4337-8ED2-D46DBF11606F}']
    procedure fail(msg : JString) ; cdecl;                                      // (Ljava/lang/String;)V A: $9
    procedure isFalse(val : boolean) ; cdecl; overload;                         // (Z)V A: $9
    procedure isFalse(val : boolean; msg : JString) ; cdecl; overload;          // (ZLjava/lang/String;)V A: $9
    procedure isTrue(val : boolean) ; cdecl; overload;                          // (Z)V A: $9
    procedure isTrue(val : boolean; msg : JString) ; cdecl; overload;           // (ZLjava/lang/String;)V A: $9
    procedure noNullElements(objects : TJavaArray<JObject>) ; cdecl; overload;  // ([Ljava/lang/Object;)V A: $9
    procedure noNullElements(objects : TJavaArray<JObject>; msg : JString) ; cdecl; overload;// ([Ljava/lang/Object;Ljava/lang/String;)V A: $9
    procedure notEmpty(&string : JString) ; cdecl; overload;                    // (Ljava/lang/String;)V A: $9
    procedure notEmpty(&string : JString; msg : JString) ; cdecl; overload;     // (Ljava/lang/String;Ljava/lang/String;)V A: $9
    procedure notNull(obj : JObject) ; cdecl; overload;                         // (Ljava/lang/Object;)V A: $9
    procedure notNull(obj : JObject; msg : JString) ; cdecl; overload;          // (Ljava/lang/Object;Ljava/lang/String;)V A: $9
  end;

  [JavaSignature('org/jsoup/helper/Validate')]
  JValidate = interface(JObject)
    ['{B87761FB-B7A4-4DB2-8CCF-01181332549A}']
  end;

  TJValidate = class(TJavaGenericImport<JValidateClass, JValidate>)
  end;

implementation

end.
