//
// Generated by JavaToPas v1.5 20160713 - 141505
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.XmlTreeBuilder_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JXmlTreeBuilder_1 = interface;

  JXmlTreeBuilder_1Class = interface(JObjectClass)
    ['{601FFB10-9ED9-408D-BC75-A1A5384417C5}']
  end;

  [JavaSignature('org/jsoup/parser/XmlTreeBuilder_1')]
  JXmlTreeBuilder_1 = interface(JObject)
    ['{93B91278-B0EB-4171-8EFF-3120295F6917}']
  end;

  TJXmlTreeBuilder_1 = class(TJavaGenericImport<JXmlTreeBuilder_1Class, JXmlTreeBuilder_1>)
  end;

implementation

end.
