//
// Generated by JavaToPas v1.5 20160713 - 141458
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.Token_Tag;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Attributes;

type
  JToken_Tag = interface;

  JToken_TagClass = interface(JObjectClass)
    ['{BB83B9B4-0845-453B-92E9-9BA8071DC419}']
  end;

  [JavaSignature('org/jsoup/parser/Token_Tag')]
  JToken_Tag = interface(JObject)
    ['{BF28453D-D955-46A2-B23B-7AC036F1A7BF}']
  end;

  TJToken_Tag = class(TJavaGenericImport<JToken_TagClass, JToken_Tag>)
  end;

implementation

end.
