//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_39;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_39 = interface;

  JTokeniserState_39Class = interface(JObjectClass)
    ['{F514E4EB-1E4D-40E7-9D11-84FF4E180B86}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_39')]
  JTokeniserState_39 = interface(JObject)
    ['{86E50B4C-6230-40DF-ACAC-2DC514C4A988}']
  end;

  TJTokeniserState_39 = class(TJavaGenericImport<JTokeniserState_39Class, JTokeniserState_39>)
  end;

implementation

end.
