//
// Generated by JavaToPas v1.5 20160713 - 141506
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.safety.Whitelist_TagName;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JWhitelist_TagName = interface;

  JWhitelist_TagNameClass = interface(JObjectClass)
    ['{0D586A88-F7B2-47F7-877D-8424ED85E5F4}']
  end;

  [JavaSignature('org/jsoup/safety/Whitelist_TagName')]
  JWhitelist_TagName = interface(JObject)
    ['{1C2491B4-D93A-4151-A217-78A2C360B395}']
  end;

  TJWhitelist_TagName = class(TJavaGenericImport<JWhitelist_TagNameClass, JWhitelist_TagName>)
  end;

implementation

end.
