//
// Generated by JavaToPas v1.5 20160713 - 141441
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.helper.DataUtil;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.util.regex.Pattern,
  org.jsoup.nodes.Document,
  org.jsoup.parser.Parser,
  java.nio.ByteBuffer;

type
  JDataUtil = interface;

  JDataUtilClass = interface(JObjectClass)
    ['{B3E5E6CE-825F-4F7C-8156-0C62631B4FC5}']
    function load(&in : JFile; charsetName : JString; baseUri : JString) : JDocument; cdecl; overload;// (Ljava/io/File;Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function load(&in : JInputStream; charsetName : JString; baseUri : JString) : JDocument; cdecl; overload;// (Ljava/io/InputStream;Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/nodes/Document; A: $9
    function load(&in : JInputStream; charsetName : JString; baseUri : JString; parser : JParser) : JDocument; cdecl; overload;// (Ljava/io/InputStream;Ljava/lang/String;Ljava/lang/String;Lorg/jsoup/parser/Parser;)Lorg/jsoup/nodes/Document; A: $9
  end;

  [JavaSignature('org/jsoup/helper/DataUtil')]
  JDataUtil = interface(JObject)
    ['{3C96D611-D8DC-4759-901C-751791061870}']
  end;

  TJDataUtil = class(TJavaGenericImport<JDataUtilClass, JDataUtil>)
  end;

const
  TJDataUtildefaultCharset = 'UTF-8';
  TJDataUtilbufferSize = 131072;
  TJDataUtilUNICODE_BOM = 65279;
  TJDataUtilboundaryLength = 32;

implementation

end.
