//
// Generated by JavaToPas v1.5 20160713 - 141440
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.Connection_Base;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.net.URL,
  org.jsoup.Connection_Method;

type
  JConnection_Base = interface;

  JConnection_BaseClass = interface(JObjectClass)
    ['{6E89FEBE-1634-4639-B029-AB2A01662419}']
    function cookie(JStringparam0 : JString) : JString; cdecl; overload;        // (Ljava/lang/String;)Ljava/lang/String; A: $401
    function cookie(JStringparam0 : JString; JStringparam1 : JString) : JConnection_Base; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/Connection$Base; A: $401
    function cookies : JMap; cdecl;                                             // ()Ljava/util/Map; A: $401
    function hasCookie(JStringparam0 : JString) : boolean; cdecl;               // (Ljava/lang/String;)Z A: $401
    function hasHeader(JStringparam0 : JString) : boolean; cdecl;               // (Ljava/lang/String;)Z A: $401
    function hasHeaderWithValue(JStringparam0 : JString; JStringparam1 : JString) : boolean; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Z A: $401
    function header(JStringparam0 : JString) : JString; cdecl; overload;        // (Ljava/lang/String;)Ljava/lang/String; A: $401
    function header(JStringparam0 : JString; JStringparam1 : JString) : JConnection_Base; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/Connection$Base; A: $401
    function headers : JMap; cdecl;                                             // ()Ljava/util/Map; A: $401
    function method : JConnection_Method; cdecl; overload;                      // ()Lorg/jsoup/Connection$Method; A: $401
    function method(JConnection_Methodparam0 : JConnection_Method) : JConnection_Base; cdecl; overload;// (Lorg/jsoup/Connection$Method;)Lorg/jsoup/Connection$Base; A: $401
    function removeCookie(JStringparam0 : JString) : JConnection_Base; cdecl;   // (Ljava/lang/String;)Lorg/jsoup/Connection$Base; A: $401
    function removeHeader(JStringparam0 : JString) : JConnection_Base; cdecl;   // (Ljava/lang/String;)Lorg/jsoup/Connection$Base; A: $401
    function url : JURL; cdecl; overload;                                       // ()Ljava/net/URL; A: $401
    function url(JURLparam0 : JURL) : JConnection_Base; cdecl; overload;        // (Ljava/net/URL;)Lorg/jsoup/Connection$Base; A: $401
  end;

  [JavaSignature('org/jsoup/Connection_Base')]
  JConnection_Base = interface(JObject)
    ['{9EC4523C-0B8A-47B3-9690-F893CEC4DE9D}']
    function cookie(JStringparam0 : JString) : JString; cdecl; overload;        // (Ljava/lang/String;)Ljava/lang/String; A: $401
    function cookie(JStringparam0 : JString; JStringparam1 : JString) : JConnection_Base; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/Connection$Base; A: $401
    function cookies : JMap; cdecl;                                             // ()Ljava/util/Map; A: $401
    function hasCookie(JStringparam0 : JString) : boolean; cdecl;               // (Ljava/lang/String;)Z A: $401
    function hasHeader(JStringparam0 : JString) : boolean; cdecl;               // (Ljava/lang/String;)Z A: $401
    function hasHeaderWithValue(JStringparam0 : JString; JStringparam1 : JString) : boolean; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Z A: $401
    function header(JStringparam0 : JString) : JString; cdecl; overload;        // (Ljava/lang/String;)Ljava/lang/String; A: $401
    function header(JStringparam0 : JString; JStringparam1 : JString) : JConnection_Base; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/Connection$Base; A: $401
    function headers : JMap; cdecl;                                             // ()Ljava/util/Map; A: $401
    function method : JConnection_Method; cdecl; overload;                      // ()Lorg/jsoup/Connection$Method; A: $401
    function method(JConnection_Methodparam0 : JConnection_Method) : JConnection_Base; cdecl; overload;// (Lorg/jsoup/Connection$Method;)Lorg/jsoup/Connection$Base; A: $401
    function removeCookie(JStringparam0 : JString) : JConnection_Base; cdecl;   // (Ljava/lang/String;)Lorg/jsoup/Connection$Base; A: $401
    function removeHeader(JStringparam0 : JString) : JConnection_Base; cdecl;   // (Ljava/lang/String;)Lorg/jsoup/Connection$Base; A: $401
    function url : JURL; cdecl; overload;                                       // ()Ljava/net/URL; A: $401
    function url(JURLparam0 : JURL) : JConnection_Base; cdecl; overload;        // (Ljava/net/URL;)Lorg/jsoup/Connection$Base; A: $401
  end;

  TJConnection_Base = class(TJavaGenericImport<JConnection_BaseClass, JConnection_Base>)
  end;

implementation

end.
