//
// Generated by JavaToPas v1.5 20160713 - 141456
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_8;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_8 = interface;

  JHtmlTreeBuilderState_8Class = interface(JObjectClass)
    ['{0618016F-205B-4DB2-B284-53FDDC5AEBD3}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_8')]
  JHtmlTreeBuilderState_8 = interface(JObject)
    ['{91D6EAF7-10AA-49DB-AA8C-AE7892784996}']
  end;

  TJHtmlTreeBuilderState_8 = class(TJavaGenericImport<JHtmlTreeBuilderState_8Class, JHtmlTreeBuilderState_8>)
  end;

implementation

end.
