//
// Generated by JavaToPas v1.5 20160713 - 141441
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.helper.HttpConnection_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JHttpConnection_1 = interface;

  JHttpConnection_1Class = interface(JObjectClass)
    ['{92067200-C1F3-4D51-9657-4C5A466329F5}']
  end;

  [JavaSignature('org/jsoup/helper/HttpConnection_1')]
  JHttpConnection_1 = interface(JObject)
    ['{8055F145-1996-4754-B722-2121AB450D9C}']
  end;

  TJHttpConnection_1 = class(TJavaGenericImport<JHttpConnection_1Class, JHttpConnection_1>)
  end;

implementation

end.
