//
// Generated by JavaToPas v1.5 20160713 - 141459
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.Tokeniser;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.CharacterReader,
  org.jsoup.parser.ParseErrorList,
  org.jsoup.parser.Token,
  org.jsoup.parser.Token_Tag,
  org.jsoup.parser.Token_StartTag,
  org.jsoup.parser.Token_EndTag,
  java.lang.Character;

type
  JTokeniserState = interface; // merged
  JTokeniser = interface;

  JTokeniserClass = interface(JObjectClass)
    ['{A0689477-ABAE-48A2-8A38-9CBC886789AA}']
  end;

  [JavaSignature('org/jsoup/parser/Tokeniser')]
  JTokeniser = interface(JObject)
    ['{9D5433CE-2F7F-4FA4-8051-8C6406E43937}']
  end;

  TJTokeniser = class(TJavaGenericImport<JTokeniserClass, JTokeniser>)

  // Merged from: .\org.jsoup.parser.TokeniserState.pas
  JTokeniserStateClass = interface(JObjectClass)
    ['{26F570CD-426E-4697-87ED-01D1DB8D2818}']
    function _GetAfterAttributeName : JTokeniserState; cdecl;                   //  A: $4019
    function _GetAfterAttributeValue_quoted : JTokeniserState; cdecl;           //  A: $4019
    function _GetAfterDoctypeName : JTokeniserState; cdecl;                     //  A: $4019
    function _GetAfterDoctypePublicIdentifier : JTokeniserState; cdecl;         //  A: $4019
    function _GetAfterDoctypePublicKeyword : JTokeniserState; cdecl;            //  A: $4019
    function _GetAfterDoctypeSystemIdentifier : JTokeniserState; cdecl;         //  A: $4019
    function _GetAfterDoctypeSystemKeyword : JTokeniserState; cdecl;            //  A: $4019
    function _GetAttributeName : JTokeniserState; cdecl;                        //  A: $4019
    function _GetAttributeValue_doubleQuoted : JTokeniserState; cdecl;          //  A: $4019
    function _GetAttributeValue_singleQuoted : JTokeniserState; cdecl;          //  A: $4019
    function _GetAttributeValue_unquoted : JTokeniserState; cdecl;              //  A: $4019
    function _GetBeforeAttributeName : JTokeniserState; cdecl;                  //  A: $4019
    function _GetBeforeAttributeValue : JTokeniserState; cdecl;                 //  A: $4019
    function _GetBeforeDoctypeName : JTokeniserState; cdecl;                    //  A: $4019
    function _GetBeforeDoctypePublicIdentifier : JTokeniserState; cdecl;        //  A: $4019
    function _GetBeforeDoctypeSystemIdentifier : JTokeniserState; cdecl;        //  A: $4019
    function _GetBetweenDoctypePublicAndSystemIdentifiers : JTokeniserState; cdecl;//  A: $4019
    function _GetBogusComment : JTokeniserState; cdecl;                         //  A: $4019
    function _GetBogusDoctype : JTokeniserState; cdecl;                         //  A: $4019
    function _GetCdataSection : JTokeniserState; cdecl;                         //  A: $4019
    function _GetCharacterReferenceInData : JTokeniserState; cdecl;             //  A: $4019
    function _GetCharacterReferenceInRcdata : JTokeniserState; cdecl;           //  A: $4019
    function _GetComment : JTokeniserState; cdecl;                              //  A: $4019
    function _GetCommentEnd : JTokeniserState; cdecl;                           //  A: $4019
    function _GetCommentEndBang : JTokeniserState; cdecl;                       //  A: $4019
    function _GetCommentEndDash : JTokeniserState; cdecl;                       //  A: $4019
    function _GetCommentStart : JTokeniserState; cdecl;                         //  A: $4019
    function _GetCommentStartDash : JTokeniserState; cdecl;                     //  A: $4019
    function _GetData : JTokeniserState; cdecl;                                 //  A: $4019
    function _GetDoctype : JTokeniserState; cdecl;                              //  A: $4019
    function _GetDoctypeName : JTokeniserState; cdecl;                          //  A: $4019
    function _GetDoctypePublicIdentifier_doubleQuoted : JTokeniserState; cdecl; //  A: $4019
    function _GetDoctypePublicIdentifier_singleQuoted : JTokeniserState; cdecl; //  A: $4019
    function _GetDoctypeSystemIdentifier_doubleQuoted : JTokeniserState; cdecl; //  A: $4019
    function _GetDoctypeSystemIdentifier_singleQuoted : JTokeniserState; cdecl; //  A: $4019
    function _GetEndTagOpen : JTokeniserState; cdecl;                           //  A: $4019
    function _GetMarkupDeclarationOpen : JTokeniserState; cdecl;                //  A: $4019
    function _GetPLAINTEXT : JTokeniserState; cdecl;                            //  A: $4019
    function _GetRCDATAEndTagName : JTokeniserState; cdecl;                     //  A: $4019
    function _GetRCDATAEndTagOpen : JTokeniserState; cdecl;                     //  A: $4019
    function _GetRawtext : JTokeniserState; cdecl;                              //  A: $4019
    function _GetRawtextEndTagName : JTokeniserState; cdecl;                    //  A: $4019
    function _GetRawtextEndTagOpen : JTokeniserState; cdecl;                    //  A: $4019
    function _GetRawtextLessthanSign : JTokeniserState; cdecl;                  //  A: $4019
    function _GetRcdata : JTokeniserState; cdecl;                               //  A: $4019
    function _GetRcdataLessthanSign : JTokeniserState; cdecl;                   //  A: $4019
    function _GetScriptData : JTokeniserState; cdecl;                           //  A: $4019
    function _GetScriptDataDoubleEscapeEnd : JTokeniserState; cdecl;            //  A: $4019
    function _GetScriptDataDoubleEscapeStart : JTokeniserState; cdecl;          //  A: $4019
    function _GetScriptDataDoubleEscaped : JTokeniserState; cdecl;              //  A: $4019
    function _GetScriptDataDoubleEscapedDash : JTokeniserState; cdecl;          //  A: $4019
    function _GetScriptDataDoubleEscapedDashDash : JTokeniserState; cdecl;      //  A: $4019
    function _GetScriptDataDoubleEscapedLessthanSign : JTokeniserState; cdecl;  //  A: $4019
    function _GetScriptDataEndTagName : JTokeniserState; cdecl;                 //  A: $4019
    function _GetScriptDataEndTagOpen : JTokeniserState; cdecl;                 //  A: $4019
    function _GetScriptDataEscapeStart : JTokeniserState; cdecl;                //  A: $4019
    function _GetScriptDataEscapeStartDash : JTokeniserState; cdecl;            //  A: $4019
    function _GetScriptDataEscaped : JTokeniserState; cdecl;                    //  A: $4019
    function _GetScriptDataEscapedDash : JTokeniserState; cdecl;                //  A: $4019
    function _GetScriptDataEscapedDashDash : JTokeniserState; cdecl;            //  A: $4019
    function _GetScriptDataEscapedEndTagName : JTokeniserState; cdecl;          //  A: $4019
    function _GetScriptDataEscapedEndTagOpen : JTokeniserState; cdecl;          //  A: $4019
    function _GetScriptDataEscapedLessthanSign : JTokeniserState; cdecl;        //  A: $4019
    function _GetScriptDataLessthanSign : JTokeniserState; cdecl;               //  A: $4019
    function _GetSelfClosingStartTag : JTokeniserState; cdecl;                  //  A: $4019
    function _GetTagName : JTokeniserState; cdecl;                              //  A: $4019
    function _GetTagOpen : JTokeniserState; cdecl;                              //  A: $4019
    function valueOf(&name : JString) : JTokeniserState; cdecl;                 // (Ljava/lang/String;)Lorg/jsoup/parser/TokeniserState; A: $9
    function values : TJavaArray<JTokeniserState>; cdecl;                       // ()[Lorg/jsoup/parser/TokeniserState; A: $9
    property AfterAttributeName : JTokeniserState read _GetAfterAttributeName;  // Lorg/jsoup/parser/TokeniserState; A: $4019
    property AfterAttributeValue_quoted : JTokeniserState read _GetAfterAttributeValue_quoted;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property AfterDoctypeName : JTokeniserState read _GetAfterDoctypeName;      // Lorg/jsoup/parser/TokeniserState; A: $4019
    property AfterDoctypePublicIdentifier : JTokeniserState read _GetAfterDoctypePublicIdentifier;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property AfterDoctypePublicKeyword : JTokeniserState read _GetAfterDoctypePublicKeyword;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property AfterDoctypeSystemIdentifier : JTokeniserState read _GetAfterDoctypeSystemIdentifier;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property AfterDoctypeSystemKeyword : JTokeniserState read _GetAfterDoctypeSystemKeyword;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property AttributeName : JTokeniserState read _GetAttributeName;            // Lorg/jsoup/parser/TokeniserState; A: $4019
    property AttributeValue_doubleQuoted : JTokeniserState read _GetAttributeValue_doubleQuoted;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property AttributeValue_singleQuoted : JTokeniserState read _GetAttributeValue_singleQuoted;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property AttributeValue_unquoted : JTokeniserState read _GetAttributeValue_unquoted;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property BeforeAttributeName : JTokeniserState read _GetBeforeAttributeName;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property BeforeAttributeValue : JTokeniserState read _GetBeforeAttributeValue;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property BeforeDoctypeName : JTokeniserState read _GetBeforeDoctypeName;    // Lorg/jsoup/parser/TokeniserState; A: $4019
    property BeforeDoctypePublicIdentifier : JTokeniserState read _GetBeforeDoctypePublicIdentifier;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property BeforeDoctypeSystemIdentifier : JTokeniserState read _GetBeforeDoctypeSystemIdentifier;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property BetweenDoctypePublicAndSystemIdentifiers : JTokeniserState read _GetBetweenDoctypePublicAndSystemIdentifiers;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property BogusComment : JTokeniserState read _GetBogusComment;              // Lorg/jsoup/parser/TokeniserState; A: $4019
    property BogusDoctype : JTokeniserState read _GetBogusDoctype;              // Lorg/jsoup/parser/TokeniserState; A: $4019
    property CdataSection : JTokeniserState read _GetCdataSection;              // Lorg/jsoup/parser/TokeniserState; A: $4019
    property CharacterReferenceInData : JTokeniserState read _GetCharacterReferenceInData;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property CharacterReferenceInRcdata : JTokeniserState read _GetCharacterReferenceInRcdata;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property Comment : JTokeniserState read _GetComment;                        // Lorg/jsoup/parser/TokeniserState; A: $4019
    property CommentEnd : JTokeniserState read _GetCommentEnd;                  // Lorg/jsoup/parser/TokeniserState; A: $4019
    property CommentEndBang : JTokeniserState read _GetCommentEndBang;          // Lorg/jsoup/parser/TokeniserState; A: $4019
    property CommentEndDash : JTokeniserState read _GetCommentEndDash;          // Lorg/jsoup/parser/TokeniserState; A: $4019
    property CommentStart : JTokeniserState read _GetCommentStart;              // Lorg/jsoup/parser/TokeniserState; A: $4019
    property CommentStartDash : JTokeniserState read _GetCommentStartDash;      // Lorg/jsoup/parser/TokeniserState; A: $4019
    property Data : JTokeniserState read _GetData;                              // Lorg/jsoup/parser/TokeniserState; A: $4019
    property Doctype : JTokeniserState read _GetDoctype;                        // Lorg/jsoup/parser/TokeniserState; A: $4019
    property DoctypeName : JTokeniserState read _GetDoctypeName;                // Lorg/jsoup/parser/TokeniserState; A: $4019
    property DoctypePublicIdentifier_doubleQuoted : JTokeniserState read _GetDoctypePublicIdentifier_doubleQuoted;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property DoctypePublicIdentifier_singleQuoted : JTokeniserState read _GetDoctypePublicIdentifier_singleQuoted;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property DoctypeSystemIdentifier_doubleQuoted : JTokeniserState read _GetDoctypeSystemIdentifier_doubleQuoted;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property DoctypeSystemIdentifier_singleQuoted : JTokeniserState read _GetDoctypeSystemIdentifier_singleQuoted;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property EndTagOpen : JTokeniserState read _GetEndTagOpen;                  // Lorg/jsoup/parser/TokeniserState; A: $4019
    property MarkupDeclarationOpen : JTokeniserState read _GetMarkupDeclarationOpen;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property PLAINTEXT : JTokeniserState read _GetPLAINTEXT;                    // Lorg/jsoup/parser/TokeniserState; A: $4019
    property RCDATAEndTagName : JTokeniserState read _GetRCDATAEndTagName;      // Lorg/jsoup/parser/TokeniserState; A: $4019
    property RCDATAEndTagOpen : JTokeniserState read _GetRCDATAEndTagOpen;      // Lorg/jsoup/parser/TokeniserState; A: $4019
    property Rawtext : JTokeniserState read _GetRawtext;                        // Lorg/jsoup/parser/TokeniserState; A: $4019
    property RawtextEndTagName : JTokeniserState read _GetRawtextEndTagName;    // Lorg/jsoup/parser/TokeniserState; A: $4019
    property RawtextEndTagOpen : JTokeniserState read _GetRawtextEndTagOpen;    // Lorg/jsoup/parser/TokeniserState; A: $4019
    property RawtextLessthanSign : JTokeniserState read _GetRawtextLessthanSign;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property Rcdata : JTokeniserState read _GetRcdata;                          // Lorg/jsoup/parser/TokeniserState; A: $4019
    property RcdataLessthanSign : JTokeniserState read _GetRcdataLessthanSign;  // Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptData : JTokeniserState read _GetScriptData;                  // Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataDoubleEscapeEnd : JTokeniserState read _GetScriptDataDoubleEscapeEnd;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataDoubleEscapeStart : JTokeniserState read _GetScriptDataDoubleEscapeStart;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataDoubleEscaped : JTokeniserState read _GetScriptDataDoubleEscaped;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataDoubleEscapedDash : JTokeniserState read _GetScriptDataDoubleEscapedDash;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataDoubleEscapedDashDash : JTokeniserState read _GetScriptDataDoubleEscapedDashDash;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataDoubleEscapedLessthanSign : JTokeniserState read _GetScriptDataDoubleEscapedLessthanSign;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataEndTagName : JTokeniserState read _GetScriptDataEndTagName;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataEndTagOpen : JTokeniserState read _GetScriptDataEndTagOpen;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataEscapeStart : JTokeniserState read _GetScriptDataEscapeStart;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataEscapeStartDash : JTokeniserState read _GetScriptDataEscapeStartDash;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataEscaped : JTokeniserState read _GetScriptDataEscaped;    // Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataEscapedDash : JTokeniserState read _GetScriptDataEscapedDash;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataEscapedDashDash : JTokeniserState read _GetScriptDataEscapedDashDash;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataEscapedEndTagName : JTokeniserState read _GetScriptDataEscapedEndTagName;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataEscapedEndTagOpen : JTokeniserState read _GetScriptDataEscapedEndTagOpen;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataEscapedLessthanSign : JTokeniserState read _GetScriptDataEscapedLessthanSign;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property ScriptDataLessthanSign : JTokeniserState read _GetScriptDataLessthanSign;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property SelfClosingStartTag : JTokeniserState read _GetSelfClosingStartTag;// Lorg/jsoup/parser/TokeniserState; A: $4019
    property TagName : JTokeniserState read _GetTagName;                        // Lorg/jsoup/parser/TokeniserState; A: $4019
    property TagOpen : JTokeniserState read _GetTagOpen;                        // Lorg/jsoup/parser/TokeniserState; A: $4019
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState')]
  JTokeniserState = interface(JObject)
    ['{8B7D69A3-3A0B-4107-8DAC-80AE57BB6241}']
  end;

  TJTokeniserState = class(TJavaGenericImport<JTokeniserStateClass, JTokeniserState>)
  end;

  end;

const
  TJTokeniserStatenullChar = 0;
  TJTokeniserStatereplacementChar = 65533;
  TJTokeniserStateeof = 65535;

  TJTokeniserreplacementChar = 65533;

implementation

end.
