//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_40;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_40 = interface;

  JTokeniserState_40Class = interface(JObjectClass)
    ['{B32D3E4B-BFE5-4469-B8B7-84854B2305D2}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_40')]
  JTokeniserState_40 = interface(JObject)
    ['{7D0DDD15-7030-49AD-880B-B2FA33B0F9DE}']
  end;

  TJTokeniserState_40 = class(TJavaGenericImport<JTokeniserState_40Class, JTokeniserState_40>)
  end;

implementation

end.
