//
// Generated by JavaToPas v1.5 20160713 - 141501
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_44;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_44 = interface;

  JTokeniserState_44Class = interface(JObjectClass)
    ['{F11FC899-AD19-4344-8556-E68A98B7B3E5}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_44')]
  JTokeniserState_44 = interface(JObject)
    ['{DA63620C-A4A4-4B39-987A-C3C9263A2CC7}']
  end;

  TJTokeniserState_44 = class(TJavaGenericImport<JTokeniserState_44Class, JTokeniserState_44>)
  end;

implementation

end.
