//
// Generated by JavaToPas v1.5 20160713 - 141449
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.Entities_1;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JEntities_1 = interface;

  JEntities_1Class = interface(JObjectClass)
    ['{51C6C9CC-F417-4201-A30F-A363D570E0AD}']
  end;

  [JavaSignature('org/jsoup/nodes/Entities_1')]
  JEntities_1 = interface(JObject)
    ['{77B4AE3F-6EE7-48BF-871A-1D49522E3E3F}']
  end;

  TJEntities_1 = class(TJavaGenericImport<JEntities_1Class, JEntities_1>)
  end;

implementation

end.
