//
// Generated by JavaToPas v1.5 20160713 - 141440
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.Connection;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.net.URL,
  java.net.Proxy,
  org.jsoup.Connection_Method,
  org.jsoup.Connection_KeyVal,
  org.jsoup.parser.Parser,
  org.jsoup.nodes.Document,
  org.jsoup.Connection_Response,
  org.jsoup.Connection_Request;

type
  JConnection = interface;

  JConnectionClass = interface(JObjectClass)
    ['{0D4885BE-63B4-40A5-A11A-74FDF66DAD26}']
    function cookie(JStringparam0 : JString; JStringparam1 : JString) : JConnection; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function cookies(JMapparam0 : JMap) : JConnection; cdecl;                   // (Ljava/util/Map;)Lorg/jsoup/Connection; A: $401
    function data(JCollectionparam0 : JCollection) : JConnection; cdecl; overload;// (Ljava/util/Collection;)Lorg/jsoup/Connection; A: $401
    function data(JMapparam0 : JMap) : JConnection; cdecl; overload;            // (Ljava/util/Map;)Lorg/jsoup/Connection; A: $401
    function data(JStringparam0 : JString) : JConnection_KeyVal; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/Connection$KeyVal; A: $401
    function data(JStringparam0 : JString; JStringparam1 : JString) : JConnection; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function data(JStringparam0 : JString; JStringparam1 : JString; JInputStreamparam2 : JInputStream) : JConnection; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;Ljava/io/InputStream;)Lorg/jsoup/Connection; A: $401
    function data(TJavaArrayJStringparam0 : TJavaArray<JString>) : JConnection; cdecl; overload;// ([Ljava/lang/String;)Lorg/jsoup/Connection; A: $481
    function execute : JConnection_Response; cdecl;                             // ()Lorg/jsoup/Connection$Response; A: $401
    function followRedirects(booleanparam0 : boolean) : JConnection; cdecl;     // (Z)Lorg/jsoup/Connection; A: $401
    function get : JDocument; cdecl;                                            // ()Lorg/jsoup/nodes/Document; A: $401
    function header(JStringparam0 : JString; JStringparam1 : JString) : JConnection; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function ignoreContentType(booleanparam0 : boolean) : JConnection; cdecl;   // (Z)Lorg/jsoup/Connection; A: $401
    function ignoreHttpErrors(booleanparam0 : boolean) : JConnection; cdecl;    // (Z)Lorg/jsoup/Connection; A: $401
    function maxBodySize(Integerparam0 : Integer) : JConnection; cdecl;         // (I)Lorg/jsoup/Connection; A: $401
    function method(JConnection_Methodparam0 : JConnection_Method) : JConnection; cdecl;// (Lorg/jsoup/Connection$Method;)Lorg/jsoup/Connection; A: $401
    function parser(JParserparam0 : JParser) : JConnection; cdecl;              // (Lorg/jsoup/parser/Parser;)Lorg/jsoup/Connection; A: $401
    function post : JDocument; cdecl;                                           // ()Lorg/jsoup/nodes/Document; A: $401
    function postDataCharset(JStringparam0 : JString) : JConnection; cdecl;     // (Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function proxy(JProxyparam0 : JProxy) : JConnection; cdecl; overload;       // (Ljava/net/Proxy;)Lorg/jsoup/Connection; A: $401
    function proxy(JStringparam0 : JString; Integerparam1 : Integer) : JConnection; cdecl; overload;// (Ljava/lang/String;I)Lorg/jsoup/Connection; A: $401
    function referrer(JStringparam0 : JString) : JConnection; cdecl;            // (Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function request : JConnection_Request; cdecl; overload;                    // ()Lorg/jsoup/Connection$Request; A: $401
    function request(JConnection_Requestparam0 : JConnection_Request) : JConnection; cdecl; overload;// (Lorg/jsoup/Connection$Request;)Lorg/jsoup/Connection; A: $401
    function requestBody(JStringparam0 : JString) : JConnection; cdecl;         // (Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function response : JConnection_Response; cdecl; overload;                  // ()Lorg/jsoup/Connection$Response; A: $401
    function response(JConnection_Responseparam0 : JConnection_Response) : JConnection; cdecl; overload;// (Lorg/jsoup/Connection$Response;)Lorg/jsoup/Connection; A: $401
    function timeout(Integerparam0 : Integer) : JConnection; cdecl;             // (I)Lorg/jsoup/Connection; A: $401
    function url(JStringparam0 : JString) : JConnection; cdecl; overload;       // (Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function url(JURLparam0 : JURL) : JConnection; cdecl; overload;             // (Ljava/net/URL;)Lorg/jsoup/Connection; A: $401
    function userAgent(JStringparam0 : JString) : JConnection; cdecl;           // (Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function validateTLSCertificates(booleanparam0 : boolean) : JConnection; cdecl;// (Z)Lorg/jsoup/Connection; A: $401
  end;

  [JavaSignature('org/jsoup/Connection$KeyVal')]
  JConnection = interface(JObject)
    ['{351D837E-B0FC-49B9-89C2-01B5624233CC}']
    function cookie(JStringparam0 : JString; JStringparam1 : JString) : JConnection; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function cookies(JMapparam0 : JMap) : JConnection; cdecl;                   // (Ljava/util/Map;)Lorg/jsoup/Connection; A: $401
    function data(JCollectionparam0 : JCollection) : JConnection; cdecl; overload;// (Ljava/util/Collection;)Lorg/jsoup/Connection; A: $401
    function data(JMapparam0 : JMap) : JConnection; cdecl; overload;            // (Ljava/util/Map;)Lorg/jsoup/Connection; A: $401
    function data(JStringparam0 : JString) : JConnection_KeyVal; cdecl; overload;// (Ljava/lang/String;)Lorg/jsoup/Connection$KeyVal; A: $401
    function data(JStringparam0 : JString; JStringparam1 : JString) : JConnection; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function data(JStringparam0 : JString; JStringparam1 : JString; JInputStreamparam2 : JInputStream) : JConnection; cdecl; overload;// (Ljava/lang/String;Ljava/lang/String;Ljava/io/InputStream;)Lorg/jsoup/Connection; A: $401
    function data(TJavaArrayJStringparam0 : TJavaArray<JString>) : JConnection; cdecl; overload;// ([Ljava/lang/String;)Lorg/jsoup/Connection; A: $481
    function execute : JConnection_Response; cdecl;                             // ()Lorg/jsoup/Connection$Response; A: $401
    function followRedirects(booleanparam0 : boolean) : JConnection; cdecl;     // (Z)Lorg/jsoup/Connection; A: $401
    function get : JDocument; cdecl;                                            // ()Lorg/jsoup/nodes/Document; A: $401
    function header(JStringparam0 : JString; JStringparam1 : JString) : JConnection; cdecl;// (Ljava/lang/String;Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function ignoreContentType(booleanparam0 : boolean) : JConnection; cdecl;   // (Z)Lorg/jsoup/Connection; A: $401
    function ignoreHttpErrors(booleanparam0 : boolean) : JConnection; cdecl;    // (Z)Lorg/jsoup/Connection; A: $401
    function maxBodySize(Integerparam0 : Integer) : JConnection; cdecl;         // (I)Lorg/jsoup/Connection; A: $401
    function method(JConnection_Methodparam0 : JConnection_Method) : JConnection; cdecl;// (Lorg/jsoup/Connection$Method;)Lorg/jsoup/Connection; A: $401
    function parser(JParserparam0 : JParser) : JConnection; cdecl;              // (Lorg/jsoup/parser/Parser;)Lorg/jsoup/Connection; A: $401
    function post : JDocument; cdecl;                                           // ()Lorg/jsoup/nodes/Document; A: $401
    function postDataCharset(JStringparam0 : JString) : JConnection; cdecl;     // (Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function proxy(JProxyparam0 : JProxy) : JConnection; cdecl; overload;       // (Ljava/net/Proxy;)Lorg/jsoup/Connection; A: $401
    function proxy(JStringparam0 : JString; Integerparam1 : Integer) : JConnection; cdecl; overload;// (Ljava/lang/String;I)Lorg/jsoup/Connection; A: $401
    function referrer(JStringparam0 : JString) : JConnection; cdecl;            // (Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function request : JConnection_Request; cdecl; overload;                    // ()Lorg/jsoup/Connection$Request; A: $401
    function request(JConnection_Requestparam0 : JConnection_Request) : JConnection; cdecl; overload;// (Lorg/jsoup/Connection$Request;)Lorg/jsoup/Connection; A: $401
    function requestBody(JStringparam0 : JString) : JConnection; cdecl;         // (Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function response : JConnection_Response; cdecl; overload;                  // ()Lorg/jsoup/Connection$Response; A: $401
    function response(JConnection_Responseparam0 : JConnection_Response) : JConnection; cdecl; overload;// (Lorg/jsoup/Connection$Response;)Lorg/jsoup/Connection; A: $401
    function timeout(Integerparam0 : Integer) : JConnection; cdecl;             // (I)Lorg/jsoup/Connection; A: $401
    function url(JStringparam0 : JString) : JConnection; cdecl; overload;       // (Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function url(JURLparam0 : JURL) : JConnection; cdecl; overload;             // (Ljava/net/URL;)Lorg/jsoup/Connection; A: $401
    function userAgent(JStringparam0 : JString) : JConnection; cdecl;           // (Ljava/lang/String;)Lorg/jsoup/Connection; A: $401
    function validateTLSCertificates(booleanparam0 : boolean) : JConnection; cdecl;// (Z)Lorg/jsoup/Connection; A: $401
  end;

  TJConnection = class(TJavaGenericImport<JConnectionClass, JConnection>)
  end;

implementation

end.
