//
// Generated by JavaToPas v1.5 20160713 - 141447
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.nodes.DocumentType;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  java.lang.Appendable,
  org.jsoup.nodes.Document_OutputSettings;

type
  JDocumentType = interface;

  JDocumentTypeClass = interface(JObjectClass)
    ['{ADA2E585-53DD-4C2C-9851-7B67A4AE3A86}']
    function init(&name : JString; publicId : JString; systemId : JString; baseUri : JString) : JDocumentType; cdecl;// (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V A: $1
    function nodeName : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/nodes/DocumentType')]
  JDocumentType = interface(JObject)
    ['{35EF4B72-1F5B-459D-AA21-7A9C047A2E2D}']
    function nodeName : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJDocumentType = class(TJavaGenericImport<JDocumentTypeClass, JDocumentType>)
  end;

const
  TJDocumentTypeNAME = 'name';
  TJDocumentTypePUBLIC_ID = 'publicId';
  TJDocumentTypeSYSTEM_ID = 'systemId';

implementation

end.
