//
// Generated by JavaToPas v1.5 20160713 - 141456
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_Constants;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes;

type
  JHtmlTreeBuilderState_Constants = interface;

  JHtmlTreeBuilderState_ConstantsClass = interface(JObjectClass)
    ['{6D60A96C-6772-4107-84B8-2AA2911DBD74}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_Constants')]
  JHtmlTreeBuilderState_Constants = interface(JObject)
    ['{DE209634-E965-49EC-A0E3-F62783CC8AE6}']
  end;

  TJHtmlTreeBuilderState_Constants = class(TJavaGenericImport<JHtmlTreeBuilderState_ConstantsClass, JHtmlTreeBuilderState_Constants>)
  end;

implementation

end.
