//
// Generated by JavaToPas v1.5 20160713 - 141454
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.HtmlTreeBuilderState_16;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Token,
  org.jsoup.parser.HtmlTreeBuilder;

type
  JHtmlTreeBuilderState_16 = interface;

  JHtmlTreeBuilderState_16Class = interface(JObjectClass)
    ['{9B717545-859A-41C7-9692-AF2D6895EBB6}']
  end;

  [JavaSignature('org/jsoup/parser/HtmlTreeBuilderState_16')]
  JHtmlTreeBuilderState_16 = interface(JObject)
    ['{A1E7DEC1-D10B-433C-8631-B035D0B699CA}']
  end;

  TJHtmlTreeBuilderState_16 = class(TJavaGenericImport<JHtmlTreeBuilderState_16Class, JHtmlTreeBuilderState_16>)
  end;

implementation

end.
