//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_62;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_62 = interface;

  JTokeniserState_62Class = interface(JObjectClass)
    ['{F51B62B1-BA41-4E07-911A-1D478A7BD69E}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_62')]
  JTokeniserState_62 = interface(JObject)
    ['{11DBA93C-A4A2-4316-A57A-7D2AE79E7DA7}']
  end;

  TJTokeniserState_62 = class(TJavaGenericImport<JTokeniserState_62Class, JTokeniserState_62>)
  end;

implementation

end.
