//
// Generated by JavaToPas v1.5 20160713 - 141509
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.select.Evaluator_IsOnlyChild;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.nodes.Element;

type
  JEvaluator_IsOnlyChild = interface;

  JEvaluator_IsOnlyChildClass = interface(JObjectClass)
    ['{6F53C852-6901-4B20-B906-9ED0E7AE8F64}']
    function init : JEvaluator_IsOnlyChild; cdecl;                              // ()V A: $1
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  [JavaSignature('org/jsoup/select/Evaluator_IsOnlyChild')]
  JEvaluator_IsOnlyChild = interface(JObject)
    ['{EA9D5879-27F4-403E-8AFF-BB9E2F1F400A}']
    function matches(root : JElement; element : JElement) : boolean; cdecl;     // (Lorg/jsoup/nodes/Element;Lorg/jsoup/nodes/Element;)Z A: $1
    function toString : JString; cdecl;                                         // ()Ljava/lang/String; A: $1
  end;

  TJEvaluator_IsOnlyChild = class(TJavaGenericImport<JEvaluator_IsOnlyChildClass, JEvaluator_IsOnlyChild>)
  end;

implementation

end.
