//
// Generated by JavaToPas v1.5 20160713 - 141506
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.safety.Cleaner;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.safety.Whitelist,
  org.jsoup.nodes.Document,
  org.jsoup.nodes.Element,
  org.jsoup.safety.Cleaner_ElementMeta;

type
  JCleaner = interface;

  JCleanerClass = interface(JObjectClass)
    ['{D8535FDF-F546-4925-98C8-7211E6EA5E1A}']
    function clean(dirtyDocument : JDocument) : JDocument; cdecl;               // (Lorg/jsoup/nodes/Document;)Lorg/jsoup/nodes/Document; A: $1
    function init(whitelist : JWhitelist) : JCleaner; cdecl;                    // (Lorg/jsoup/safety/Whitelist;)V A: $1
    function isValid(dirtyDocument : JDocument) : boolean; cdecl;               // (Lorg/jsoup/nodes/Document;)Z A: $1
  end;

  [JavaSignature('org/jsoup/safety/Cleaner$ElementMeta')]
  JCleaner = interface(JObject)
    ['{CB35B177-9DE2-4081-91D8-D38A5D61D59A}']
    function clean(dirtyDocument : JDocument) : JDocument; cdecl;               // (Lorg/jsoup/nodes/Document;)Lorg/jsoup/nodes/Document; A: $1
    function isValid(dirtyDocument : JDocument) : boolean; cdecl;               // (Lorg/jsoup/nodes/Document;)Z A: $1
  end;

  TJCleaner = class(TJavaGenericImport<JCleanerClass, JCleaner>)
  end;

implementation

end.
