//
// Generated by JavaToPas v1.5 20160713 - 141503
////////////////////////////////////////////////////////////////////////////////
unit org.jsoup.parser.TokeniserState_57;

interface

uses
  AndroidAPI.JNIBridge,
  Androidapi.JNI.JavaTypes,
  org.jsoup.parser.Tokeniser,
  org.jsoup.parser.CharacterReader;

type
  JTokeniserState_57 = interface;

  JTokeniserState_57Class = interface(JObjectClass)
    ['{E5F10CD9-D795-4629-AF2C-52975D18AF92}']
  end;

  [JavaSignature('org/jsoup/parser/TokeniserState_57')]
  JTokeniserState_57 = interface(JObject)
    ['{25FF4BEF-59E9-45E2-9D60-1E2C397A365A}']
  end;

  TJTokeniserState_57 = class(TJavaGenericImport<JTokeniserState_57Class, JTokeniserState_57>)
  end;

implementation

end.
